// Mock data for development - Replace with Firestore in production
import type {
  Customer,
  Bid,
  Job,
  Invoice,
  TeamMember,
  Activity,
  DashboardStats,
  ScheduledItem,
  Transaction,
  BankAccount,
  AIThread,
} from '@/types';

// Helper to create dates
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);
const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000);

// ==================== CUSTOMERS ====================
export const mockCustomers: Customer[] = [
  {
    id: 'cust_1',
    companyId: 'comp_1',
    firstName: 'John',
    lastName: 'Mitchell',
    email: 'john.mitchell@email.com',
    phone: '(860) 555-0123',
    address: { street: '142 Oak Street', city: 'Hartford', state: 'CT', zip: '06103' },
    tags: ['residential', 'repeat'],
    notes: 'Prefers morning appointments',
    source: 'referral',
    totalRevenue: 8450,
    jobCount: 3,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cust_2',
    companyId: 'comp_1',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@techcorp.com',
    phone: '(203) 555-0456',
    address: { street: '500 Main Street', city: 'New Haven', state: 'CT', zip: '06510' },
    tags: ['commercial', 'vip'],
    notes: 'Building manager for TechCorp offices',
    source: 'google',
    totalRevenue: 24750,
    jobCount: 7,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(2),
  },
  {
    id: 'cust_3',
    companyId: 'comp_1',
    firstName: 'Michael',
    lastName: 'Rodriguez',
    email: 'mrodriguez@gmail.com',
    phone: '(860) 555-0789',
    address: { street: '78 Maple Avenue', city: 'West Hartford', state: 'CT', zip: '06107' },
    tags: ['residential'],
    source: 'website',
    totalRevenue: 2150,
    jobCount: 1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'cust_4',
    companyId: 'comp_1',
    firstName: 'Emily',
    lastName: 'Thompson',
    email: 'emily.t@propmanage.com',
    phone: '(203) 555-0321',
    address: { street: '1200 Chapel Street', city: 'New Haven', state: 'CT', zip: '06511' },
    tags: ['commercial', 'property-manager'],
    notes: 'Manages 12 properties',
    source: 'referral',
    totalRevenue: 45200,
    jobCount: 18,
    createdAt: daysAgo(540),
    updatedAt: daysAgo(1),
  },
  {
    id: 'cust_5',
    companyId: 'comp_1',
    firstName: 'David',
    lastName: 'Park',
    email: 'dpark@parkrestaurants.com',
    phone: '(860) 555-0654',
    address: { street: '55 Pratt Street', city: 'Hartford', state: 'CT', zip: '06103' },
    tags: ['commercial', 'restaurant'],
    source: 'yelp',
    totalRevenue: 12800,
    jobCount: 4,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(15),
  },
];

// ==================== BIDS ====================
export const mockBids: Bid[] = [
  {
    id: 'bid_1',
    companyId: 'comp_1',
    customerId: 'cust_1',
    customer: mockCustomers[0],
    title: 'Panel Upgrade - 200A Service',
    description: 'Upgrade existing 100A panel to 200A service with new meter base',
    status: 'sent',
    options: [
      {
        id: 'opt_1',
        name: 'Good',
        description: 'Standard 200A panel upgrade',
        lineItems: [
          { id: 'li_1', description: '200A Main Panel', quantity: 1, unitPrice: 450, total: 450 },
          { id: 'li_2', description: 'Labor', quantity: 8, unitPrice: 125, total: 1000 },
          { id: 'li_3', description: 'Permits & Inspection', quantity: 1, unitPrice: 250, total: 250 },
        ],
        subtotal: 1700,
        isRecommended: false,
      },
      {
        id: 'opt_2',
        name: 'Better',
        description: '200A panel with whole-home surge protection',
        lineItems: [
          { id: 'li_4', description: '200A Main Panel', quantity: 1, unitPrice: 450, total: 450 },
          { id: 'li_5', description: 'Whole-Home Surge Protector', quantity: 1, unitPrice: 350, total: 350 },
          { id: 'li_6', description: 'Labor', quantity: 10, unitPrice: 125, total: 1250 },
          { id: 'li_7', description: 'Permits & Inspection', quantity: 1, unitPrice: 250, total: 250 },
        ],
        subtotal: 2300,
        isRecommended: true,
      },
      {
        id: 'opt_3',
        name: 'Best',
        description: '200A smart panel with monitoring and surge protection',
        lineItems: [
          { id: 'li_8', description: 'Span Smart Panel 200A', quantity: 1, unitPrice: 3500, total: 3500 },
          { id: 'li_9', description: 'Whole-Home Surge Protector', quantity: 1, unitPrice: 350, total: 350 },
          { id: 'li_10', description: 'Labor', quantity: 12, unitPrice: 125, total: 1500 },
          { id: 'li_11', description: 'Permits & Inspection', quantity: 1, unitPrice: 250, total: 250 },
        ],
        subtotal: 5600,
        isRecommended: false,
      },
    ],
    addOns: [
      { id: 'addon_1', name: 'EV Charger Circuit', description: '50A circuit for future EV charger', price: 450 },
      { id: 'addon_2', name: 'Generator Interlock', description: 'Manual transfer switch for generator', price: 650 },
    ],
    selectedAddOnIds: [],
    subtotal: 2300,
    tax: 146.63,
    total: 2446.63,
    depositRequired: 500,
    depositPaid: false,
    validUntil: daysFromNow(14),
    sentAt: daysAgo(2),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'bid_2',
    companyId: 'comp_1',
    customerId: 'cust_2',
    customer: mockCustomers[1],
    title: 'Office Lighting Retrofit - LED',
    description: 'Replace all fluorescent fixtures with LED panels',
    status: 'accepted',
    options: [
      {
        id: 'opt_4',
        name: 'Standard',
        description: 'Replace 48 fluorescent fixtures with LED panels',
        lineItems: [
          { id: 'li_12', description: '2x4 LED Panel (48)', quantity: 48, unitPrice: 85, total: 4080 },
          { id: 'li_13', description: 'Labor', quantity: 24, unitPrice: 125, total: 3000 },
        ],
        subtotal: 7080,
        isRecommended: true,
      },
    ],
    addOns: [],
    selectedOptionId: 'opt_4',
    selectedAddOnIds: [],
    subtotal: 7080,
    tax: 451.35,
    total: 7531.35,
    depositRequired: 2000,
    depositPaid: true,
    validUntil: daysFromNow(7),
    signedAt: daysAgo(5),
    sentAt: daysAgo(10),
    viewedAt: daysAgo(8),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(5),
  },
  {
    id: 'bid_3',
    companyId: 'comp_1',
    customerId: 'cust_3',
    customer: mockCustomers[2],
    title: 'Outdoor Lighting Installation',
    description: 'Install landscape lighting and path lights',
    status: 'draft',
    options: [
      {
        id: 'opt_5',
        name: 'Basic Package',
        description: '6 path lights and 4 uplights',
        lineItems: [
          { id: 'li_14', description: 'Path Lights (6)', quantity: 6, unitPrice: 75, total: 450 },
          { id: 'li_15', description: 'Uplights (4)', quantity: 4, unitPrice: 95, total: 380 },
          { id: 'li_16', description: 'Transformer', quantity: 1, unitPrice: 250, total: 250 },
          { id: 'li_17', description: 'Labor', quantity: 6, unitPrice: 125, total: 750 },
        ],
        subtotal: 1830,
        isRecommended: false,
      },
    ],
    addOns: [],
    selectedAddOnIds: [],
    subtotal: 1830,
    tax: 116.66,
    total: 1946.66,
    depositRequired: 400,
    depositPaid: false,
    validUntil: daysFromNow(30),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// ==================== JOBS ====================
export const mockJobs: Job[] = [
  {
    id: 'job_1',
    companyId: 'comp_1',
    customerId: 'cust_2',
    customer: mockCustomers[1],
    bidId: 'bid_2',
    title: 'Office Lighting Retrofit - LED',
    description: 'Replace 48 fluorescent fixtures with LED panels at TechCorp offices',
    status: 'in_progress',
    priority: 'high',
    address: { street: '500 Main Street', city: 'New Haven', state: 'CT', zip: '06510' },
    scheduledStart: daysAgo(1),
    scheduledEnd: daysFromNow(2),
    actualStart: daysAgo(1),
    assignedTo: ['team_1', 'team_2'],
    estimatedValue: 7531.35,
    actualCost: 0,
    notes: [
      {
        id: 'note_1',
        content: 'Customer requested we work outside business hours. Start time 6PM.',
        authorId: 'user_1',
        authorName: 'Mike Johnson',
        createdAt: daysAgo(2),
      },
    ],
    photos: [],
    tags: ['commercial', 'lighting'],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: 'job_2',
    companyId: 'comp_1',
    customerId: 'cust_4',
    customer: mockCustomers[3],
    title: 'Emergency - No Power Unit 4B',
    description: 'Tenant reporting complete power loss in unit',
    status: 'scheduled',
    priority: 'urgent',
    address: { street: '1200 Chapel Street, Unit 4B', city: 'New Haven', state: 'CT', zip: '06511' },
    scheduledStart: new Date(),
    scheduledEnd: new Date(Date.now() + 4 * 60 * 60 * 1000),
    assignedTo: ['team_1'],
    estimatedValue: 350,
    actualCost: 0,
    notes: [],
    photos: [],
    tags: ['emergency', 'residential'],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'job_3',
    companyId: 'comp_1',
    customerId: 'cust_5',
    customer: mockCustomers[4],
    title: 'Kitchen Hood Wiring',
    description: 'Install dedicated circuit for new commercial hood',
    status: 'scheduled',
    priority: 'normal',
    address: { street: '55 Pratt Street', city: 'Hartford', state: 'CT', zip: '06103' },
    scheduledStart: daysFromNow(3),
    scheduledEnd: daysFromNow(3),
    assignedTo: ['team_2'],
    estimatedValue: 1200,
    actualCost: 0,
    notes: [],
    photos: [],
    tags: ['commercial', 'restaurant'],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'job_4',
    companyId: 'comp_1',
    customerId: 'cust_1',
    customer: mockCustomers[0],
    title: 'Ceiling Fan Installation',
    description: 'Install 3 ceiling fans with remotes',
    status: 'completed',
    priority: 'low',
    address: { street: '142 Oak Street', city: 'Hartford', state: 'CT', zip: '06103' },
    scheduledStart: daysAgo(10),
    scheduledEnd: daysAgo(10),
    actualStart: daysAgo(10),
    actualEnd: daysAgo(10),
    assignedTo: ['team_3'],
    estimatedValue: 850,
    actualCost: 320,
    notes: [],
    photos: [],
    tags: ['residential'],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: 'job_5',
    companyId: 'comp_1',
    customerId: 'cust_4',
    customer: mockCustomers[3],
    title: 'Parking Lot Light Repair',
    description: 'Replace 3 failed LED fixtures in parking lot',
    status: 'invoiced',
    priority: 'normal',
    address: { street: '1200 Chapel Street', city: 'New Haven', state: 'CT', zip: '06511' },
    scheduledStart: daysAgo(7),
    scheduledEnd: daysAgo(7),
    actualStart: daysAgo(7),
    actualEnd: daysAgo(7),
    assignedTo: ['team_1', 'team_3'],
    estimatedValue: 2400,
    actualCost: 980,
    notes: [],
    photos: [],
    tags: ['commercial', 'outdoor'],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(5),
  },
];

// ==================== INVOICES ====================
export const mockInvoices: Invoice[] = [
  {
    id: 'inv_1',
    companyId: 'comp_1',
    customerId: 'cust_4',
    customer: mockCustomers[3],
    jobId: 'job_5',
    invoiceNumber: 'INV-2026-0042',
    status: 'sent',
    lineItems: [
      { id: 'ili_1', description: 'LED Parking Lot Fixture (3)', quantity: 3, unitPrice: 450, total: 1350 },
      { id: 'ili_2', description: 'Labor - Lift Rental', quantity: 1, unitPrice: 350, total: 350 },
      { id: 'ili_3', description: 'Labor', quantity: 6, unitPrice: 125, total: 750 },
    ],
    subtotal: 2450,
    taxRate: 6.35,
    tax: 155.58,
    total: 2605.58,
    amountPaid: 0,
    amountDue: 2605.58,
    dueDate: daysFromNow(15),
    sentAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'inv_2',
    companyId: 'comp_1',
    customerId: 'cust_1',
    customer: mockCustomers[0],
    jobId: 'job_4',
    invoiceNumber: 'INV-2026-0041',
    status: 'paid',
    lineItems: [
      { id: 'ili_4', description: 'Ceiling Fan w/ Remote (3)', quantity: 3, unitPrice: 180, total: 540 },
      { id: 'ili_5', description: 'Installation Labor', quantity: 4, unitPrice: 125, total: 500 },
    ],
    subtotal: 1040,
    taxRate: 6.35,
    tax: 66.04,
    total: 1106.04,
    amountPaid: 1106.04,
    amountDue: 0,
    dueDate: daysAgo(3),
    sentAt: daysAgo(10),
    paidAt: daysAgo(8),
    paymentMethod: 'card',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },
  {
    id: 'inv_3',
    companyId: 'comp_1',
    customerId: 'cust_5',
    customer: mockCustomers[4],
    invoiceNumber: 'INV-2026-0038',
    status: 'overdue',
    lineItems: [
      { id: 'ili_6', description: 'GFCI Outlet Installation (4)', quantity: 4, unitPrice: 85, total: 340 },
      { id: 'ili_7', description: 'Labor', quantity: 2, unitPrice: 125, total: 250 },
    ],
    subtotal: 590,
    taxRate: 6.35,
    tax: 37.47,
    total: 627.47,
    amountPaid: 0,
    amountDue: 627.47,
    dueDate: daysAgo(10),
    sentAt: daysAgo(25),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(10),
  },
  {
    id: 'inv_4',
    companyId: 'comp_1',
    customerId: 'cust_2',
    customer: mockCustomers[1],
    invoiceNumber: 'INV-2026-0035',
    status: 'paid',
    lineItems: [
      { id: 'ili_8', description: 'Dedicated Circuit for Server Room', quantity: 1, unitPrice: 650, total: 650 },
      { id: 'ili_9', description: 'UPS Installation', quantity: 1, unitPrice: 1200, total: 1200 },
      { id: 'ili_10', description: 'Labor', quantity: 8, unitPrice: 125, total: 1000 },
    ],
    subtotal: 2850,
    taxRate: 6.35,
    tax: 180.98,
    total: 3030.98,
    amountPaid: 3030.98,
    amountDue: 0,
    dueDate: daysAgo(20),
    sentAt: daysAgo(35),
    paidAt: daysAgo(30),
    paymentMethod: 'ach',
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
  },
];

// ==================== TEAM ====================
export const mockTeam: TeamMember[] = [
  {
    id: 'team_1',
    companyId: 'comp_1',
    userId: 'user_1',
    email: 'mike@mitchellelectric.com',
    name: 'Mike Johnson',
    role: 'admin',
    phone: '(860) 555-1001',
    isActive: true,
    lastActive: new Date(),
    location: { lat: 41.7637, lng: -72.6851, timestamp: new Date() },
    createdAt: daysAgo(365),
  },
  {
    id: 'team_2',
    companyId: 'comp_1',
    userId: 'user_2',
    email: 'carlos@mitchellelectric.com',
    name: 'Carlos Rivera',
    role: 'field_tech',
    phone: '(860) 555-1002',
    isActive: true,
    lastActive: new Date(Date.now() - 15 * 60 * 1000),
    location: { lat: 41.3083, lng: -72.9279, timestamp: new Date(Date.now() - 15 * 60 * 1000) },
    createdAt: daysAgo(180),
  },
  {
    id: 'team_3',
    companyId: 'comp_1',
    userId: 'user_3',
    email: 'james@mitchellelectric.com',
    name: 'James Wilson',
    role: 'field_tech',
    phone: '(860) 555-1003',
    isActive: true,
    lastActive: new Date(Date.now() - 45 * 60 * 1000),
    createdAt: daysAgo(90),
  },
  {
    id: 'team_4',
    companyId: 'comp_1',
    userId: 'user_4',
    email: 'lisa@mitchellelectric.com',
    name: 'Lisa Martinez',
    role: 'office',
    phone: '(860) 555-1004',
    isActive: true,
    lastActive: new Date(),
    createdAt: daysAgo(270),
  },
];

// ==================== ACTIVITY ====================
export const mockActivity: Activity[] = [
  {
    id: 'act_1',
    companyId: 'comp_1',
    userId: 'user_1',
    userName: 'Mike Johnson',
    type: 'paid',
    entityType: 'invoice',
    entityId: 'inv_2',
    entityName: 'INV-2026-0041',
    description: 'Payment received for $1,106.04',
    createdAt: daysAgo(8),
  },
  {
    id: 'act_2',
    companyId: 'comp_1',
    userId: 'user_2',
    userName: 'Carlos Rivera',
    type: 'completed',
    entityType: 'job',
    entityId: 'job_4',
    entityName: 'Ceiling Fan Installation',
    description: 'Job marked as completed',
    createdAt: daysAgo(10),
  },
  {
    id: 'act_3',
    companyId: 'comp_1',
    userId: 'user_1',
    userName: 'Mike Johnson',
    type: 'accepted',
    entityType: 'bid',
    entityId: 'bid_2',
    entityName: 'Office Lighting Retrofit',
    description: 'Bid accepted by Sarah Chen',
    createdAt: daysAgo(5),
  },
  {
    id: 'act_4',
    companyId: 'comp_1',
    userId: 'user_4',
    userName: 'Lisa Martinez',
    type: 'sent',
    entityType: 'invoice',
    entityId: 'inv_1',
    entityName: 'INV-2026-0042',
    description: 'Invoice sent to Emily Thompson',
    createdAt: daysAgo(5),
  },
  {
    id: 'act_5',
    companyId: 'comp_1',
    userId: 'user_1',
    userName: 'Mike Johnson',
    type: 'created',
    entityType: 'job',
    entityId: 'job_2',
    entityName: 'Emergency - No Power Unit 4B',
    description: 'Emergency job created',
    createdAt: daysAgo(0),
  },
];

// ==================== SCHEDULE ====================
export const mockSchedule: ScheduledItem[] = [
  {
    id: 'sched_1',
    type: 'job',
    title: 'Emergency - No Power Unit 4B',
    description: 'Tenant reporting complete power loss',
    start: new Date(),
    end: new Date(Date.now() + 4 * 60 * 60 * 1000),
    allDay: false,
    jobId: 'job_2',
    customerId: 'cust_4',
    assignedTo: ['team_1'],
    color: '#ef4444',
  },
  {
    id: 'sched_2',
    type: 'job',
    title: 'Office Lighting Retrofit - Day 2',
    description: 'Continue LED panel installation',
    start: new Date(new Date().setHours(18, 0, 0, 0)),
    end: new Date(new Date().setHours(23, 0, 0, 0)),
    allDay: false,
    jobId: 'job_1',
    customerId: 'cust_2',
    assignedTo: ['team_1', 'team_2'],
    color: '#3b82f6',
  },
  {
    id: 'sched_3',
    type: 'job',
    title: 'Kitchen Hood Wiring',
    description: 'Install dedicated circuit',
    start: daysFromNow(3),
    end: daysFromNow(3),
    allDay: false,
    jobId: 'job_3',
    customerId: 'cust_5',
    assignedTo: ['team_2'],
    color: '#10b981',
  },
  {
    id: 'sched_4',
    type: 'appointment',
    title: 'Site Visit - New Construction',
    description: 'Walk-through for bid preparation',
    start: daysFromNow(1),
    end: daysFromNow(1),
    allDay: false,
    assignedTo: ['team_1'],
    color: '#8b5cf6',
  },
];

// ==================== FINANCES ====================
export const mockBankAccounts: BankAccount[] = [
  {
    id: 'bank_1',
    companyId: 'comp_1',
    plaidItemId: 'plaid_item_1',
    plaidAccountId: 'plaid_acct_1',
    name: 'Business Checking',
    officialName: 'Business Premium Checking',
    type: 'checking',
    mask: '4523',
    currentBalance: 47892.34,
    availableBalance: 47892.34,
    lastSynced: new Date(),
    isActive: true,
  },
  {
    id: 'bank_2',
    companyId: 'comp_1',
    plaidItemId: 'plaid_item_1',
    plaidAccountId: 'plaid_acct_2',
    name: 'Business Savings',
    officialName: 'Business Money Market',
    type: 'savings',
    mask: '7891',
    currentBalance: 25000.00,
    availableBalance: 25000.00,
    lastSynced: new Date(),
    isActive: true,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_1',
    companyId: 'comp_1',
    bankAccountId: 'bank_1',
    date: daysAgo(1),
    description: 'Payment from John Mitchell',
    merchantName: 'Stripe',
    amount: 1106.04,
    category: 'income',
    isIncome: true,
    invoiceId: 'inv_2',
    isReviewed: true,
    createdAt: daysAgo(1),
  },
  {
    id: 'txn_2',
    companyId: 'comp_1',
    bankAccountId: 'bank_1',
    date: daysAgo(2),
    description: 'Ferguson Enterprises',
    merchantName: 'Ferguson',
    amount: -892.45,
    category: 'materials',
    isIncome: false,
    isReviewed: true,
    createdAt: daysAgo(2),
  },
  {
    id: 'txn_3',
    companyId: 'comp_1',
    bankAccountId: 'bank_1',
    date: daysAgo(3),
    description: 'Shell Gas Station',
    merchantName: 'Shell',
    amount: -78.50,
    category: 'fuel',
    isIncome: false,
    isReviewed: true,
    createdAt: daysAgo(3),
  },
  {
    id: 'txn_4',
    companyId: 'comp_1',
    bankAccountId: 'bank_1',
    date: daysAgo(4),
    description: 'Home Depot',
    merchantName: 'Home Depot',
    amount: -234.87,
    category: 'materials',
    isIncome: false,
    isReviewed: false,
    createdAt: daysAgo(4),
  },
  {
    id: 'txn_5',
    companyId: 'comp_1',
    bankAccountId: 'bank_1',
    date: daysAgo(5),
    description: 'Payment from TechCorp',
    merchantName: 'Stripe',
    amount: 3030.98,
    category: 'income',
    isIncome: true,
    invoiceId: 'inv_4',
    isReviewed: true,
    createdAt: daysAgo(5),
  },
];

// ==================== AI THREADS ====================
export const mockAIThreads: AIThread[] = [
  {
    id: 'thread_1',
    companyId: 'comp_1',
    userId: 'user_1',
    title: 'Help with panel load calculation',
    messageCount: 8,
    lastMessageAt: daysAgo(1),
    linkedEntity: { type: 'bid', id: 'bid_1', name: 'Panel Upgrade - 200A Service' },
    createdAt: daysAgo(3),
  },
  {
    id: 'thread_2',
    companyId: 'comp_1',
    userId: 'user_1',
    title: 'Create invoice for LED retrofit',
    messageCount: 4,
    lastMessageAt: daysAgo(5),
    linkedEntity: { type: 'job', id: 'job_1', name: 'Office Lighting Retrofit' },
    createdAt: daysAgo(5),
  },
];

// ==================== DASHBOARD STATS ====================
export const mockDashboardStats: DashboardStats = {
  bids: {
    pending: 2,
    sent: 1,
    accepted: 1,
    totalValue: 11924.64,
    conversionRate: 68,
  },
  jobs: {
    scheduled: 2,
    inProgress: 1,
    completed: 15,
    completedThisMonth: 8,
  },
  invoices: {
    draft: 0,
    sent: 1,
    overdue: 1,
    overdueAmount: 627.47,
    paidThisMonth: 4137.02,
  },
  revenue: {
    today: 0,
    thisWeek: 1106.04,
    thisMonth: 12485.50,
    lastMonth: 18742.30,
    monthOverMonthChange: -33.4,
  },
};

// ==================== REVENUE CHART DATA ====================
export const mockRevenueData = [
  { date: 'Jan', revenue: 18500, expenses: 7200, profit: 11300 },
  { date: 'Feb', revenue: 22100, expenses: 8100, profit: 14000 },
  { date: 'Mar', revenue: 19800, expenses: 7800, profit: 12000 },
  { date: 'Apr', revenue: 25400, expenses: 9200, profit: 16200 },
  { date: 'May', revenue: 28900, expenses: 10500, profit: 18400 },
  { date: 'Jun', revenue: 32100, expenses: 11200, profit: 20900 },
  { date: 'Jul', revenue: 29500, expenses: 10800, profit: 18700 },
  { date: 'Aug', revenue: 34200, expenses: 12100, profit: 22100 },
  { date: 'Sep', revenue: 31800, expenses: 11500, profit: 20300 },
  { date: 'Oct', revenue: 27600, expenses: 10200, profit: 17400 },
  { date: 'Nov', revenue: 24300, expenses: 9100, profit: 15200 },
  { date: 'Dec', revenue: 18742, expenses: 7500, profit: 11242 },
];

export const mockJobsByStatus = [
  { name: 'Completed', value: 156, color: '#10b981' },
  { name: 'In Progress', value: 12, color: '#3b82f6' },
  { name: 'Scheduled', value: 8, color: '#8b5cf6' },
  { name: 'Lead', value: 5, color: '#f59e0b' },
];

export const mockRevenueByCategory = [
  { name: 'Commercial', value: 145000, color: '#3b82f6' },
  { name: 'Residential', value: 82000, color: '#10b981' },
  { name: 'Service Calls', value: 34000, color: '#f59e0b' },
  { name: 'Emergency', value: 18000, color: '#ef4444' },
];
