#!/usr/bin/env python3
"""5-language batch 16: P values (second half) + Q values"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("Policy", "Polis", "Полис", "보험증권", "Hợp đồng bảo hiểm", "Polisiya")
t("Policy #", "Polis #", "Полис #", "보험증권 #", "Hợp đồng bảo hiểm #", "Polisiya #")
t("Policy #:", "Polis #:", "Полис #:", "보험증권 #:", "Hợp đồng bảo hiểm #:", "Polisiya #:")
t("Policy:", "Polis:", "Полис:", "보험증권:", "Hợp đồng bảo hiểm:", "Polisiya:")
t("Policyholder", "Detantè Polis", "Страхователь", "보험 계약자", "Chủ hợp đồng bảo hiểm", "Policyholder")
t("Portal URL", "URL Pòtay", "URL портала", "포털 URL", "URL cổng", "URL ng Portal")
t("Portal Username", "Non Itilizatè Pòtay", "Имя пользователя портала", "포털 사용자명", "Tên người dùng cổng", "Username sa Portal")
t("Portfolio", "Pòtfèy", "Портфель", "포트폴리오", "Danh mục", "Portfolio")
t("Portfolio / Website", "Pòtfèy / Sit Wèb", "Портфолио / Сайт", "포트폴리오 / 웹사이트", "Danh mục / Website", "Portfolio / Website")
t("Portfolio Health", "Sante Pòtfèy", "Здоровье портфеля", "포트폴리오 건전성", "Sức khỏe danh mục", "Kalusugan ng Portfolio")
t("Portfolio Photos", "Foto Pòtfèy", "Фото портфеля", "포트폴리오 사진", "Ảnh danh mục", "Mga Litrato ng Portfolio")
t("Portfolio View", "Vi Pòtfèy", "Вид портфеля", "포트폴리오 보기", "Xem danh mục", "Portfolio View")
t("Position", "Pozisyon", "Должность", "직위", "Vị trí", "Posisyon")
t("Position Title", "Tit Pozisyon", "Название должности", "직위명", "Chức danh", "Titulo ng Posisyon")
t("Positions Available", "Pozisyon Disponib", "Доступные вакансии", "채용 가능 직위", "Vị trí tuyển dụng", "Mga Available na Posisyon")
t("Powered by Z", "Powered by Z", "Работает на Z", "Z 제공", "Được hỗ trợ bởi Z", "Powered by Z")
t("Powered by the rent ledger", "Alimante pa rejis lwaye a", "На основе реестра аренды", "임대료 원장 기반", "Được hỗ trợ bởi sổ cái thuê", "Pinapagana ng rent ledger")
t("Pre-Closeout", "Avan-Fèmti", "Предварительное закрытие", "사전 종결", "Trước khi đóng", "Pre-Closeout")
t("Pre-Loss Value", "Valè Avan-Pèt", "Стоимость до ущерба", "손실 전 가치", "Giá trị trước tổn thất", "Pre-Loss Value")
t("Preferences", "Preferans", "Настройки", "환경설정", "Tùy chọn", "Mga Kagustuhan")
t("Preferred Contact", "Kontak Prefere", "Предпочтительный контакт", "선호 연락처", "Liên hệ ưu tiên", "Mas Gustong Kontak")
t("Preferred Contact Method", "Metòd Kontak Prefere", "Предпочтительный способ связи", "선호 연락 방법", "Phương thức liên hệ ưu tiên", "Mas Gustong Paraan ng Pakikipag-ugnayan")
t("Preliminary Notice", "Avi Preliminè", "Предварительное уведомление", "사전 통지", "Thông báo sơ bộ", "Preliminary Notice")
t("Premium", "Premyòm", "Премиум", "프리미엄", "Cao cấp", "Premium")
t("Prepared For", "Prepare Pou", "Подготовлено для", "준비 대상", "Chuẩn bị cho", "Inihanda Para Kay")
t("Prev.", "Presi.", "Пред.", "이전", "Trước", "Nakar.")
t("Prev. Done", "Presi. Fini", "Пред. завершённый", "이전 완료", "Trước đã xong", "Naunang Tapos")
t("Prevention", "Prevansyon", "Профилактика", "예방", "Phòng ngừa", "Pag-iwas")
t("Preview", "Apèsi", "Предпросмотр", "미리보기", "Xem trước", "Preview")
t("Price Book", "Liv Pri", "Прайс-лист", "가격표", "Bảng giá", "Price Book")
t("Price Discrepancies", "Eskaleman Pri", "Расхождения цен", "가격 차이", "Chênh lệch giá", "Mga Price Discrepancy")
t("Price Optimization", "Optimizasyon Pri", "Оптимизация цен", "가격 최적화", "Tối ưu hóa giá", "Price Optimization")
t("Pricing Adjustments", "Ajisteman Pri", "Ценовые корректировки", "가격 조정", "Điều chỉnh giá", "Mga Pricing Adjustment")
t("Pricing Analytics", "Analitik Pri", "Ценовая аналитика", "가격 분석", "Phân tích giá", "Pricing Analytics")
t("Pricing Database Coverage", "Kouvèti Baz Done Pri", "Покрытие базы данных цен", "가격 데이터베이스 커버리지", "Phạm vi cơ sở dữ liệu giá", "Saklaw ng Pricing Database")
t("Pricing History", "Istwa Pri", "История цен", "가격 이력", "Lịch sử giá", "Kasaysayan ng Presyo")
t("Pricing Options", "Opsyon Pri", "Ценовые варианты", "가격 옵션", "Tùy chọn giá", "Mga Pricing Option")
t("Pricing Rules", "Règ Pri", "Ценовые правила", "가격 규칙", "Quy tắc giá", "Mga Pricing Rule")
t("Pricing Tiers", "Nivo Pri", "Ценовые уровни", "가격 등급", "Bậc giá", "Mga Pricing Tier")
t("Primary", "Prensipal", "Основной", "기본", "Chính", "Pangunahin")
t("Primary Contact", "Kontak Prensipal", "Основной контакт", "기본 연락처", "Liên hệ chính", "Pangunahing Kontak")
t("Primary Email", "Imèl Prensipal", "Основной email", "기본 이메일", "Email chính", "Pangunahing Email")
t("Primary Phone", "Telefòn Prensipal", "Основной телефон", "기본 전화", "Điện thoại chính", "Pangunahing Telepono")
t("Primary Pitch", "Pant Prensipal", "Основной уклон", "기본 경사", "Độ dốc chính", "Pangunahing Pitch")
t("Principal Balance", "Balans Prensipal", "Основной баланс", "원금 잔액", "Số dư gốc", "Principal Balance")
t("Private", "Prive", "Частный", "비공개", "Riêng tư", "Pribado")
t("Pro Plan", "Plan Pwo", "Тариф Pro", "프로 요금제", "Gói Pro", "Pro Plan")
t("Processing", "An Tretman", "Обработка", "처리 중", "Đang xử lý", "Pinoproseso")
t("Processing Fee", "Frè Tretman", "Комиссия обработки", "처리 수수료", "Phí xử lý", "Processing Fee")
t("Processing Fees", "Frè Tretman", "Комиссии обработки", "처리 수수료", "Phí xử lý", "Mga Processing Fee")
t("Professional-Grade Tools", "Zouti Nivo Pwofesyonèl", "Профессиональные инструменты", "전문가급 도구", "Công cụ chuyên nghiệp", "Professional-Grade na Mga Tool")
t("Profile Information", "Enfòmasyon Pwofil", "Информация профиля", "프로필 정보", "Thông tin hồ sơ", "Impormasyon ng Profile")
t("Profile Photo", "Foto Pwofil", "Фото профиля", "프로필 사진", "Ảnh hồ sơ", "Litrato ng Profile")
t("Profile Settings", "Paramèt Pwofil", "Настройки профиля", "프로필 설정", "Cài đặt hồ sơ", "Mga Setting ng Profile")
t("Profit & Loss", "Pwofi & Pèt", "Прибыли и убытки", "손익", "Lãi & Lỗ", "Kita & Pagkalugi")
t("Profit & Loss Statement", "Deklarasyon Pwofi & Pèt", "Отчёт о прибылях и убытках", "손익 계산서", "Báo cáo lãi lỗ", "Ulat ng Kita & Pagkalugi")
t("Profit & Loss Summary", "Rezime Pwofi & Pèt", "Сводка прибылей и убытков", "손익 요약", "Tóm tắt lãi lỗ", "Buod ng Kita & Pagkalugi")
t("Profit Margin", "Maj Pwofi", "Маржа прибыли", "이윤율", "Biên lợi nhuận", "Profit Margin")
t("Profit This Month", "Pwofi Mwa Sa a", "Прибыль этого месяца", "이번 달 이익", "Lợi nhuận tháng này", "Kita Ngayong Buwan")
t("Program", "Pwogram", "Программа", "프로그램", "Chương trình", "Programa")
t("Program Type", "Tip Pwogram", "Тип программы", "프로그램 유형", "Loại chương trình", "Uri ng Programa")
t("Programs", "Pwogram", "Программы", "프로그램", "Chương trình", "Mga Programa")
t("Programs (TPA)", "Pwogram (TPA)", "Программы (ТПА)", "프로그램 (TPA)", "Chương trình (TPA)", "Mga Programa (TPA)")
t("Progress Chart", "Cha Pwogrè", "График прогресса", "진행 차트", "Biểu đồ tiến độ", "Progress Chart")
t("Progress Check", "Verifikasyon Pwogrè", "Проверка прогресса", "진행 확인", "Kiểm tra tiến độ", "Progress Check")
t("Project Details", "Detay Pwojè", "Детали проекта", "프로젝트 상세", "Chi tiết dự án", "Detalye ng Proyekto")
t("Project Manager", "Manadjè Pwojè", "Руководитель проекта", "프로젝트 매니저", "Quản lý dự án", "Project Manager")
t("Project Photos", "Foto Pwojè", "Фото проекта", "프로젝트 사진", "Ảnh dự án", "Mga Litrato ng Proyekto")
t("Projected", "Pwojekte", "Прогноз", "예상", "Dự kiến", "Inaasahan")
t("Projected Margin", "Maj Pwojekte", "Прогнозная маржа", "예상 마진", "Biên lợi nhuận dự kiến", "Inaasahang Margin")
t("Property / Unit", "Pwopriyete / Inite", "Объект / Помещение", "부동산 / 유닛", "Bất động sản / Đơn vị", "Property / Unit")
t("Property Address", "Adrès Pwopriyete", "Адрес объекта", "부동산 주소", "Địa chỉ bất động sản", "Address ng Property")
t("Property Assets", "Byen Pwopriyete", "Активы объекта", "부동산 자산", "Tài sản bất động sản", "Mga Asset ng Property")
t("Property Inspections", "Enspeksyon Pwopriyete", "Инспекции объектов", "부동산 검사", "Kiểm tra bất động sản", "Mga Property Inspection")
t("Property Portal Preview", "Apèsi Pòtay Pwopriyete", "Предпросмотр портала объекта", "부동산 포털 미리보기", "Xem trước cổng bất động sản", "Preview ng Property Portal")
t("Property Recon", "Rekon Pwopriyete", "Разведка объекта", "부동산 정찰", "Trinh sát bất động sản", "Property Recon")
t("Property Research Links", "Lyen Rechèch Pwopriyete", "Ссылки для исследования объекта", "부동산 조사 링크", "Liên kết nghiên cứu bất động sản", "Mga Property Research Link")
t("Property Scan", "Eskanè Pwopriyete", "Сканирование объекта", "부동산 스캔", "Quét bất động sản", "Property Scan")
t("Property Scans", "Eskanè Pwopriyete", "Сканирования объектов", "부동산 스캔", "Quét bất động sản", "Mga Property Scan")
t("Property Tax", "Taks Pwopriyete", "Налог на имущество", "재산세", "Thuế bất động sản", "Property Tax")
t("Property Type", "Tip Pwopriyete", "Тип объекта", "부동산 유형", "Loại bất động sản", "Uri ng Property")
t("Property data from:", "Done pwopriyete soti nan:", "Данные объекта из:", "부동산 데이터 출처:", "Dữ liệu bất động sản từ:", "Property data mula sa:")
t("Property not found", "Pwopriyete pa jwenn", "Объект не найден", "부동산을 찾을 수 없음", "Không tìm thấy bất động sản", "Hindi nahanap ang property")
t("Property walkthroughs and site assessments", "Vizit pwopriyete ak evalyasyon sit", "Обходы и оценка площадки", "부동산 현장 조사 및 현장 평가", "Khảo sát bất động sản và đánh giá hiện trường", "Mga property walkthrough at site assessment")
t("Proposal", "Pwopozisyon", "Предложение", "제안서", "Đề xuất", "Proposal")
t("Proposal Sent", "Pwopozisyon Voye", "Предложение отправлено", "제안서 전송됨", "Đã gửi đề xuất", "Naipadala ang Proposal")
t("Public", "Piblik", "Публичный", "공개", "Công khai", "Pampubliko")
t("Punch List", "Lis Ponch", "Дефектная ведомость", "펀치 리스트", "Danh sách sửa chữa", "Punch List")
t("Punch List Items", "Atik Lis Ponch", "Позиции дефектной ведомости", "펀치 리스트 항목", "Mục danh sách sửa chữa", "Mga Punch List Item")
t("Purchase Cost", "Koût Acha", "Стоимость покупки", "구매 비용", "Chi phí mua", "Gastos sa Pagbili")
t("Purchase Date", "Dat Acha", "Дата покупки", "구매일", "Ngày mua", "Petsa ng Pagbili")
t("Purchase Orders", "Kòmann Acha", "Заказы на закупку", "구매 주문", "Đơn đặt hàng", "Mga Purchase Order")
t("Purchase Price", "Pri Acha", "Цена покупки", "구매 가격", "Giá mua", "Presyo ng Pagbili")
t("Push Notifications", "Notifikasyon Push", "Push-уведомления", "푸시 알림", "Thông báo đẩy", "Mga Push Notification")
# Q values
t("Qty", "Kte", "Кол-во", "수량", "SL", "Qty")
t("Qualified", "Kalifye", "Квалифицирован", "자격 충족", "Đủ điều kiện", "Kwalipikado")
t("Quality Control", "Kontwòl Kalite", "Контроль качества", "품질 관리", "Kiểm soát chất lượng", "Quality Control")
t("Quality control, safety compliance, and punch lists", "Kontwòl kalite, konformite sekirite, ak lis ponch", "Контроль качества, безопасность и дефектные ведомости", "품질 관리, 안전 규정 준수 및 펀치 리스트", "Kiểm soát chất lượng, tuân thủ an toàn và danh sách sửa chữa", "Quality control, safety compliance, at punch list")
t("Quarterly", "Chak Trimès", "Ежеквартально", "분기별", "Hàng quý", "Quarterly")
t("Quarterly Payment", "Peman Chak Trimès", "Ежеквартальный платёж", "분기 납입", "Thanh toán hàng quý", "Quarterly na Bayad")
t("Quick Access", "Aksè Rapid", "Быстрый доступ", "빠른 접근", "Truy cập nhanh", "Quick Access")
t("Quick Actions", "Aksyon Rapid", "Быстрые действия", "빠른 작업", "Thao tác nhanh", "Mga Quick Action")
t("Quick Info", "Enfò Rapid", "Краткая информация", "간략 정보", "Thông tin nhanh", "Quick Info")
t("Quick Links", "Lyen Rapid", "Быстрые ссылки", "빠른 링크", "Liên kết nhanh", "Mga Quick Link")
t("Quick Messages", "Mesaj Rapid", "Быстрые сообщения", "빠른 메시지", "Tin nhắn nhanh", "Mga Quick Message")
t("Quote", "Kotasyon", "Ценовое предложение", "견적", "Báo giá", "Quote")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
