#!/usr/bin/env python3
"""5-language batch 9: M values"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("MAT:", "MAT:", "MAT:", "MAT:", "MAT:", "MAT:")
t("MTD breakdown", "Dekoupaj MTD", "Разбивка с начала месяца", "월초부터 분석", "Phân tích từ đầu tháng", "MTD breakdown")
t("Maintenance", "Antretyen", "Обслуживание", "유지보수", "Bảo trì", "Maintenance")
t("Maintenance Jobs", "Travay Antretyen", "Заказы обслуживания", "유지보수 작업", "Công việc bảo trì", "Mga Maintenance na Trabaho")
t("Maintenance Pipeline", "Pipeline Antretyen", "Воронка обслуживания", "유지보수 파이프라인", "Kênh bảo trì", "Maintenance Pipeline")
t("Maintenance Requests", "Demann Antretyen", "Запросы на обслуживание", "유지보수 요청", "Yêu cầu bảo trì", "Mga Request ng Maintenance")
t("Maintenance Timeline", "Kronoloji Antretyen", "Хронология обслуживания", "유지보수 타임라인", "Dòng thời gian bảo trì", "Timeline ng Maintenance")
t("Maintenance requests for this property will appear here", "Demann antretyen pou pwopriyete sa a ap parèt isit", "Запросы обслуживания этого объекта появятся здесь", "이 부동산의 유지보수 요청이 여기에 표시됩니다", "Yêu cầu bảo trì cho bất động sản này sẽ hiển thị ở đây", "Mga maintenance request para sa property na ito ay lalabas dito")
t("Make", "Mak", "Марка", "제조사", "Hãng", "Make")
t("Make / Model / Year", "Mak / Modèl / Ane", "Марка / Модель / Год", "제조사 / 모델 / 연식", "Hãng / Mẫu / Năm", "Make / Model / Taon")
t("Male", "Gason", "Мужской", "남성", "Nam", "Lalaki")
t("Manage", "Jere", "Управление", "관리", "Quản lý", "Pamahalaan")
t("Manage API access for integrations and automations", "Jere aksè API pou entegrasyon ak otomatizasyon", "Управление API-доступом для интеграций и автоматизации", "통합 및 자동화를 위한 API 접근 관리", "Quản lý truy cập API cho tích hợp và tự động hóa", "Pamahalaan ang API access para sa mga integration at automation")
t("Manage Stripe", "Jere Stripe", "Управление Stripe", "Stripe 관리", "Quản lý Stripe", "Pamahalaan ang Stripe")
t("Manage Third-Party Administrator program enrollments", "Jere enskripsyon pwogram TPA", "Управление регистрацией в программах ТПА", "TPA 프로그램 등록 관리", "Quản lý đăng ký chương trình TPA", "Pamahalaan ang mga TPA program enrollment")
t("Manage accounting periods and year-end close", "Jere peryòd kontab ak fèmti fen dane", "Управление отчётными периодами и закрытием года", "회계 기간 및 연말 마감 관리", "Quản lý kỳ kế toán và đóng sổ cuối năm", "Pamahalaan ang mga accounting period at year-end close")
t("Manage checklists for inspections across all trades", "Jere lis tchèk pou enspeksyon nan tout metye", "Управление чек-листами для инспекций по всем специальностям", "모든 공종의 검사 체크리스트 관리", "Quản lý danh sách kiểm tra cho tất cả ngành", "Pamahalaan ang mga checklist para sa inspeksyon sa lahat ng trade")
t("Manage company locations and assign team members", "Jere kote konpayi ak asiye manm ekip", "Управление офисами и назначение сотрудников", "회사 위치 관리 및 팀원 배정", "Quản lý địa điểm công ty và phân công thành viên", "Pamahalaan ang mga lokasyon ng kompanya at mag-assign ng team member")
t("Manage customer email communications", "Jere kominikasyon imèl kliyan", "Управление email-общением с клиентами", "고객 이메일 커뮤니케이션 관리", "Quản lý liên lạc email với khách hàng", "Pamahalaan ang email communication sa mga customer")
t("Manage employee timesheets and approvals", "Jere fèy tan anplwaye ak apwobasyon", "Управление табелями и утверждениями", "직원 타임시트 및 승인 관리", "Quản lý bảng chấm công và phê duyệt", "Pamahalaan ang timesheet at approval ng mga empleyado")
t("Manage employees, benefits, and compliance", "Jere anplwaye, avantaj, ak konformite", "Управление сотрудниками, льготами и соответствием", "직원, 복리후생 및 규정 준수 관리", "Quản lý nhân viên, phúc lợi và tuân thủ", "Pamahalaan ang mga empleyado, benepisyo, at compliance")
t("Manage job postings, applicants, and interviews", "Jere piblikasyon travay, aplikan, ak entèvyou", "Управление вакансиями, кандидатами и собеседованиями", "채용 공고, 지원자 및 면접 관리", "Quản lý tin tuyển dụng, ứng viên và phỏng vấn", "Pamahalaan ang mga job posting, aplikante, at interview")
t("Manage recurring maintenance contracts", "Jere kontra antretyen regilye", "Управление договорами регулярного обслуживания", "정기 유지보수 계약 관리", "Quản lý hợp đồng bảo trì định kỳ", "Pamahalaan ang mga recurring maintenance contract")
t("Manage restoration equipment deployments and tracking", "Jere deplwaman ekipman restorasyon ak swivi", "Управление развертыванием оборудования восстановления", "복원 장비 배치 및 추적 관리", "Quản lý triển khai và theo dõi thiết bị phục hồi", "Pamahalaan ang deployment at tracking ng restoration equipment")
t("Manage suppliers and accounting vendors", "Jere founisè ak vandè kontab", "Управление поставщиками и контрагентами", "공급업체 및 회계 거래처 관리", "Quản lý nhà cung cấp và đối tác kế toán", "Pamahalaan ang mga supplier at accounting vendor")
t("Manage tax rates for invoices and bids", "Jere to taks pou fakti ak òf", "Управление налоговыми ставками для счетов и заявок", "청구서 및 입찰의 세율 관리", "Quản lý thuế suất cho hóa đơn và đấu thầu", "Pamahalaan ang mga tax rate para sa invoice at bid")
t("Manage tenants across all your properties", "Jere lokatè nan tout pwopriyete ou", "Управление арендаторами по всем объектам", "모든 부동산의 세입자 관리", "Quản lý người thuê trên tất cả bất động sản", "Pamahalaan ang mga tenant sa lahat ng property mo")
t("Manage third-party integrations", "Jere entegrasyon tyès pati", "Управление сторонними интеграциями", "서드파티 통합 관리", "Quản lý tích hợp bên thứ ba", "Pamahalaan ang mga third-party integration")
t("Manage turnover tasks from move-out to re-lease", "Jere travay tounen depi demenajman jiska re-lwaye", "Управление задачами при смене арендаторов", "퇴거부터 재임대까지 턴오버 작업 관리", "Quản lý nhiệm vụ luân chuyển từ trả phòng đến tái cho thuê", "Pamahalaan ang mga turnover task mula move-out hanggang re-lease")
t("Manage who has access to your account", "Jere kilès ki gen aksè nan kont ou", "Управление доступом к аккаунту", "계정 접근 권한 관리", "Quản lý quyền truy cập tài khoản", "Pamahalaan kung sino ang may access sa account mo")
t("Manage your account and preferences", "Jere kont ou ak preferans ou", "Управление аккаунтом и настройками", "계정 및 환경설정 관리", "Quản lý tài khoản và tùy chọn", "Pamahalaan ang account at mga kagustuhan mo")
t("Manage your customer relationships", "Jere relasyon kliyan ou", "Управление отношениями с клиентами", "고객 관계 관리", "Quản lý quan hệ khách hàng", "Pamahalaan ang mga relasyon sa customer")
t("Manage your jobs and track progress", "Jere travay ou epi swiv pwogrè", "Управление заказами и отслеживание прогресса", "작업 관리 및 진행 상황 추적", "Quản lý công việc và theo dõi tiến độ", "Pamahalaan ang mga trabaho at i-track ang progress")
t("Manage your property portfolio", "Jere pòtfèy pwopriyete ou", "Управление портфелем недвижимости", "부동산 포트폴리오 관리", "Quản lý danh mục bất động sản", "Pamahalaan ang property portfolio mo")
t("Manage your subcontractor network", "Jere rezo sou-kontraktè ou", "Управление сетью субподрядчиков", "하도급업체 네트워크 관리", "Quản lý mạng lưới nhà thầu phụ", "Pamahalaan ang network ng subcontractor mo")
t("Management fees", "Frè jesyon", "Комиссия за управление", "관리 수수료", "Phí quản lý", "Mga management fee")
t("Manager", "Manadjè", "Менеджер", "매니저", "Quản lý", "Manager")
t("Manager Summary", "Rezime Manadjè", "Сводка менеджера", "매니저 요약", "Tóm tắt quản lý", "Buod ng Manager")
t("Manual payment recording", "Anrejistreman peman manyèl", "Ручная запись платежей", "수동 결제 기록", "Ghi nhận thanh toán thủ công", "Manual na pag-record ng bayad")
t("Manufacturer", "Fabrikè", "Производитель", "제조업체", "Nhà sản xuất", "Manufacturer")
t("Manufacturer Warranty", "Garanti Fabrikè", "Гарантия производителя", "제조업체 보증", "Bảo hành nhà sản xuất", "Garantiya ng Manufacturer")
t("Map", "Kat", "Карта", "지도", "Bản đồ", "Mapa")
t("Map View", "Vi Kat", "Вид карты", "지도 보기", "Xem bản đồ", "Map View")
t("Mark Approved", "Make Apwouve", "Отметить утверждённым", "승인 처리", "Đánh dấu đã duyệt", "Markahan bilang Approved")
t("Mark Passed", "Make Pase", "Отметить пройденным", "통과 처리", "Đánh dấu đạt", "Markahan bilang Passed")
t("Mark Read", "Make Li", "Отметить прочитанным", "읽음 처리", "Đánh dấu đã đọc", "Markahan bilang Nabasa")
t("Mark Sent", "Make Voye", "Отметить отправленным", "전송 처리", "Đánh dấu đã gửi", "Markahan bilang Naipadala")
t("Mark Unread", "Make Pa Li", "Отметить непрочитанным", "읽지 않음 처리", "Đánh dấu chưa đọc", "Markahan bilang Hindi Nabasa")
t("Mark as Dry", "Make tankou Sèk", "Отметить как сухое", "건조 처리", "Đánh dấu khô", "Markahan bilang Tuyo")
t("Mark as Paid", "Make tankou Peye", "Отметить оплаченным", "결제 완료 처리", "Đánh dấu đã thanh toán", "Markahan bilang Nabayaran")
t("Market Rent", "Lwaye Mache", "Рыночная аренда", "시장 임대료", "Giá thuê thị trường", "Market Rent")
t("Marketplace", "Mache", "Маркетплейс", "마켓플레이스", "Thị trường", "Marketplace")
t("Marketplace Settings", "Paramèt Mache", "Настройки маркетплейса", "마켓플레이스 설정", "Cài đặt thị trường", "Mga Setting ng Marketplace")
t("Markup", "Majè", "Наценка", "마크업", "Phụ phí", "Markup")
t("Match", "Korespondans", "Совпадение", "매칭", "Khớp", "Match")
t("Material", "Materyèl", "Материал", "자재", "Vật liệu", "Materyales")
t("Material Cost", "Koût Materyèl", "Стоимость материалов", "자재 비용", "Chi phí vật liệu", "Gastos sa Materyales")
t("Material Costs", "Koût Materyèl", "Затраты на материалы", "자재 비용", "Chi phí vật liệu", "Mga Gastos sa Materyales")
t("Material Delivery", "Livrezon Materyèl", "Доставка материалов", "자재 배송", "Giao vật liệu", "Delivery ng Materyales")
t("Material Name", "Non Materyèl", "Название материала", "자재명", "Tên vật liệu", "Pangalan ng Materyales")
t("Material Order", "Kòmann Materyèl", "Заказ материалов", "자재 주문", "Đơn hàng vật liệu", "Order ng Materyales")
t("Material Pricing", "Pri Materyèl", "Цены на материалы", "자재 가격", "Giá vật liệu", "Presyo ng Materyales")
t("Material Tier", "Nivo Materyèl", "Класс материала", "자재 등급", "Hạng vật liệu", "Tier ng Materyales")
t("Material Tier Options", "Opsyon Nivo Materyèl", "Варианты класса материала", "자재 등급 옵션", "Tùy chọn hạng vật liệu", "Mga Option ng Material Tier")
t("Material Type", "Tip Materyèl", "Тип материала", "자재 유형", "Loại vật liệu", "Uri ng Materyales")
t("Materials", "Materyèl", "Материалы", "자재", "Vật liệu", "Mga Materyales")
t("Max Daily Leads", "Pwopriyetè Maksimòm Pa Jou", "Макс. лидов в день", "일일 최대 리드", "Khách hàng tiềm năng tối đa mỗi ngày", "Max Daily Leads")
t("Maximum", "Maksimòm", "Максимум", "최대", "Tối đa", "Pinakamataas")
t("Measurement Data", "Done Mezirman", "Данные измерений", "측정 데이터", "Dữ liệu đo lường", "Data ng Pagsukat")
t("Measurements", "Mezirman", "Измерения", "측정", "Đo lường", "Mga Pagsukat")
t("Mechanical / HVAC", "Mekanik / HVAC", "Механика / HVAC", "기계 / HVAC", "Cơ khí / HVAC", "Mechanical / HVAC")
t("Medium", "Mwayen", "Средний", "중간", "Trung bình", "Katamtaman")
t("Meeting Room", "Sal Reyinyon", "Переговорная", "회의실", "Phòng họp", "Meeting Room")
t("Meetings", "Reyinyon", "Встречи", "회의", "Cuộc họp", "Mga Meeting")
t("Member", "Manm", "Участник", "멤버", "Thành viên", "Miyembro")
t("Memo", "Nòt", "Памятка", "메모", "Ghi chú", "Memo")
t("Menu", "Meni", "Меню", "메뉴", "Menu", "Menu")
t("Merge", "Fizyone", "Объединить", "병합", "Hợp nhất", "I-merge")
t("Message", "Mesaj", "Сообщение", "메시지", "Tin nhắn", "Mensahe")
t("Messages", "Mesaj", "Сообщения", "메시지", "Tin nhắn", "Mga Mensahe")
t("Meter Type", "Tip Kontè", "Тип счётчика", "계량기 유형", "Loại đồng hồ đo", "Uri ng Meter")
t("Method", "Metòd", "Метод", "방법", "Phương pháp", "Paraan")
t("Metric", "Metrik", "Метрика", "지표", "Chỉ số", "Sukatan")
t("Mike Johnson", "Mike Johnson", "Mike Johnson", "Mike Johnson", "Mike Johnson", "Mike Johnson")
t("Mike Thompson", "Mike Thompson", "Mike Thompson", "Mike Thompson", "Mike Thompson", "Mike Thompson")
t("Mileage", "Kilomètraj", "Пробег", "주행거리", "Số km", "Mileage")
t("Milestone", "Etap", "Этап", "마일스톤", "Cột mốc", "Milestone")
t("Milestones", "Etap", "Этапы", "마일스톤", "Các cột mốc", "Mga Milestone")
t("Min", "Min", "Мин.", "최소", "Tối thiểu", "Min")
t("Minimum", "Minimòm", "Минимум", "최소", "Tối thiểu", "Pinakamababa")
t("Minimum Job Value", "Valè Minimòm Travay", "Минимальная стоимость заказа", "최소 작업 금액", "Giá trị công việc tối thiểu", "Minimum na Halaga ng Trabaho")
t("Minutes", "Minit", "Протокол", "회의록", "Biên bản", "Mga Minuto")
t("Missed Calls", "Apèl Manke", "Пропущенные звонки", "부재중 전화", "Cuộc gọi nhỡ", "Mga Missed Call")
t("Missing", "Manke", "Отсутствует", "누락", "Thiếu", "Nawawala")
t("Mitigation", "Atenuasyon", "Устранение", "완화", "Giảm thiểu", "Mitigation")
t("Mobile app notifications", "Notifikasyon aplikasyon mobil", "Push-уведомления", "모바일 앱 알림", "Thông báo ứng dụng di động", "Mga notification sa mobile app")
t("Mobilization", "Mobilizasyon", "Мобилизация", "동원", "Huy động", "Mobilization")
t("Mode", "Mòd", "Режим", "모드", "Chế độ", "Mode")
t("Model", "Modèl", "Модель", "모델", "Mẫu", "Modelo")
t("Modifier", "Modifye", "Модификатор", "수정자", "Bộ điều chỉnh", "Modifier")
t("Moisture", "Imidite", "Влажность", "수분", "Độ ẩm", "Moisture")
t("Moisture & Drying Monitor", "Monitè Imidite ak Sechaj", "Монитор влажности и сушки", "수분 및 건조 모니터", "Giám sát độ ẩm & sấy khô", "Moisture & Drying Monitor")
t("Moisture Level", "Nivo Imidite", "Уровень влажности", "수분 수준", "Mức độ ẩm", "Antas ng Moisture")
t("Moisture Location Grid", "Griy Kote Imidite", "Сетка расположения влажности", "수분 위치 그리드", "Lưới vị trí độ ẩm", "Moisture Location Grid")
t("Moisture Readings", "Lekti Imidite", "Показания влажности", "수분 판독값", "Số đọc độ ẩm", "Mga Reading ng Moisture")
t("Mold Remediation", "Remèd Mwazi", "Удаление плесени", "곰팡이 제거", "Xử lý nấm mốc", "Mold Remediation")
t("Month-to-Month", "Mwa-a-Mwa", "Помесячно", "월 단위", "Theo tháng", "Buwan-buwan")
t("Monthly", "Chak Mwa", "Ежемесячно", "월간", "Hàng tháng", "Buwanan")
t("Monthly Breakdown", "Dekoupaj Chak Mwa", "Ежемесячная разбивка", "월별 분석", "Phân tích hàng tháng", "Buwanang Breakdown")
t("Monthly Expenses", "Depans Chak Mwa", "Ежемесячные расходы", "월간 지출", "Chi phí hàng tháng", "Buwanang Gastos")
t("Monthly Forecast", "Previzyon Chak Mwa", "Ежемесячный прогноз", "월간 예측", "Dự báo hàng tháng", "Buwanang Forecast")
t("Monthly Income", "Revni Chak Mwa", "Ежемесячный доход", "월간 수입", "Thu nhập hàng tháng", "Buwanang Kita")
t("Monthly Margin Trend", "Tandans Maj Chak Mwa", "Ежемесячная динамика маржи", "월간 마진 추이", "Xu hướng biên lợi nhuận hàng tháng", "Buwanang Margin Trend")
t("Monthly Mortgage", "Ipotèk Chak Mwa", "Ежемесячная ипотека", "월 모기지", "Thế chấp hàng tháng", "Buwanang Mortgage")
t("Monthly Payment", "Peman Chak Mwa", "Ежемесячный платёж", "월 납입액", "Thanh toán hàng tháng", "Buwanang Bayad")
t("Monthly Periods", "Peryòd Chak Mwa", "Месячные периоды", "월간 기간", "Kỳ hàng tháng", "Mga Buwanang Period")
t("Monthly Recurring", "Regilye Chak Mwa", "Ежемесячные повторяющиеся", "월간 반복", "Định kỳ hàng tháng", "Buwanang Recurring")
t("Monthly Rent", "Lwaye Chak Mwa", "Ежемесячная аренда", "월 임대료", "Tiền thuê hàng tháng", "Buwanang Upa")
t("Monthly Trend", "Tandans Chak Mwa", "Ежемесячная динамика", "월간 추이", "Xu hướng hàng tháng", "Buwanang Trend")
t("Monthly revenue for the past year", "Revni chak mwa pou ane pase a", "Ежемесячный доход за прошлый год", "지난 1년간 월별 매출", "Doanh thu hàng tháng trong năm qua", "Buwanang kita sa nakaraang taon")
t("More", "Plis", "Ещё", "더보기", "Thêm", "Higit Pa")
t("More translations coming soon. Language preference saved to your profile.", "Plis tradiksyon ap vini byento. Preferans lang sove nan pwofil ou.", "Дополнительные переводы скоро будут. Языковые настройки сохранены.", "더 많은 번역이 곧 제공됩니다. 언어 설정이 프로필에 저장되었습니다.", "Sẽ có thêm bản dịch sớm. Tùy chọn ngôn ngữ đã lưu vào hồ sơ.", "May mga darating pang translation. Na-save na ang language preference sa profile mo.")
t("Mortgage Payment", "Peman Ipotèk", "Ипотечный платёж", "모기지 납입", "Thanh toán thế chấp", "Bayad sa Mortgage")
t("Mortgage interest", "Enterè ipotèk", "Проценты по ипотеке", "모기지 이자", "Lãi thế chấp", "Interes sa mortgage")
t("Most Applied Pricing Factors", "Faktè Pri Pi Aplike", "Наиболее применяемые ценовые факторы", "가장 많이 적용된 가격 요인", "Các yếu tố giá được áp dụng nhiều nhất", "Mga Pinaka-applied na Pricing Factor")
t("Move to Trash", "Mete nan Poubèl", "Переместить в корзину", "휴지통으로 이동", "Chuyển vào thùng rác", "Ilipat sa Trash")
t("Move-In", "Demenaje Antre", "Въезд", "입주", "Nhận phòng", "Move-In")
t("Move-In Date", "Dat Demenaje Antre", "Дата въезда", "입주일", "Ngày nhận phòng", "Petsa ng Move-In")
t("Move-Out", "Demenaje Soti", "Выезд", "퇴거", "Trả phòng", "Move-Out")
t("Move-Out Date", "Dat Demenaje Soti", "Дата выезда", "퇴거일", "Ngày trả phòng", "Petsa ng Move-Out")
t("Multi-branch P&L and performance comparison", "P&L milti-branch ak konparezon pèfòmans", "P&L и сравнение по филиалам", "다지점 P&L 및 성과 비교", "P&L đa chi nhánh và so sánh hiệu suất", "Multi-branch P&L at performance comparison")
t("Multiple warranty company relationships", "Relasyon miltipl konpayi garanti", "Связи с несколькими гарантийными компаниями", "복수 보증 회사 관계", "Quan hệ với nhiều công ty bảo hành", "Maramihang warranty company relationship")
t("My Active Bids", "Òf Aktif Mwen", "Мои активные заявки", "내 활성 입찰", "Đấu thầu đang hoạt động của tôi", "Mga Aktibong Bid Ko")
t("My Bids", "Òf Mwen", "Мои заявки", "내 입찰", "Đấu thầu của tôi", "Mga Bid Ko")
t("My Listings", "Lis Mwen", "Мои объявления", "내 목록", "Danh sách của tôi", "Mga Listing Ko")
t("My Rating", "Evalyasyon Mwen", "Мой рейтинг", "내 평점", "Đánh giá của tôi", "Rating Ko")
t("My Templates", "Modèl Mwen", "Мои шаблоны", "내 템플릿", "Mẫu của tôi", "Mga Template Ko")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
