#!/usr/bin/env python3
"""5-language batch 22: T values (second half: Total Customers through to) + lowercase"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("Total Customers", "Total Kliyan", "Всего клиентов", "총 고객", "Tổng khách hàng", "Kabuuang Customers")
t("Total Debits", "Total Debi", "Всего дебетов", "총 차변", "Tổng nợ", "Kabuuang Debits")
t("Total Documents", "Total Dokiman", "Всего документов", "총 문서", "Tổng tài liệu", "Kabuuang Documents")
t("Total Due", "Total Dwe", "Итого к оплате", "총 미납", "Tổng phải trả", "Kabuuang Due")
t("Total Employees", "Total Anplwaye", "Всего сотрудников", "총 직원", "Tổng nhân viên", "Kabuuang Empleyado")
t("Total Entries", "Total Antre", "Всего записей", "총 항목", "Tổng mục nhập", "Kabuuang Entries")
t("Total Equipment", "Total Ekipman", "Всего оборудования", "총 장비", "Tổng thiết bị", "Kabuuang Equipment")
t("Total Expenses", "Total Depans", "Всего расходов", "총 비용", "Tổng chi phí", "Kabuuang Gastos")
t("Total Generated", "Total Jenere", "Всего сгенерировано", "총 생성", "Tổng đã tạo", "Kabuuang Na-generate")
t("Total Gross", "Total Brit", "Всего валовая", "총 매출총액", "Tổng gộp", "Kabuuang Gross")
t("Total Hours", "Total Èdtan", "Всего часов", "총 시간", "Tổng giờ", "Kabuuang Oras")
t("Total Hours This Week", "Total Èdtan Semèn Sa a", "Всего часов на этой неделе", "이번 주 총 시간", "Tổng giờ tuần này", "Kabuuang Oras Ngayong Linggo")
t("Total Inspections", "Total Enspeksyon", "Всего инспекций", "총 검사", "Tổng kiểm tra", "Kabuuang Inspections")
t("Total Invoiced", "Total Faktire", "Всего выставлено счетов", "총 청구됨", "Tổng đã lập hóa đơn", "Kabuuang Invoiced")
t("Total Items", "Total Atik", "Всего позиций", "총 항목", "Tổng mục", "Kabuuang Items")
t("Total Jobs", "Total Travay", "Всего заказов", "총 작업", "Tổng công việc", "Kabuuang Trabaho")
t("Total Labor", "Total Travay", "Всего труд", "총 인건비", "Tổng nhân công", "Kabuuang Labor")
t("Total Leads", "Total Pwopriyetè", "Всего лидов", "총 리드", "Tổng khách hàng tiềm năng", "Kabuuang Leads")
t("Total Leases", "Total Kontra Lwaye", "Всего договоров аренды", "총 임대", "Tổng hợp đồng thuê", "Kabuuang Leases")
t("Total Materials", "Total Materyèl", "Всего материалов", "총 자재", "Tổng vật liệu", "Kabuuang Materials")
t("Total Members", "Total Manm", "Всего участников", "총 멤버", "Tổng thành viên", "Kabuuang Members")
t("Total Monthly Expenses", "Total Depans Mansyèl", "Всего ежемесячных расходов", "총 월 비용", "Tổng chi phí hàng tháng", "Kabuuang Buwanang Gastos")
t("Total Monthly Rent", "Total Lwaye Mansyèl", "Всего ежемесячной аренды", "총 월 임대료", "Tổng tiền thuê hàng tháng", "Kabuuang Buwanang Upa")
t("Total Net", "Total Nèt", "Всего нетто", "총 순액", "Tổng ròng", "Kabuuang Net")
t("Total Outstanding", "Total Anreta", "Всего неоплаченных", "총 미결제", "Tổng chưa thanh toán", "Kabuuang Outstanding")
t("Total POs", "Total PO", "Всего закупок", "총 구매 주문", "Tổng đơn đặt hàng", "Kabuuang POs")
t("Total Paid", "Total Peye", "Всего оплачено", "총 지급", "Tổng đã thanh toán", "Kabuuang Nabayaran")
t("Total Parcels", "Total Pasel", "Всего участков", "총 필지", "Tổng lô đất", "Kabuuang Parcels")
t("Total Payments", "Total Peman", "Всего платежей", "총 결제", "Tổng thanh toán", "Kabuuang Bayad")
t("Total Payroll", "Total Pewòl", "Всего зарплата", "총 급여", "Tổng bảng lương", "Kabuuang Payroll")
t("Total Photos", "Total Foto", "Всего фото", "총 사진", "Tổng ảnh", "Kabuuang Litrato")
t("Total Profit", "Total Pwofi", "Всего прибыль", "총 이익", "Tổng lợi nhuận", "Kabuuang Kita")
t("Total Properties", "Total Pwopriyete", "Всего объектов", "총 부동산", "Tổng bất động sản", "Kabuuang Properties")
t("Total Qty", "Total Kantite", "Общее кол-во", "총 수량", "Tổng số lượng", "Kabuuang Qty")
t("Total Readings", "Total Lekti", "Всего показаний", "총 판독", "Tổng số đọc", "Kabuuang Readings")
t("Total Rental Income", "Total Revni Lwaye", "Всего арендного дохода", "총 임대 수입", "Tổng thu nhập cho thuê", "Kabuuang Rental Income")
t("Total Requests", "Total Demand", "Всего запросов", "총 요청", "Tổng yêu cầu", "Kabuuang Requests")
t("Total Retainage", "Total Retansyon", "Всего удержано", "총 보유금", "Tổng giữ lại", "Kabuuang Retainage")
t("Total Retained", "Total Retni", "Всего удержано", "총 보유", "Tổng giữ lại", "Kabuuang Retained")
t("Total Revenue", "Total Revni", "Общий доход", "총 매출", "Tổng doanh thu", "Kabuuang Revenue")
t("Total Reviews", "Total Revizyon", "Всего отзывов", "총 리뷰", "Tổng đánh giá", "Kabuuang Reviews")
t("Total Rooms", "Total Chanm", "Всего комнат", "총 방", "Tổng phòng", "Kabuuang Rooms")
t("Total Rows", "Total Liy", "Всего строк", "총 행", "Tổng hàng", "Kabuuang Rows")
t("Total Runs", "Total Kous", "Всего маршрутов", "총 경로", "Tổng lượt chạy", "Kabuuang Runs")
t("Total Scans", "Total Eskanè", "Всего сканирований", "총 스캔", "Tổng lần quét", "Kabuuang Scans")
t("Total Schedules", "Total Orè", "Всего расписаний", "총 일정", "Tổng lịch trình", "Kabuuang Schedules")
t("Total Services", "Total Sèvis", "Всего услуг", "총 서비스", "Tổng dịch vụ", "Kabuuang Services")
t("Total Spend", "Total Depans", "Всего расходов", "총 지출", "Tổng chi tiêu", "Kabuuang Ginastos")
t("Total Sq Ft", "Total Pi Kare", "Общая площадь (кв. фут.)", "총 평방피트", "Tổng diện tích (sq ft)", "Kabuuang Sq Ft")
t("Total Subs", "Total Sou-kontraktè", "Всего субподрядчиков", "총 하도급", "Tổng nhà thầu phụ", "Kabuuang Subs")
t("Total Suppliers", "Total Founisè", "Всего поставщиков", "총 공급업체", "Tổng nhà cung cấp", "Kabuuang Suppliers")
t("Total Surveys", "Total Sondaj", "Всего обследований", "총 조사", "Tổng khảo sát", "Kabuuang Surveys")
t("Total Tenants", "Total Lokatè", "Всего арендаторов", "총 임차인", "Tổng người thuê", "Kabuuang Nangungupahan")
t("Total Units", "Total Inite", "Всего юнитов", "총 유닛", "Tổng đơn vị", "Kabuuang Units")
t("Total Value", "Total Valè", "Общая стоимость", "총 금액", "Tổng giá trị", "Kabuuang Halaga")
t("Total Vehicles", "Total Machin", "Всего транспорта", "총 차량", "Tổng phương tiện", "Kabuuang Sasakyan")
t("Total Walls", "Total Mi", "Всего стен", "총 벽", "Tổng tường", "Kabuuang Walls")
t("Total potential value from suggestions", "Total valè potansyèl nan sijesyon", "Общая потенциальная стоимость предложений", "제안의 총 잠재 가치", "Tổng giá trị tiềm năng từ đề xuất", "Kabuuang potensyal na halaga mula sa mga suhestiyon")
t("Totals", "Total", "Итого", "합계", "Tổng cộng", "Mga Kabuuan")
t("Track HVAC, water heaters, appliances, and more", "Swiv HVAC, chofaj dlo, aparèy, ak plis ankò", "Отслеживайте HVAC, водонагреватели, технику и другое", "HVAC, 온수기, 가전제품 등을 추적하세요", "Theo dõi HVAC, máy nước nóng, thiết bị và nhiều hơn nữa", "I-track ang HVAC, water heaters, appliances, at iba pa")
t("Track and manage property maintenance requests", "Swiv ak jere demand antretyen pwopriyete", "Отслеживайте и управляйте запросами на обслуживание", "부동산 유지보수 요청을 추적 및 관리하세요", "Theo dõi và quản lý yêu cầu bảo trì bất động sản", "I-track at pamahalaan ang mga property maintenance request")
t("Track and manage your sales opportunities", "Swiv ak jere opòtinite lavant ou", "Отслеживайте и управляйте возможностями продаж", "영업 기회를 추적 및 관리하세요", "Theo dõi và quản lý cơ hội kinh doanh", "I-track at pamahalaan ang iyong mga sales opportunity")
t("Track and monitor moisture levels across restoration jobs", "Swiv ak siveye nivo imidite sou travay restorasyon", "Отслеживайте уровни влажности на объектах восстановления", "복원 작업의 수분 수준을 추적 및 모니터링하세요", "Theo dõi và giám sát mức độ ẩm trên các công việc phục hồi", "I-track at i-monitor ang moisture levels sa mga restoration job")
t("Track business growth metrics and insights", "Swiv endis kwasans biznis ak apèsi", "Отслеживайте метрики роста бизнеса и аналитику", "비즈니스 성장 지표 및 인사이트를 추적하세요", "Theo dõi chỉ số tăng trưởng kinh doanh và thông tin chi tiết", "I-track ang business growth metrics at insights")
t("Track continuing education hours toward license renewals", "Swiv èdtan edikasyon kontini pou renouvèlman lisans", "Отслеживайте часы повышения квалификации для продления лицензии", "면허 갱신을 위한 보수교육 시간을 추적하세요", "Theo dõi giờ học liên tục để gia hạn giấy phép", "I-track ang continuing education hours para sa license renewals")
t("Track dehumidifiers, air movers, and other restoration equipment deployed to job sites.", "Swiv dezimidifikatè, vantilatè, ak lòt ekipman restorasyon deplwaye sou sit travay.", "Отслеживайте осушители, вентиляторы и другое оборудование на объектах.", "현장에 배치된 제습기, 에어무버 및 기타 복원 장비를 추적하세요.", "Theo dõi máy hút ẩm, quạt công nghiệp và thiết bị phục hồi khác tại công trường.", "I-track ang mga dehumidifier, air mover, at iba pang restoration equipment na naka-deploy sa job sites.")
t("Track dispatched insurance restoration assignments", "Swiv asiyman restorasyon asirans distribye", "Отслеживайте направленные страховые заказы на восстановление", "배정된 보험 복원 작업을 추적하세요", "Theo dõi các phân công phục hồi bảo hiểm đã điều phối", "I-track ang mga dispatched insurance restoration assignment")
t("Track employee performance with periodic reviews and ratings.", "Swiv pèfòmans anplwaye ak evalyasyon ak nòt peryodik.", "Отслеживайте эффективность сотрудников с периодическими обзорами.", "정기 리뷰 및 등급으로 직원 성과를 추적하세요.", "Theo dõi hiệu suất nhân viên qua đánh giá và xếp hạng định kỳ.", "I-track ang employee performance sa pamamagitan ng periodic reviews at ratings.")
t("Track employee training, certifications, and compliance.", "Swiv fòmasyon anplwaye, sètifikasyon, ak konformite.", "Отслеживайте обучение сотрудников, сертификации и соответствие.", "직원 교육, 자격증 및 규정 준수를 추적하세요.", "Theo dõi đào tạo nhân viên, chứng chỉ và tuân thủ.", "I-track ang employee training, certifications, at compliance.")
t("Track labor and equipment warranties across all jobs", "Swiv garanti travay ak ekipman sou tout travay", "Отслеживайте гарантии на работу и оборудование по всем заказам", "모든 작업의 인건비 및 장비 보증을 추적하세요", "Theo dõi bảo hành nhân công và thiết bị trên tất cả công việc", "I-track ang labor at equipment warranties sa lahat ng trabaho")
t("Track licenses, certifications, and regulatory compliance", "Swiv lisans, sètifikasyon, ak konformite regilasyon", "Отслеживайте лицензии, сертификации и соответствие нормативам", "면허, 자격증 및 규정 준수를 추적하세요", "Theo dõi giấy phép, chứng chỉ và tuân thủ quy định", "I-track ang mga lisensya, certification, at regulatory compliance")
t("Track materials and supplies", "Swiv materyèl ak founitè", "Отслеживайте материалы и расходники", "자재 및 소모품을 추적하세요", "Theo dõi vật liệu và vật tư", "I-track ang mga materyales at supply")
t("Track vehicles, maintenance, and fuel costs", "Swiv machin, antretyen, ak koût gaz", "Отслеживайте транспорт, обслуживание и расходы на топливо", "차량, 유지보수 및 연료비를 추적하세요", "Theo dõi phương tiện, bảo trì và chi phí nhiên liệu", "I-track ang mga sasakyan, maintenance, at fuel costs")
t("Trade", "Metye", "Специальность", "공종", "Ngành nghề", "Trade")
t("Trade Breakdown", "Dekoupaj Metye", "Разбивка по специальностям", "공종별 분석", "Phân tích theo ngành nghề", "Trade Breakdown")
t("Trade Categories", "Kategori Metye", "Категории специальностей", "공종 카테고리", "Danh mục ngành nghề", "Mga Trade Category")
t("Trade Modules", "Modil Metye", "Модули специальностей", "공종 모듈", "Mô-đun ngành nghề", "Mga Trade Module")
t("Trade Specialties", "Espesyalite Metye", "Специализации", "공종 전문 분야", "Chuyên môn ngành nghề", "Mga Trade Specialty")
t("Trade Types", "Tip Metye", "Типы специальностей", "공종 유형", "Loại ngành nghề", "Mga Uri ng Trade")
t("Trade:", "Metye:", "Специальность:", "공종:", "Ngành nghề:", "Trade:")
t("Trades", "Metye", "Специальности", "공종", "Ngành nghề", "Mga Trade")
t("Trades & Specializations", "Metye & Espesyalizasyon", "Специальности и специализации", "공종 및 전문 분야", "Ngành nghề & Chuyên môn", "Mga Trade & Espesyalisasyon")
t("Training", "Fòmasyon", "Обучение", "교육", "Đào tạo", "Pagsasanay")
t("Training Records", "Dosye Fòmasyon", "Записи обучения", "교육 기록", "Hồ sơ đào tạo", "Mga Training Record")
t("Transactions", "Tranzaksyon", "Транзакции", "거래", "Giao dịch", "Mga Transaksyon")
t("Transfer", "Transfè", "Перевод", "이체", "Chuyển khoản", "Transfer")
t("Transmittal", "Transmisyon", "Сопроводительное письмо", "송부장", "Phiếu chuyển giao", "Transmittal")
t("Transparent pricing with no hidden charges", "Pri transparan san frè kache", "Прозрачное ценообразование без скрытых платежей", "숨겨진 비용 없는 투명한 가격", "Giá minh bạch không có phí ẩn", "Transparent na presyo na walang hidden charges")
t("Treatments", "Tretman", "Обработки", "처리", "Xử lý", "Mga Treatment")
t("Trend", "Tandans", "Тренд", "트렌드", "Xu hướng", "Trend")
t("Trial Balance", "Balans Esè", "Пробный баланс", "시산표", "Bảng cân đối thử", "Trial Balance")
t("Trigger", "Deklanchè", "Триггер", "트리거", "Kích hoạt", "Trigger")
t("Trigger Event", "Evènman Deklanchè", "Событие-триггер", "트리거 이벤트", "Sự kiện kích hoạt", "Trigger Event")
t("Try adjusting your filters", "Eseye ajiste filt ou yo", "Попробуйте изменить фильтры", "필터를 조정해 보세요", "Thử điều chỉnh bộ lọc của bạn", "Subukang i-adjust ang iyong mga filter")
t("Two-Factor Authentication", "Otantifikasyon De-Faktè", "Двухфакторная аутентификация", "2단계 인증", "Xác thực hai yếu tố", "Two-Factor Authentication")
t("Two-way sync between ZAFTO jobs and Google Calendar", "Senkwonizasyon de-sans ant travay ZAFTO ak Google Calendar", "Двусторонняя синхронизация между заказами ZAFTO и Google Календарём", "ZAFTO 작업과 Google 캘린더 간 양방향 동기화", "Đồng bộ hai chiều giữa công việc ZAFTO và Google Calendar", "Two-way sync sa pagitan ng ZAFTO jobs at Google Calendar")
t("Type a message...", "Tape yon mesaj...", "Введите сообщение...", "메시지를 입력하세요...", "Nhập tin nhắn...", "Mag-type ng mensahe...")
t("Type:", "Tip:", "Тип:", "유형:", "Loại:", "Uri:")
# lowercase
t("to", "a", "до", "까지", "đến", "sa")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
