#!/usr/bin/env python3
"""5-language batch 21: T values (first half: TOTP through Total Credits)"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("TOTP enabled", "TOTP aktive", "TOTP включён", "TOTP 활성화됨", "TOTP đã bật", "TOTP enabled")
t("TPA Assignments", "Asiyman TPA", "Назначения TPA", "TPA 배정", "Phân công TPA", "Mga TPA Assignment")
t("TPA Dashboard", "Tablo TPA", "Панель TPA", "TPA 대시보드", "Bảng điều khiển TPA", "TPA Dashboard")
t("TPA Program", "Pwogram TPA", "Программа TPA", "TPA 프로그램", "Chương trình TPA", "TPA Program")
t("TPA Programs", "Pwogram TPA", "Программы TPA", "TPA 프로그램", "Chương trình TPA", "Mga TPA Program")
t("TPA Scorecards", "Kat Pwen TPA", "Оценочные карты TPA", "TPA 성과표", "Bảng điểm TPA", "Mga TPA Scorecard")
t("TPA portal access and program contacts", "Aksè pòtay TPA ak kontak pwogram", "Доступ к порталу TPA и контакты программы", "TPA 포털 접근 및 프로그램 연락처", "Truy cập cổng TPA và liên hệ chương trình", "TPA portal access at program contacts")
t("TPA-compliant documentation checklist and tracking", "Lis tchèk dokimantasyon konfòm TPA ak swivi", "Чек-лист документации TPA и отслеживание", "TPA 준수 문서 체크리스트 및 추적", "Danh sách kiểm tra tài liệu tuân thủ TPA và theo dõi", "TPA-compliant documentation checklist at tracking")
t("Tab", "Tab", "Вкладка", "탭", "Tab", "Tab")
t("Table", "Tablo", "Таблица", "테이블", "Bảng", "Talahanayan")
t("Tag", "Tag", "Тег", "태그", "Thẻ", "Tag")
t("Tagline", "Slogann", "Слоган", "태그라인", "Khẩu hiệu", "Tagline")
t("Tags", "Tag", "Теги", "태그", "Thẻ", "Mga Tag")
t("Target", "Objektif", "Цель", "목표", "Mục tiêu", "Target")
t("Target Ready Date", "Dat Prè Objektif", "Целевая дата готовности", "목표 준비 날짜", "Ngày sẵn sàng mục tiêu", "Target Ready Date")
t("Task", "Travay", "Задача", "작업", "Nhiệm vụ", "Gawain")
t("Task Checklist", "Lis Tchèk Travay", "Чек-лист задач", "작업 체크리스트", "Danh sách kiểm tra nhiệm vụ", "Task Checklist")
t("Task Name", "Non Travay", "Название задачи", "작업 이름", "Tên nhiệm vụ", "Pangalan ng Gawain")
t("Task Snapshot", "Apèsi Travay", "Снимок задач", "작업 스냅샷", "Ảnh chụp nhiệm vụ", "Task Snapshot")
t("Tasks", "Travay", "Задачи", "작업", "Nhiệm vụ", "Mga Gawain")
t("Tax & 1099 Compliance", "Taks & Konformite 1099", "Налоги и соответствие 1099", "세금 및 1099 준수", "Thuế & Tuân thủ 1099", "Tax & 1099 Compliance")
t("Tax Amount", "Montan Taks", "Сумма налога", "세금 금액", "Số tiền thuế", "Halaga ng Tax")
t("Tax Category", "Kategori Taks", "Налоговая категория", "세금 카테고리", "Danh mục thuế", "Kategorya ng Tax")
t("Tax ID", "Nimewo Taks", "ИНН", "세금 ID", "Mã số thuế", "Tax ID")
t("Tax Mappings", "Mapaj Taks", "Налоговые привязки", "세금 매핑", "Ánh xạ thuế", "Mga Tax Mapping")
t("Tax Rate", "To Taks", "Налоговая ставка", "세율", "Thuế suất", "Tax Rate")
t("Tax Rates", "To Taks", "Налоговые ставки", "세율", "Thuế suất", "Mga Tax Rate")
t("Tax Settings", "Paramèt Taks", "Настройки налогов", "세금 설정", "Cài đặt thuế", "Mga Tax Setting")
t("Tax Year", "Ane Fiskal", "Налоговый год", "세금 연도", "Năm thuế", "Tax Year")
t("Taxes", "Taks", "Налоги", "세금", "Thuế", "Mga Buwis")
t("Team Chat", "Chat Ekip", "Командный чат", "팀 채팅", "Nhóm chat", "Team Chat")
t("Team Live", "Ekip An Dirèk", "Команда онлайн", "팀 실시간", "Nhóm trực tuyến", "Team Live")
t("Team Member", "Manm Ekip", "Сотрудник", "팀원", "Thành viên nhóm", "Team Member")
t("Team Members", "Manm Ekip", "Сотрудники", "팀원", "Thành viên nhóm", "Mga Team Member")
t("Team Performance", "Pèfòmans Ekip", "Производительность команды", "팀 성과", "Hiệu suất nhóm", "Performance ng Team")
t("Team Settings", "Paramèt Ekip", "Настройки команды", "팀 설정", "Cài đặt nhóm", "Mga Team Setting")
t("Team members can clock in from the Time Clock page", "Manm ekip ka antre nan paj Orè Travay", "Сотрудники могут отмечаться на странице табеля", "팀원은 타임 클록 페이지에서 출근 기록을 할 수 있습니다", "Thành viên nhóm có thể chấm công từ trang Chấm công", "Ang mga team member ay maaaring mag-clock in sa Time Clock page")
t("Tech Locations", "Kote Teknisyen", "Расположение техников", "기술자 위치", "Vị trí kỹ thuật viên", "Mga Lokasyon ng Tech")
t("Technician", "Teknisyen", "Техник", "기술자", "Kỹ thuật viên", "Technician")
t("Technicians", "Teknisyen", "Техники", "기술자", "Kỹ thuật viên", "Mga Technician")
t("Temperature", "Tanperati", "Температура", "온도", "Nhiệt độ", "Temperatura")
t("Template", "Modèl", "Шаблон", "템플릿", "Mẫu", "Template")
t("Template Details", "Detay Modèl", "Детали шаблона", "템플릿 상세", "Chi tiết mẫu", "Detalye ng Template")
t("Template Library", "Bibliyotèk Modèl", "Библиотека шаблонов", "템플릿 라이브러리", "Thư viện mẫu", "Template Library")
t("Template Variables", "Varyab Modèl", "Переменные шаблона", "템플릿 변수", "Biến mẫu", "Mga Template Variable")
t("Template-based inspections with pass/fail/conditional items", "Enspeksyon baze sou modèl ak eleman pase/echwe/kondisyonèl", "Инспекции по шаблону с пунктами пройдено/не пройдено/условно", "합격/불합격/조건부 항목이 있는 템플릿 기반 검사", "Kiểm tra dựa trên mẫu với các mục đạt/không đạt/có điều kiện", "Template-based inspections na may pass/fail/conditional items")
t("Templates", "Modèl", "Шаблоны", "템플릿", "Mẫu", "Mga Template")
t("Temporary", "Tanporè", "Временный", "임시", "Tạm thời", "Pansamantala")
t("Tenant", "Lokatè", "Арендатор", "임차인", "Người thuê", "Nangungupahan")
t("Tenant Info", "Enfòmasyon Lokatè", "Информация арендатора", "임차인 정보", "Thông tin người thuê", "Impormasyon ng Nangungupahan")
t("Tenant Since", "Lokatè Depi", "Арендатор с", "임차 시작일", "Thuê từ", "Nangungupahan Mula")
t("Tenant not found", "Lokatè pa jwenn", "Арендатор не найден", "임차인을 찾을 수 없음", "Không tìm thấy người thuê", "Hindi nahanap ang nangungupahan")
t("Tenants", "Lokatè", "Арендаторы", "임차인", "Người thuê", "Mga Nangungupahan")
t("Tentative", "Tantatif", "Предварительно", "잠정", "Dự kiến", "Tentative")
t("Termination Date", "Dat Revokasyon", "Дата увольнения", "퇴직 날짜", "Ngày chấm dứt", "Petsa ng Pagtitiwalag")
t("Termination Reason", "Rezon Revokasyon", "Причина увольнения", "퇴직 사유", "Lý do chấm dứt", "Dahilan ng Pagtitiwalag")
t("Terms", "Tèm", "Условия", "조건", "Điều khoản", "Mga Tuntunin")
t("Terms & Conditions", "Tèm & Kondisyon", "Условия и положения", "약관", "Điều khoản & Điều kiện", "Mga Tuntunin at Kundisyon")
t("Text message alerts", "Alèt mesaj tèks", "Текстовые оповещения", "문자 메시지 알림", "Cảnh báo tin nhắn", "Mga text message alert")
t("The bid you're looking for doesn't exist.", "Òf w ap chèche a pa egziste.", "Запрашиваемая заявка не существует.", "찾으시는 입찰이 존재하지 않습니다.", "Đấu thầu bạn tìm không tồn tại.", "Hindi umiiral ang bid na hinahanap mo.")
t("The customer you're looking for doesn't exist.", "Kliyan w ap chèche a pa egziste.", "Запрашиваемый клиент не существует.", "찾으시는 고객이 존재하지 않습니다.", "Khách hàng bạn tìm không tồn tại.", "Hindi umiiral ang customer na hinahanap mo.")
t("The invoice you're looking for doesn't exist.", "Fakti w ap chèche a pa egziste.", "Запрашиваемый счёт не существует.", "찾으시는 청구서가 존재하지 않습니다.", "Hóa đơn bạn tìm không tồn tại.", "Hindi umiiral ang invoice na hinahanap mo.")
t("The job you're looking for doesn't exist.", "Travay w ap chèche a pa egziste.", "Запрашиваемый заказ не существует.", "찾으시는 작업이 존재하지 않습니다.", "Công việc bạn tìm không tồn tại.", "Hindi umiiral ang trabaho na hinahanap mo.")
t("The lease you are looking for does not exist.", "Kontra lwaye w ap chèche a pa egziste.", "Запрашиваемый договор аренды не существует.", "찾으시는 임대 계약이 존재하지 않습니다.", "Hợp đồng thuê bạn tìm không tồn tại.", "Hindi umiiral ang lease na hinahanap mo.")
t("The property you are looking for does not exist.", "Pwopriyete w ap chèche a pa egziste.", "Запрашиваемый объект не существует.", "찾으시는 부동산이 존재하지 않습니다.", "Bất động sản bạn tìm không tồn tại.", "Hindi umiiral ang property na hinahanap mo.")
t("The tenant you are looking for does not exist.", "Lokatè w ap chèche a pa egziste.", "Запрашиваемый арендатор не существует.", "찾으시는 임차인이 존재하지 않습니다.", "Người thuê bạn tìm không tồn tại.", "Hindi umiiral ang nangungupahan na hinahanap mo.")
t("The unit you are looking for does not exist.", "Inite w ap chèche a pa egziste.", "Запрашиваемый юнит не существует.", "찾으시는 유닛이 존재하지 않습니다.", "Đơn vị bạn tìm không tồn tại.", "Hindi umiiral ang unit na hinahanap mo.")
t("Theme", "Tèm", "Тема оформления", "테마", "Chủ đề", "Theme")
t("Then do this...", "Apre sa fè sa...", "Затем сделать это...", "그런 다음 이 작업 수행...", "Sau đó làm điều này...", "Pagkatapos gawin ito...")
t("This action cannot be undone.", "Aksyon sa a pa ka defèt.", "Это действие нельзя отменить.", "이 작업은 취소할 수 없습니다.", "Hành động này không thể hoàn tác.", "Hindi na maaaring i-undo ang aksyon na ito.")
t("This may take a few seconds", "Sa ka pran kèk segond", "Это может занять несколько секунд", "몇 초 정도 걸릴 수 있습니다", "Quá trình này có thể mất vài giây", "Maaaring tumagal ng ilang segundo ito")
t("This template requires a signature after generation.", "Modèl sa a mande yon siyati apre kreyasyon.", "Этот шаблон требует подписи после создания.", "이 템플릿은 생성 후 서명이 필요합니다.", "Mẫu này yêu cầu chữ ký sau khi tạo.", "Ang template na ito ay nangangailangan ng lagda pagkatapos i-generate.")
t("This unit is currently not occupied", "Inite sa a pa okipe kounye a", "Этот юнит сейчас не заселён", "이 유닛은 현재 비어 있습니다", "Đơn vị này hiện không có người ở", "Ang unit na ito ay kasalukuyang walang nakatira")
t("Thompson Auto Shop", "Thompson Auto Shop", "Томпсон Авто Шоп", "Thompson Auto Shop", "Thompson Auto Shop", "Thompson Auto Shop")
t("Threshold $", "Sèy $", "Порог $", "임계값 $", "Ngưỡng $", "Threshold $")
t("Thumbtack", "Thumbtack", "Thumbtack", "Thumbtack", "Thumbtack", "Thumbtack")
t("Tier Comparison", "Konparezon Nivo", "Сравнение тарифов", "등급 비교", "So sánh hạng", "Tier Comparison")
t("Time Clock", "Orè Travay", "Табель", "타임 클록", "Chấm công", "Time Clock")
t("Time Entries", "Antre Tan", "Записи времени", "시간 항목", "Mục thời gian", "Mga Time Entry")
t("Time Zone", "Fizono", "Часовой пояс", "시간대", "Múi giờ", "Time Zone")
t("Time entries will appear here when employees clock in", "Antre tan ap parèt isit la lè anplwaye antre", "Записи времени появятся здесь при отметке сотрудников", "직원이 출근 기록을 하면 시간 항목이 여기에 표시됩니다", "Mục thời gian sẽ xuất hiện ở đây khi nhân viên chấm công", "Lalabas dito ang mga time entry kapag nag-clock in ang mga empleyado")
t("Time entries will appear here when team members clock in to this job.", "Antre tan ap parèt isit la lè manm ekip antre nan travay sa a.", "Записи времени появятся при отметке сотрудников на этом заказе.", "팀원이 이 작업에 출근 기록을 하면 시간 항목이 여기에 표시됩니다.", "Mục thời gian sẽ xuất hiện ở đây khi thành viên nhóm chấm công cho công việc này.", "Lalabas dito ang mga time entry kapag nag-clock in ang mga team member sa trabahong ito.")
t("Time-Off Balance", "Balans Konje", "Остаток отпуска", "휴가 잔여", "Số ngày nghỉ còn lại", "Time-Off Balance")
t("Timeline", "Kronoloji", "Хронология", "타임라인", "Dòng thời gian", "Timeline")
t("Timeline:", "Kronoloji:", "Хронология:", "타임라인:", "Dòng thời gian:", "Timeline:")
t("Timestamp", "Mak Tan", "Временная метка", "타임스탬프", "Dấu thời gian", "Timestamp")
t("Timezone", "Fizono", "Часовой пояс", "시간대", "Múi giờ", "Timezone")
t("Title", "Tit", "Название", "제목", "Tiêu đề", "Pamagat")
t("Tool Checkout", "Prete Zouti", "Выдача инструментов", "도구 대출", "Mượn dụng cụ", "Tool Checkout")
t("Toolbar", "Ba Zouti", "Панель инструментов", "도구 모음", "Thanh công cụ", "Toolbar")
t("Tools Issued", "Zouti Distribye", "Выданные инструменты", "발급된 도구", "Dụng cụ đã cấp", "Mga Na-issue na Tool")
t("Top Services", "Sèvis Prensipal", "Популярные услуги", "인기 서비스", "Dịch vụ hàng đầu", "Mga Top Service")
t("Tornado", "Tònad", "Торнадо", "토네이도", "Lốc xoáy", "Tornado")
t("Total Affected", "Total Afekte", "Всего затронуто", "총 영향", "Tổng bị ảnh hưởng", "Kabuuang Naapektuhan")
t("Total Applicants", "Total Aplikan", "Всего кандидатов", "총 지원자", "Tổng ứng viên", "Kabuuang Applicants")
t("Total Assets", "Total Aktif", "Всего активов", "총 자산", "Tổng tài sản", "Kabuuang Assets")
t("Total Balance", "Total Balans", "Общий баланс", "총 잔액", "Tổng số dư", "Kabuuang Balance")
t("Total Bids", "Total Òf", "Всего заявок", "총 입찰", "Tổng đấu thầu", "Kabuuang Bids")
t("Total Billable", "Total Faktirabl", "Всего оплачиваемых", "총 청구 가능", "Tổng có thể tính phí", "Kabuuang Billable")
t("Total Billed", "Total Faktire", "Всего выставлено", "총 청구됨", "Tổng đã lập hóa đơn", "Kabuuang Billed")
t("Total Budget vs Projected", "Total Bidjè vs Projte", "Бюджет vs Прогноз", "총 예산 vs 예상", "Tổng ngân sách vs Dự kiến", "Kabuuang Budget vs Projected")
t("Total COs", "Total CO", "Всего ордеров изменений", "총 변경 주문", "Tổng lệnh thay đổi", "Kabuuang COs")
t("Total Calls", "Total Apèl", "Всего звонков", "총 통화", "Tổng cuộc gọi", "Kabuuang Calls")
t("Total Checklist Items", "Total Eleman Lis Tchèk", "Всего пунктов чек-листа", "총 체크리스트 항목", "Tổng mục danh sách kiểm tra", "Kabuuang Checklist Items")
t("Total Claims", "Total Reklamasyon", "Всего заявок", "총 청구", "Tổng yêu cầu bồi thường", "Kabuuang Claims")
t("Total Collected", "Total Kolekte", "Всего собрано", "총 수금", "Tổng đã thu", "Kabuuang Nakolekta")
t("Total Completed to Date", "Total Konplè jiska Dat", "Всего выполнено на дату", "현재까지 총 완료", "Tổng hoàn thành đến ngày", "Kabuuang Kumpleto Hanggang Ngayon")
t("Total Cost", "Koût Total", "Общая стоимость", "총 비용", "Tổng chi phí", "Kabuuang Gastos")
t("Total Costs", "Koût Total", "Общие затраты", "총 비용", "Tổng chi phí", "Kabuuang Gastos")
t("Total Credits", "Total Kredi", "Всего кредитов", "총 대변", "Tổng tín dụng", "Kabuuang Credits")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
