#!/usr/bin/env python3
"""5-language batch 29: remaining E + F values"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

# E values
t("Early payment discount", "Rabè peman bonè", "Скидка за раннюю оплату", "조기 결제 할인", "Chiết khấu thanh toán sớm", "Diskwento sa maagang bayad")
t("Edit Customer", "Modifye Kliyan", "Редактировать клиента", "고객 수정", "Chỉnh sửa khách hàng", "I-edit ang Customer")
t("Electrical", "Elektrik", "Электрика", "전기", "Điện", "Electrical")
t("Email Address", "Adrès Imèl", "Адрес эл. почты", "이메일 주소", "Địa chỉ email", "Email Address")
t("Email Notifications", "Notifikasyon Imèl", "Уведомления по эл. почте", "이메일 알림", "Thông báo email", "Mga Email Notification")
t("Email Templates", "Modèl Imèl", "Шаблоны писем", "이메일 템플릿", "Mẫu email", "Mga Email Template")
t("Email marketing opt-in", "Enskri nan maketing imèl", "Подписка на email-маркетинг", "이메일 마케팅 수신 동의", "Đăng ký nhận email marketing", "Email marketing opt-in")
t("Emergency", "Ijans", "Экстренный", "긴급", "Khẩn cấp", "Emergency")
t("Emergency Authorization", "Otorizasyon Ijans", "Экстренное разрешение", "긴급 승인", "Ủy quyền khẩn cấp", "Emergency Authorization")
t("Emergency Contact", "Kontak Ijans", "Экстренный контакт", "비상 연락처", "Liên hệ khẩn cấp", "Emergency Contact")
t("Employee ID", "ID Anplwaye", "ID сотрудника", "직원 ID", "Mã nhân viên", "Employee ID")
t("Enable 2FA", "Aktive 2FA", "Включить 2FA", "2FA 활성화", "Bật 2FA", "I-enable ang 2FA")
t("Enable/disable notification channels here", "Aktive/dezaktive kanal notifikasyon isit la", "Включите/отключите каналы уведомлений здесь", "여기에서 알림 채널을 활성화/비활성화하세요", "Bật/tắt kênh thông báo tại đây", "I-enable/disable ang mga notification channel dito")
t("Enabled", "Aktive", "Включено", "활성화됨", "Đã bật", "Naka-enable")
t("Engine Capabilities", "Kapasite Motè", "Возможности движка", "엔진 기능", "Khả năng công cụ", "Mga Kakayahan ng Engine")
t("Enterprise Feature", "Fonksyon Antrepriz", "Корпоративная функция", "엔터프라이즈 기능", "Tính năng doanh nghiệp", "Enterprise Feature")
t("Equipment Change", "Chanjman Ekipman", "Изменение оборудования", "장비 변경", "Thay đổi thiết bị", "Pagbabago ng Equipment")
t("Equipment Memory", "Memwa Ekipman", "Память оборудования", "장비 기록", "Bộ nhớ thiết bị", "Equipment Memory")
t("Equipment Running", "Ekipman Ap Fonksyone", "Работающее оборудование", "가동 중인 장비", "Thiết bị đang chạy", "Tumatakbong Equipment")
t("Equipment Tracked", "Ekipman Swivi", "Отслеживаемое оборудование", "추적 중인 장비", "Thiết bị được theo dõi", "Sinusubaybayang Equipment")
t("Error Details", "Detay Erè", "Подробности ошибки", "오류 상세", "Chi tiết lỗi", "Detalye ng Error")
t("Error loading growth actions", "Erè nan chajman aksyon kwasans", "Ошибка загрузки действий роста", "성장 작업 로드 오류", "Lỗi tải hành động tăng trưởng", "Error sa pag-load ng growth actions")
t("Error loading insights", "Erè nan chajman apersi", "Ошибка загрузки аналитики", "인사이트 로드 오류", "Lỗi tải thông tin chi tiết", "Error sa pag-load ng insights")
t("Error loading inspections", "Erè nan chajman enspeksyon", "Ошибка загрузки инспекций", "점검 로드 오류", "Lỗi tải kiểm tra", "Error sa pag-load ng inspections")
t("Esc", "Esc", "Esc", "Esc", "Esc", "Esc")
t("Est", "Est", "Ориент.", "추정", "Ước tính", "Est")
t("Est. Income Tax", "Taks sou Revni Est.", "Ориент. подоходный налог", "추정 소득세", "Thuế thu nhập ước tính", "Est. Income Tax")
t("Est. Revenue", "Revni Est.", "Ориент. выручка", "추정 수익", "Doanh thu ước tính", "Est. Revenue")
t("Est. Revenue Opportunity", "Opòtinite Revni Est.", "Ориент. возможная выручка", "추정 수익 기회", "Cơ hội doanh thu ước tính", "Est. Revenue Opportunity")
t("Estimate #", "Estimasyon #", "Смета #", "견적 #", "Báo giá #", "Estimate #")
t("Estimate Details", "Detay Estimasyon", "Детали сметы", "견적 상세", "Chi tiết báo giá", "Detalye ng Estimate")
t("Estimate Summary", "Rezime Estimasyon", "Сводка сметы", "견적 요약", "Tóm tắt báo giá", "Buod ng Estimate")
t("Estimate Total", "Total Estimasyon", "Итого по смете", "견적 합계", "Tổng báo giá", "Kabuuang Estimate")
t("Estimated", "Estime", "Оценочный", "추정", "Ước tính", "Tinatantya")
t("Estimated Completion", "Konpletman Estime", "Ориент. завершение", "예상 완료", "Hoàn thành dự kiến", "Tinatayang Pagkumpleto")
t("Estimated Cost", "Kou Estime", "Ориент. стоимость", "추정 비용", "Chi phí ước tính", "Tinatayang Gastos")
t("Estimated Recipients", "Destinatè Estime", "Ориент. получатели", "예상 수신자", "Người nhận ước tính", "Tinatayang Tatanggap")
t("Estimates", "Estimasyon", "Сметы", "견적서", "Báo giá", "Mga Estimate")
t("Event", "Evènman", "Событие", "이벤트", "Sự kiện", "Event")
t("Evidence", "Prèv", "Доказательства", "증거", "Bằng chứng", "Ebidensya")
t("Exclusions", "Eksklizyon", "Исключения", "제외 항목", "Loại trừ", "Mga Exclusion")
t("Expand All", "Elaji Tout", "Развернуть всё", "모두 펼치기", "Mở rộng tất cả", "I-expand Lahat")
t("Expected Delivery Date", "Dat Livrezon Prevwa", "Ожидаемая дата доставки", "예상 배송일", "Ngày giao hàng dự kiến", "Inaasahang Petsa ng Delivery")
t("Expenses by Category", "Depans pa Kategori", "Расходы по категориям", "카테고리별 비용", "Chi phí theo danh mục", "Mga Gastos ayon sa Category")
t("Expiration", "Ekspirasyon", "Истечение", "만료", "Hết hạn", "Pag-expire")
t("Expiration Date", "Dat Ekspirasyon", "Дата истечения", "만료일", "Ngày hết hạn", "Petsa ng Pag-expire")
t("Expires", "Ekspire", "Истекает", "만료됨", "Hết hạn", "Mag-e-expire")
t("Export Ready", "Prè pou Ekspòte", "Готово к экспорту", "내보내기 준비 완료", "Sẵn sàng xuất", "Handa nang I-export")
t("Export Schedule", "Orè Ekspòtasyon", "Расписание экспорта", "내보내기 일정", "Lịch xuất", "Schedule ng Pag-export")
t("External", "Ekstèn", "Внешний", "외부", "Bên ngoài", "External")
t("External Number", "Nimewo Ekstèn", "Внешний номер", "외부 번호", "Số bên ngoài", "External Number")
t("Extracted Claim Info", "Enfòmasyon Reklamasyon Ekstrè", "Извлечённая информация", "추출된 청구 정보", "Thông tin yêu cầu đã trích xuất", "Na-extract na Claim Info")

# F values
t("Facebook", "Facebook", "Facebook", "Facebook", "Facebook", "Facebook")
t("Fail", "Echèk", "Неудача", "실패", "Thất bại", "Fail")
t("Failed / Needs Correction", "Echèk / Bezwen Koreksyon", "Не пройдено / Требуется исправление", "실패 / 수정 필요", "Thất bại / Cần sửa", "Nabigo / Kailangan ng Pagwawasto")
t("Failed Sensors", "Sansè Echwe", "Неисправные датчики", "실패한 센서", "Cảm biến lỗi", "Mga Nabigong Sensor")
t("Failed to load data", "Echèk nan chajman done", "Не удалось загрузить данные", "데이터 로드 실패", "Không tải được dữ liệu", "Hindi na-load ang data")
t("Failed to load documentation", "Echèk nan chajman dokimantasyon", "Не удалось загрузить документацию", "문서 로드 실패", "Không tải được tài liệu", "Hindi na-load ang documentation")
t("Failed to load jurisdictions", "Echèk nan chajman jiridiksyon", "Не удалось загрузить юрисдикции", "관할 구역 로드 실패", "Không tải được khu vực pháp lý", "Hindi na-load ang jurisdictions")
t("Failed to load permits", "Echèk nan chajman pèmi", "Не удалось загрузить разрешения", "허가 로드 실패", "Không tải được giấy phép", "Hindi na-load ang permits")
t("Fax", "Faks", "Факс", "팩스", "Fax", "Fax")
t("Fee", "Frè", "Сбор", "수수료", "Phí", "Bayad")
t("Field", "Chan", "Поле", "필드", "Trường", "Field")
t("Field Type", "Tip Chan", "Тип поля", "필드 유형", "Loại trường", "Uri ng Field")
t("File", "Fichye", "Файл", "파일", "Tệp", "File")
t("File Size", "Gwosè Fichye", "Размер файла", "파일 크기", "Kích thước tệp", "Laki ng File")
t("File Type", "Tip Fichye", "Тип файла", "파일 유형", "Loại tệp", "Uri ng File")
t("File Warranty Claim", "Depoze Reklamasyon Garanti", "Подать гарантийную претензию", "보증 청구 제출", "Nộp yêu cầu bảo hành", "Mag-file ng Warranty Claim")
t("Files", "Fichye", "Файлы", "파일", "Tệp", "Mga File")
t("Filing Deadline", "Dat Limit Depo", "Крайний срок подачи", "제출 마감일", "Hạn nộp", "Deadline ng Pag-file")
t("Filter by", "Filtre pa", "Фильтровать по", "필터", "Lọc theo", "I-filter ayon sa")
t("Finance", "Finans", "Финансы", "재무", "Tài chính", "Pananalapi")
t("Financial dashboard", "Tablo finans", "Финансовая панель", "재무 대시보드", "Bảng điều khiển tài chính", "Financial dashboard")
t("Finding revenue opportunities", "Ap chèche opòtinite revni", "Поиск возможностей дохода", "수익 기회 탐색 중", "Đang tìm cơ hội doanh thu", "Naghahanap ng revenue opportunities")
t("First Name", "Premye Non", "Имя", "이름", "Tên", "Pangalan")
t("Flag", "Drapo", "Отметка", "플래그", "Cờ", "Flag")
t("Flat Rate", "To Fiks", "Фиксированная ставка", "고정 요금", "Phí cố định", "Flat Rate")
t("Flood", "Inondasyon", "Наводнение", "홍수", "Lũ lụt", "Baha")
t("Floor", "Etaj", "Этаж", "층", "Tầng", "Palapag")
t("Floor Level", "Nivo Etaj", "Уровень этажа", "층 수", "Cấp tầng", "Antas ng Palapag")
t("Floor Plan", "Plan Etaj", "План этажа", "평면도", "Sơ đồ tầng", "Floor Plan")
t("Floor Plans", "Plan Etaj", "Планы этажей", "평면도", "Sơ đồ tầng", "Mga Floor Plan")
t("Folder", "Dosye", "Папка", "폴더", "Thư mục", "Folder")
t("Follow Up", "Swivi", "Контроль", "후속 조치", "Theo dõi", "Follow Up")
t("Footer", "Pye Paj", "Нижний колонтитул", "푸터", "Chân trang", "Footer")
t("Forecast", "Previzyon", "Прогноз", "예측", "Dự báo", "Forecast")
t("Form", "Fòm", "Форма", "양식", "Biểu mẫu", "Form")
t("Forms created by your company", "Fòm kreye pa konpayi ou", "Формы, созданные вашей компанией", "회사에서 만든 양식", "Biểu mẫu do công ty bạn tạo", "Mga form na ginawa ng iyong company")
t("Forward", "Voye", "Переслать", "전달", "Chuyển tiếp", "I-forward")
t("Foundation", "Fondasyon", "Фундамент", "기초", "Nền móng", "Pundasyon")
t("Free", "Gratis", "Бесплатно", "무료", "Miễn phí", "Libre")
t("From", "De", "От", "보낸 사람", "Từ", "Mula sa")
t("Full Home Rewire", "Rekablaj Konplè Kay", "Полная перепроводка дома", "전체 주택 배선 교체", "Đi lại dây toàn bộ nhà", "Full Home Rewire")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
