#!/usr/bin/env python3
"""5-language batch 11: 'No ...' empty state strings (part 1: No Logo through No invoices)"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("No Logo", "Pa gen Logo", "Нет логотипа", "로고 없음", "Không có logo", "Walang Logo")
t("No Moisture Readings", "Pa gen Lekti Imidite", "Нет показаний влажности", "수분 판독값 없음", "Không có số đọc độ ẩm", "Walang Moisture Reading")
t("No Notice", "Pa gen Avi", "Без уведомления", "통지 없음", "Không có thông báo", "Walang Abiso")
t("No Psychrometric Logs", "Pa gen Jounal Psikwometrik", "Нет психрометрических данных", "건습구 로그 없음", "Không có nhật ký tâm ẩm", "Walang Psychrometric Log")
t("No TPA Programs", "Pa gen Pwogram TPA", "Нет программ ТПА", "TPA 프로그램 없음", "Không có chương trình TPA", "Walang TPA Program")
t("No TPA programs found", "Pa gen pwogram TPA jwenn", "Программы ТПА не найдены", "TPA 프로그램을 찾을 수 없음", "Không tìm thấy chương trình TPA", "Walang nahanap na TPA program")
t("No WDI reports", "Pa gen rapò WDI", "Нет отчётов WDI", "WDI 보고서 없음", "Không có báo cáo WDI", "Walang WDI report")
t("No Water Damage Assessment", "Pa gen Evalyasyon Domaj Dlo", "Нет оценки ущерба от воды", "수해 평가 없음", "Không có đánh giá thiệt hại do nước", "Walang Water Damage Assessment")
t("No accounts found", "Pa gen kont jwenn", "Счета не найдены", "계정을 찾을 수 없음", "Không tìm thấy tài khoản", "Walang nahanap na account")
t("No actions match this filter", "Pa gen aksyon koresponn ak filtè sa a", "Нет действий по этому фильтру", "이 필터에 맞는 작업 없음", "Không có hành động khớp bộ lọc này", "Walang action na tumutugma sa filter na ito")
t("No active certifications found", "Pa gen sètifikasyon aktif jwenn", "Нет активных сертификаций", "활성 인증 없음", "Không tìm thấy chứng chỉ hoạt động", "Walang nahanap na aktibong sertipikasyon")
t("No active checkouts", "Pa gen tchèkawout aktif", "Нет активных выдач", "활성 대여 없음", "Không có lượt mượn đang hoạt động", "Walang aktibong checkout")
t("No active items", "Pa gen atik aktif", "Нет активных позиций", "활성 항목 없음", "Không có mục hoạt động", "Walang aktibong item")
t("No active job postings", "Pa gen piblikasyon travay aktif", "Нет активных вакансий", "활성 채용 공고 없음", "Không có tin tuyển dụng đang hoạt động", "Walang aktibong job posting")
t("No active job postings. Create one first.", "Pa gen piblikasyon travay aktif. Kreye youn anvan.", "Нет активных вакансий. Создайте первую.", "활성 채용 공고 없음. 먼저 하나를 생성하세요.", "Không có tin tuyển dụng hoạt động. Tạo tin đầu tiên.", "Walang aktibong job posting. Gumawa muna ng isa.")
t("No active lease", "Pa gen kontra aktif", "Нет активной аренды", "활성 임대 없음", "Không có hợp đồng thuê hoạt động", "Walang aktibong lease")
t("No active leases", "Pa gen kontra aktif", "Нет активных аренд", "활성 임대 없음", "Không có hợp đồng thuê hoạt động", "Walang aktibong lease")
t("No active lien records", "Pa gen dosye lyen aktif", "Нет активных залоговых записей", "활성 유치권 기록 없음", "Không có hồ sơ giữ tài sản hoạt động", "Walang aktibong lien record")
t("No active recalls", "Pa gen rapèl aktif", "Нет активных отзывов", "활성 리콜 없음", "Không có thu hồi đang hoạt động", "Walang aktibong recall")
t("No active templates found.", "Pa gen modèl aktif jwenn.", "Активные шаблоны не найдены.", "활성 템플릿을 찾을 수 없음.", "Không tìm thấy mẫu hoạt động.", "Walang nahanap na aktibong template.")
t("No active templates. Create one first.", "Pa gen modèl aktif. Kreye youn anvan.", "Нет активных шаблонов. Создайте первый.", "활성 템플릿 없음. 먼저 하나를 생성하세요.", "Không có mẫu hoạt động. Tạo mẫu đầu tiên.", "Walang aktibong template. Gumawa muna ng isa.")
t("No active tenant or lease for this unit", "Pa gen lokatè oswa kontra aktif pou inite sa a", "Нет активного арендатора или аренды для этого объекта", "이 유닛에 활성 세입자 또는 임대 없음", "Không có người thuê hoặc hợp đồng hoạt động cho đơn vị này", "Walang aktibong tenant o lease para sa unit na ito")
t("No activity recorded yet", "Pa gen aktivite anrejistre ankò", "Активность ещё не зарегистрирована", "아직 기록된 활동 없음", "Chưa ghi nhận hoạt động nào", "Wala pang nairecord na aktibidad")
t("No activity yet", "Pa gen aktivite ankò", "Ещё нет активности", "아직 활동 없음", "Chưa có hoạt động", "Wala pang aktibidad")
t("No adjuster info", "Pa gen enfò ajistè", "Нет данных оценщика", "정산인 정보 없음", "Không có thông tin giám định viên", "Walang adjuster info")
t("No agreements found", "Pa gen akò jwenn", "Соглашения не найдены", "계약을 찾을 수 없음", "Không tìm thấy thỏa thuận", "Walang nahanap na kasunduan")
t("No amenities listed", "Pa gen ekipman liste", "Нет перечисленных удобств", "등록된 편의시설 없음", "Không có tiện nghi được liệt kê", "Walang nakalista na amenity")
t("No appliance repair records", "Pa gen dosye reparasyon aparèy", "Нет записей о ремонте техники", "가전 수리 기록 없음", "Không có hồ sơ sửa chữa thiết bị", "Walang record ng appliance repair")
t("No applicants found", "Pa gen aplikan jwenn", "Кандидаты не найдены", "지원자를 찾을 수 없음", "Không tìm thấy ứng viên", "Walang nahanap na aplikante")
t("No assemblies found", "Pa gen asanblaj jwenn", "Сборки не найдены", "조립품을 찾을 수 없음", "Không tìm thấy bộ lắp ráp", "Walang nahanap na assembly")
t("No assets found", "Pa gen byen jwenn", "Активы не найдены", "자산을 찾을 수 없음", "Không tìm thấy tài sản", "Walang nahanap na asset")
t("No automations configured", "Pa gen otomatizasyon konfigire", "Нет настроенных автоматизаций", "설정된 자동화 없음", "Chưa cấu hình tự động hóa", "Walang na-configure na automation")
t("No autopsies yet. Complete jobs to generate analysis.", "Pa gen otopsi ankò. Konplete travay pou jenere analiz.", "Нет анализов. Завершите заказы для генерации.", "아직 분석 없음. 작업을 완료하여 분석을 생성하세요.", "Chưa có phân tích. Hoàn thành công việc để tạo phân tích.", "Wala pang autopsy. Kumpletuhin ang mga trabaho para mag-generate ng analysis.")
t("No bait stations", "Pa gen estasyon apèl", "Нет приманочных станций", "미끼통 없음", "Không có trạm mồi", "Walang bait station")
t("No bank accounts connected", "Pa gen kont bank konekte", "Нет подключённых банковских счетов", "연결된 은행 계좌 없음", "Chưa kết nối tài khoản ngân hàng", "Walang nakakonektang bank account")
t("No baselines yet", "Pa gen liy debaz ankò", "Нет базовых линий", "아직 기준선 없음", "Chưa có đường cơ sở", "Wala pang baseline")
t("No bids found", "Pa gen òf jwenn", "Заявки не найдены", "입찰을 찾을 수 없음", "Không tìm thấy đấu thầu", "Walang nahanap na bid")
t("No bids yet", "Pa gen òf ankò", "Заявок ещё нет", "아직 입찰 없음", "Chưa có đấu thầu", "Wala pang bid")
t("No bills due", "Pa gen bòdwo dwe", "Нет счетов к оплате", "납부할 청구서 없음", "Không có hóa đơn đến hạn", "Walang bills na due")
t("No booking types configured", "Pa gen tip rezèvasyon konfigire", "Нет настроенных типов бронирования", "설정된 예약 유형 없음", "Chưa cấu hình loại đặt lịch", "Walang na-configure na booking type")
t("No branch data available.", "Pa gen done branch disponib.", "Нет данных о филиалах.", "지점 데이터 없음.", "Không có dữ liệu chi nhánh.", "Walang available na branch data.")
t("No branches yet. Add your first location.", "Pa gen branch ankò. Ajoute premye kote ou.", "Нет филиалов. Добавьте первый.", "아직 지점 없음. 첫 번째 위치를 추가하세요.", "Chưa có chi nhánh. Thêm địa điểm đầu tiên.", "Wala pang branch. Magdagdag ng unang lokasyon.")
t("No calculations yet", "Pa gen kalkil ankò", "Нет расчётов", "아직 계산 없음", "Chưa có tính toán", "Wala pang kalkulasyon")
t("No calls yet", "Pa gen apèl ankò", "Нет звонков", "아직 통화 없음", "Chưa có cuộc gọi", "Wala pang tawag")
t("No campaigns found", "Pa gen kanpay jwenn", "Кампании не найдены", "캠페인을 찾을 수 없음", "Không tìm thấy chiến dịch", "Walang nahanap na kampanya")
t("No certifications found", "Pa gen sètifikasyon jwenn", "Сертификации не найдены", "인증을 찾을 수 없음", "Không tìm thấy chứng chỉ", "Walang nahanap na sertipikasyon")
t("No change orders found", "Pa gen òd chanjman jwenn", "Изменения заказов не найдены", "변경 주문을 찾을 수 없음", "Không tìm thấy lệnh thay đổi", "Walang nahanap na change order")
t("No checklist items for this room.", "Pa gen atik lis tchèk pou pyès sa a.", "Нет пунктов чек-листа для этой комнаты.", "이 방에 대한 체크리스트 항목 없음.", "Không có mục kiểm tra cho phòng này.", "Walang checklist item para sa room na ito.")
t("No checklist items recorded.", "Pa gen atik lis tchèk anrejistre.", "Нет записанных пунктов чек-листа.", "기록된 체크리스트 항목 없음.", "Không có mục kiểm tra được ghi nhận.", "Walang nairecord na checklist item.")
t("No checklist items. Add items to enforce completion standards.", "Pa gen atik lis tchèk. Ajoute atik pou aplike estanda konpletman.", "Нет пунктов чек-листа. Добавьте для контроля стандартов.", "체크리스트 항목 없음. 완료 기준 적용을 위해 항목을 추가하세요.", "Không có mục kiểm tra. Thêm mục để thực thi tiêu chuẩn hoàn thành.", "Walang checklist item. Magdagdag ng item para i-enforce ang completion standard.")
t("No checklist template found", "Pa gen modèl lis tchèk jwenn", "Шаблон чек-листа не найден", "체크리스트 템플릿을 찾을 수 없음", "Không tìm thấy mẫu kiểm tra", "Walang nahanap na checklist template")
t("No claims filed", "Pa gen reklamasyon depoze", "Нет поданных заявок", "접수된 청구 없음", "Chưa nộp yêu cầu bồi thường", "Walang na-file na claim")
t("No claims found", "Pa gen reklamasyon jwenn", "Заявки не найдены", "청구를 찾을 수 없음", "Không tìm thấy yêu cầu bồi thường", "Walang nahanap na claim")
t("No communications yet", "Pa gen kominikasyon ankò", "Нет сообщений", "아직 커뮤니케이션 없음", "Chưa có liên lạc", "Wala pang komunikasyon")
t("No compliance issues found", "Pa gen pwoblèm konformite jwenn", "Нарушений не найдено", "규정 준수 문제 없음", "Không tìm thấy vấn đề tuân thủ", "Walang nahanap na compliance issue")
t("No compliance packets yet", "Pa gen pakè konformite ankò", "Нет пакетов соответствия", "아직 규정 준수 패킷 없음", "Chưa có gói tuân thủ", "Wala pang compliance packet")
t("No compliance records found", "Pa gen dosye konformite jwenn", "Записи соответствия не найдены", "규정 준수 기록을 찾을 수 없음", "Không tìm thấy hồ sơ tuân thủ", "Walang nahanap na compliance record")
t("No content items documented", "Pa gen atik kontni dokimante", "Нет задокументированных элементов", "문서화된 콘텐츠 항목 없음", "Chưa có mục nội dung được ghi nhận", "Walang dokumentadong content item")
t("No conversation selected", "Pa gen konvèsasyon chwazi", "Не выбран разговор", "선택된 대화 없음", "Chưa chọn cuộc trò chuyện", "Walang napiling conversation")
t("No conversations", "Pa gen konvèsasyon", "Нет разговоров", "대화 없음", "Không có cuộc trò chuyện", "Walang conversation")
t("No cost data available", "Pa gen done koût disponib", "Нет данных о затратах", "비용 데이터 없음", "Không có dữ liệu chi phí", "Walang available na cost data")
t("No custom fields for this room.", "Pa gen chan pèsonalize pou pyès sa a.", "Нет пользовательских полей для этой комнаты.", "이 방에 대한 사용자 정의 필드 없음.", "Không có trường tùy chỉnh cho phòng này.", "Walang custom field para sa room na ito.")
t("No custom roles yet. Default role-based permissions are active.", "Pa gen wòl pèsonalize ankò. Pèmisyon pa defo aktif.", "Нет пользовательских ролей. Используются стандартные.", "아직 사용자 정의 역할 없음. 기본 역할 기반 권한이 활성화되어 있습니다.", "Chưa có vai trò tùy chỉnh. Quyền dựa trên vai trò mặc định đang hoạt động.", "Wala pang custom role. Aktibo ang default role-based permission.")
t("No custom templates yet", "Pa gen modèl pèsonalize ankò", "Нет пользовательских шаблонов", "아직 사용자 정의 템플릿 없음", "Chưa có mẫu tùy chỉnh", "Wala pang custom template")
t("No customers found", "Pa gen kliyan jwenn", "Клиенты не найдены", "고객을 찾을 수 없음", "Không tìm thấy khách hàng", "Walang nahanap na customer")
t("No data available", "Pa gen done disponib", "Нет данных", "데이터 없음", "Không có dữ liệu", "Walang available na data")
t("No data yet", "Pa gen done ankò", "Данных ещё нет", "아직 데이터 없음", "Chưa có dữ liệu", "Wala pang data")
t("No description", "Pa gen deskripsyon", "Нет описания", "설명 없음", "Không có mô tả", "Walang paglalarawan")
t("No detailed measurements", "Pa gen mezirman detaye", "Нет детальных измерений", "상세 측정 없음", "Không có đo lường chi tiết", "Walang detalyadong pagsukat")
t("No dispatches", "Pa gen depeche", "Нет отправок", "배차 없음", "Không có điều phối", "Walang dispatch")
t("No documentation checklist is configured for this job type.", "Pa gen lis tchèk dokimantasyon konfigire pou tip travay sa a.", "Чек-лист документации не настроен для этого типа заказа.", "이 작업 유형에 대한 문서 체크리스트가 설정되지 않았습니다.", "Chưa cấu hình danh sách kiểm tra tài liệu cho loại công việc này.", "Walang na-configure na documentation checklist para sa job type na ito.")
t("No documents attached to this lease", "Pa gen dokiman atache ak kontra sa a", "Нет документов к этой аренде", "이 임대에 첨부된 문서 없음", "Không có tài liệu đính kèm cho hợp đồng thuê này", "Walang dokumento na nakakabit sa lease na ito")
t("No documents found", "Pa gen dokiman jwenn", "Документы не найдены", "문서를 찾을 수 없음", "Không tìm thấy tài liệu", "Walang nahanap na dokumento")
t("No documents yet", "Pa gen dokiman ankò", "Нет документов", "아직 문서 없음", "Chưa có tài liệu", "Wala pang dokumento")
t("No drying logs found", "Pa gen jounal sechaj jwenn", "Журналы сушки не найдены", "건조 로그를 찾을 수 없음", "Không tìm thấy nhật ký sấy khô", "Walang nahanap na drying log")
t("No emails found", "Pa gen imèl jwenn", "Письма не найдены", "이메일을 찾을 수 없음", "Không tìm thấy email", "Walang nahanap na email")
t("No emails yet", "Pa gen imèl ankò", "Нет писем", "아직 이메일 없음", "Chưa có email", "Wala pang email")
t("No employees found", "Pa gen anplwaye jwenn", "Сотрудники не найдены", "직원을 찾을 수 없음", "Không tìm thấy nhân viên", "Walang nahanap na empleyado")
t("No entries for this period", "Pa gen antre pou peryòd sa a", "Нет записей за этот период", "이 기간의 항목 없음", "Không có mục cho kỳ này", "Walang entry para sa period na ito")
t("No equipment deployed", "Pa gen ekipman deplwaye", "Нет развёрнутого оборудования", "배치된 장비 없음", "Chưa triển khai thiết bị", "Walang na-deploy na equipment")
t("No equipment found", "Pa gen ekipman jwenn", "Оборудование не найдено", "장비를 찾을 수 없음", "Không tìm thấy thiết bị", "Walang nahanap na equipment")
t("No events scheduled", "Pa gen evènman planifye", "Нет запланированных событий", "예정된 이벤트 없음", "Không có sự kiện đã lên lịch", "Walang naka-schedule na event")
t("No expenses found", "Pa gen depans jwenn", "Расходы не найдены", "지출을 찾을 수 없음", "Không tìm thấy chi phí", "Walang nahanap na gastos")
t("No expenses recorded yet.", "Pa gen depans anrejistre ankò.", "Расходы ещё не записаны.", "아직 기록된 지출 없음.", "Chưa ghi nhận chi phí.", "Wala pang nairecord na gastos.")
t("No expiration", "Pa gen ekspirasyon", "Бессрочно", "만료 없음", "Không có hạn", "Walang expiration")
t("No faxes yet", "Pa gen faks ankò", "Нет факсов", "아직 팩스 없음", "Chưa có fax", "Wala pang fax")
t("No fire restoration records", "Pa gen dosye restorasyon dife", "Нет записей о восстановлении после пожара", "화재 복원 기록 없음", "Không có hồ sơ phục hồi sau cháy", "Walang fire restoration record")
t("No floor plan created", "Pa gen plan etaj kreye", "План этажа не создан", "생성된 평면도 없음", "Chưa tạo sơ đồ tầng", "Walang nagawang floor plan")
t("No folders yet", "Pa gen dosye ankò", "Нет папок", "아직 폴더 없음", "Chưa có thư mục", "Wala pang folder")
t("No forecast data available", "Pa gen done previzyon disponib", "Нет данных прогноза", "예측 데이터 없음", "Không có dữ liệu dự báo", "Walang available na forecast data")
t("No fuel logs", "Pa gen jounal gaz", "Нет журналов заправок", "연료 로그 없음", "Không có nhật ký nhiên liệu", "Walang fuel log")
t("No garage door records", "Pa gen dosye pòt garaj", "Нет записей о гаражных воротах", "차고문 기록 없음", "Không có hồ sơ cửa ga-ra", "Walang garage door record")
t("No generated documents found", "Pa gen dokiman jenere jwenn", "Созданные документы не найдены", "생성된 문서를 찾을 수 없음", "Không tìm thấy tài liệu đã tạo", "Walang nahanap na generated document")
t("No global custom fields. These apply to all rooms.", "Pa gen chan pèsonalize global. Sa yo aplike nan tout pyès.", "Нет глобальных полей. Они применяются ко всем комнатам.", "전역 사용자 정의 필드 없음. 모든 방에 적용됩니다.", "Không có trường tùy chỉnh toàn cục. Áp dụng cho tất cả phòng.", "Walang global custom field. Ito ay para sa lahat ng room.")
t("No growth actions yet", "Pa gen aksyon kwasans ankò", "Нет действий для роста", "아직 성장 작업 없음", "Chưa có hành động tăng trưởng", "Wala pang growth action")
t("No history available", "Pa gen istwa disponib", "Нет истории", "이력 없음", "Không có lịch sử", "Walang available na history")
t("No imports yet", "Pa gen enpòtasyon ankò", "Нет импортов", "아직 가져오기 없음", "Chưa có nhập liệu", "Wala pang import")
t("No inspections found", "Pa gen enspeksyon jwenn", "Инспекции не найдены", "검사를 찾을 수 없음", "Không tìm thấy kiểm tra", "Walang nahanap na inspeksyon")
t("No inspections scheduled", "Pa gen enspeksyon planifye", "Нет запланированных инспекций", "예정된 검사 없음", "Chưa lên lịch kiểm tra", "Walang naka-schedule na inspeksyon")
t("No insurance claims", "Pa gen reklamasyon asirans", "Нет страховых заявок", "보험 청구 없음", "Không có yêu cầu bồi thường bảo hiểm", "Walang insurance claim")
t("No intelligence data available", "Pa gen done entèlijans disponib", "Нет аналитических данных", "인텔리전스 데이터 없음", "Không có dữ liệu phân tích", "Walang available na intelligence data")
t("No interviews found", "Pa gen entèvyou jwenn", "Собеседования не найдены", "면접을 찾을 수 없음", "Không tìm thấy phỏng vấn", "Walang nahanap na interview")
t("No inventory items found", "Pa gen atik envantè jwenn", "Товары не найдены", "재고 항목을 찾을 수 없음", "Không tìm thấy mục tồn kho", "Walang nahanap na inventory item")
t("No invoices yet", "Pa gen fakti ankò", "Нет счетов", "아직 청구서 없음", "Chưa có hóa đơn", "Wala pang invoice")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
