#!/usr/bin/env python3
"""5-language batch 28: remaining C (Correction-end) + D + E values"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

# C remaining
t("Correction", "Koreksyon", "Исправление", "수정", "Sửa chữa", "Pagwawasto")
t("Cost Comparison", "Konparezon Koût", "Сравнение стоимости", "비용 비교", "So sánh chi phí", "Cost Comparison")
t("Cost Variance Trend", "Tandans Varyans Koût", "Тренд отклонений стоимости", "비용 차이 추세", "Xu hướng chênh lệch chi phí", "Cost Variance Trend")
t("Count", "Kantite", "Количество", "수량", "Số lượng", "Bilang")
t("Coverage Period", "Peryòd Kouvèti", "Период покрытия", "보장 기간", "Thời gian bảo hiểm", "Saklaw ng Period")
t("Create Assessment", "Kreye Evalyasyon", "Создать оценку", "평가 생성", "Tạo đánh giá", "Gumawa ng Assessment")
t("Create Compliance Packet", "Kreye Pakè Konformite", "Создать пакет соответствия", "규정 준수 패킷 생성", "Tạo gói tuân thủ", "Gumawa ng Compliance Packet")
t("Create Follow-up", "Kreye Swivi", "Создать последующее действие", "후속 조치 생성", "Tạo theo dõi", "Gumawa ng Follow-up")
t("Create Inspection", "Kreye Enspeksyon", "Создать инспекцию", "검사 생성", "Tạo kiểm tra", "Gumawa ng Inspection")
t("Create Your First Floor Plan", "Kreye Premye Plan Etaj Ou", "Создайте первый поэтажный план", "첫 번째 평면도를 만드세요", "Tạo bản vẽ mặt bằng đầu tiên", "Gumawa ng Unang Floor Plan Mo")
t("Create a new customer record", "Kreye yon nouvo dosye kliyan", "Создать новую запись клиента", "새 고객 레코드 생성", "Tạo hồ sơ khách hàng mới", "Gumawa ng bagong customer record")
t("Create a new invoice", "Kreye yon nouvo fakti", "Создать новый счёт", "새 청구서 생성", "Tạo hóa đơn mới", "Gumawa ng bagong invoice")
t("Create a new job", "Kreye yon nouvo travay", "Создать новый заказ", "새 작업 생성", "Tạo công việc mới", "Gumawa ng bagong trabaho")
t("Create and manage your bids", "Kreye ak jere òf ou", "Создание и управление заявками", "입찰을 생성하고 관리하세요", "Tạo và quản lý đấu thầu", "Gumawa at pamahalaan ang mga bid mo")
t("Created Date", "Dat Kreyasyon", "Дата создания", "생성 날짜", "Ngày tạo", "Petsa ng Paggawa")
t("Credits", "Kredi", "Кредиты", "대변", "Tín dụng", "Mga Credit")
t("Credits by Category", "Kredi pa Kategori", "Кредиты по категориям", "카테고리별 대변", "Tín dụng theo danh mục", "Mga Credit ayon sa Kategorya")
t("Credits will appear here as courses are completed", "Kredi ap parèt isit la lè kou konplete", "Кредиты появятся при завершении курсов", "과정 완료 시 학점이 여기에 표시됩니다", "Tín chỉ sẽ xuất hiện ở đây khi hoàn thành khóa học", "Lalabas dito ang mga credit kapag natapos ang mga kurso")
t("Current Lease", "Kontra Lwaye Aktyèl", "Текущий договор аренды", "현재 임대", "Hợp đồng thuê hiện tại", "Kasalukuyang Lease")
t("Current Period", "Peryòd Aktyèl", "Текущий период", "현재 기간", "Kỳ hiện tại", "Kasalukuyang Period")
t("Current Session", "Sesyon Aktyèl", "Текущий сеанс", "현재 세션", "Phiên hiện tại", "Kasalukuyang Session")
t("Current Value", "Valè Aktyèl", "Текущая стоимость", "현재 가치", "Giá trị hiện tại", "Kasalukuyang Halaga")
t("Current month-to-date", "Mwa aktyèl jiska dat", "Текущий месяц до даты", "이번 달 현재", "Tháng hiện tại đến ngày", "Kasalukuyang buwan hanggang ngayon")
t("Custom Fields", "Chan Pèsonalize", "Пользовательские поля", "사용자 정의 필드", "Trường tùy chỉnh", "Mga Custom Field")
t("Custom Forms", "Fòm Pèsonalize", "Пользовательские формы", "사용자 정의 양식", "Biểu mẫu tùy chỉnh", "Mga Custom Form")
t("Customer Acceptance", "Akseptasyon Kliyan", "Принятие клиентом", "고객 수락", "Khách hàng chấp nhận", "Customer Acceptance")
t("Customer Details", "Detay Kliyan", "Данные клиента", "고객 상세", "Chi tiết khách hàng", "Detalye ng Customer")
t("Customer Event", "Evènman Kliyan", "Событие клиента", "고객 이벤트", "Sự kiện khách hàng", "Customer Event")
t("Customer Insights", "Apèsi Kliyan", "Аналитика клиентов", "고객 인사이트", "Thông tin khách hàng", "Customer Insights")
t("Customer Request", "Demand Kliyan", "Запрос клиента", "고객 요청", "Yêu cầu khách hàng", "Customer Request")
t("Customer Reviews", "Revizyon Kliyan", "Отзывы клиентов", "고객 리뷰", "Đánh giá khách hàng", "Mga Customer Review")
t("Customer Satisfaction", "Satisfaksyon Kliyan", "Удовлетворённость клиентов", "고객 만족", "Sự hài lòng khách hàng", "Customer Satisfaction")
t("Customer Signature", "Siyati Kliyan", "Подпись клиента", "고객 서명", "Chữ ký khách hàng", "Lagda ng Customer")
t("Customer Since", "Kliyan Depi", "Клиент с", "고객 등록일", "Khách hàng từ", "Customer Mula")
t("Customer Type", "Tip Kliyan", "Тип клиента", "고객 유형", "Loại khách hàng", "Uri ng Customer")

# D values
t("Daily", "Chak Jou", "Ежедневно", "일간", "Hàng ngày", "Araw-araw")
t("Damage Assessment", "Evalyasyon Domaj", "Оценка ущерба", "피해 평가", "Đánh giá thiệt hại", "Damage Assessment")
t("Damage Zones", "Zòn Domaj", "Зоны повреждений", "피해 구역", "Vùng hư hại", "Mga Damage Zone")
t("Damaged/Lost", "Domaje/Pèdi", "Повреждён/Потерян", "파손/분실", "Hư hỏng/Mất", "Nasira/Nawala")
t("Data", "Done", "Данные", "데이터", "Dữ liệu", "Data")
t("Data Import", "Enpòtasyon Done", "Импорт данных", "데이터 가져오기", "Nhập dữ liệu", "Data Import")
t("Date Format", "Fòma Dat", "Формат даты", "날짜 형식", "Định dạng ngày", "Format ng Petsa")
t("Date of Loss", "Dat Pèt", "Дата убытка", "손실 날짜", "Ngày tổn thất", "Petsa ng Pagkawala")
t("Days Deployed", "Jou Deplwaye", "Дней развёрнуто", "배치 일수", "Ngày triển khai", "Mga Araw na Na-deploy")
t("Debit", "Debi", "Дебет", "차변", "Nợ", "Debit")
t("Decline", "Refize", "Отклонить", "거절", "Từ chối", "Tanggihan")
t("Deductible:", "Dediktib:", "Франшиза:", "공제액:", "Mức khấu trừ:", "Deductible:")
t("Deductions", "Dediksyon", "Вычеты", "공제", "Khấu trừ", "Mga Deduction")
t("Default Payment Terms", "Tèm Peman Pa Defo", "Условия оплаты по умолчанию", "기본 결제 조건", "Điều khoản thanh toán mặc định", "Default na Payment Terms")
t("Default Role Permissions", "Pèmisyon Wòl Pa Defo", "Разрешения роли по умолчанию", "기본 역할 권한", "Quyền vai trò mặc định", "Default na Role Permissions")
t("Default terms", "Tèm pa defo", "Условия по умолчанию", "기본 조건", "Điều khoản mặc định", "Default na terms")
t("Deficiency", "Defisyans", "Дефект", "결함", "Khiếm khuyết", "Kakulangan")
t("Dehumidifiers", "Dezimidifikatè", "Осушители", "제습기", "Máy hút ẩm", "Mga Dehumidifier")
t("Delayed", "Reta", "Задержан", "지연됨", "Bị trì hoãn", "Na-delay")
t("Delete Floor Plan", "Efase Plan Etaj", "Удалить поэтажный план", "평면도 삭제", "Xóa bản vẽ mặt bằng", "I-delete ang Floor Plan")
t("Delete Template", "Efase Modèl", "Удалить шаблон", "템플릿 삭제", "Xóa mẫu", "I-delete ang Template")
t("Delinquent", "Delenkant", "Просрочен", "연체", "Quá hạn", "Delinquent")
t("Delivered", "Livre", "Доставлено", "배달됨", "Đã giao", "Naihatid")
t("Delivery Rate", "To Livrezon", "Процент доставки", "배달률", "Tỷ lệ giao hàng", "Delivery Rate")
t("Denied", "Refize", "Отклонено", "거부됨", "Bị từ chối", "Tinanggihan")
t("Deposit Paid", "Depo Peye", "Залог оплачен", "보증금 납부", "Đã đặt cọc", "Nabayaran ang Deposito")
t("Deposit Recovered", "Depo Rekipere", "Залог возвращён", "보증금 회수", "Đã thu hồi tiền cọc", "Na-recover ang Deposito")
t("Deposit Required to Start", "Depo Nesesè pou Kòmanse", "Залог для начала работ", "시작 보증금 필요", "Đặt cọc để bắt đầu", "Kailangang Deposito para Magsimula")
t("Depreciation", "Depresyasyon", "Амортизация", "감가상각", "Khấu hao", "Depreciation")
t("Descending", "Desandan", "По убыванию", "내림차순", "Giảm dần", "Pababa")
t("Description:", "Deskripsyon:", "Описание:", "설명:", "Mô tả:", "Paglalarawan:")
t("Deselect All", "Deseleksyone Tout", "Снять выбор со всех", "모두 선택 해제", "Bỏ chọn tất cả", "I-deselect Lahat")
t("Design Change", "Chanjman Konsepsyon", "Изменение дизайна", "설계 변경", "Thay đổi thiết kế", "Pagbabago ng Disenyo")
t("Detail", "Detay", "Деталь", "상세", "Chi tiết", "Detalye")
t("Dew Point", "Pwen Rouze", "Точка росы", "이슬점", "Điểm sương", "Dew Point")
t("Dimensions", "Dimansyon", "Размеры", "치수", "Kích thước", "Mga Dimensyon")
t("Disabled", "Dezaktive", "Отключён", "비활성", "Đã tắt", "Hindi Pinagana")
t("Disconnect", "Dekonekte", "Отключить", "연결 해제", "Ngắt kết nối", "I-disconnect")
t("Discovered During Work", "Dekouvri Pandan Travay", "Обнаружено в ходе работ", "작업 중 발견", "Phát hiện trong khi làm việc", "Natuklasan Habang Nagtatrabaho")
t("Dispatch Board", "Tablo Dispatching", "Диспетчерская доска", "배차 보드", "Bảng điều phối", "Dispatch Board")
t("Dispatched", "Distribye", "Направлен", "배차됨", "Đã điều phối", "Na-dispatch")
t("Display Name", "Non Afiche", "Отображаемое имя", "표시 이름", "Tên hiển thị", "Display Name")
t("Document Templates", "Modèl Dokiman", "Шаблоны документов", "문서 템플릿", "Mẫu tài liệu", "Mga Document Template")
t("Document Title", "Tit Dokiman", "Название документа", "문서 제목", "Tiêu đề tài liệu", "Pamagat ng Dokumento")
t("Documentation", "Dokimantasyon", "Документация", "문서", "Tài liệu", "Dokumentasyon")
t("Documents Generated", "Dokiman Jenere", "Документов создано", "생성된 문서", "Tài liệu đã tạo", "Mga Na-generate na Dokumento")
t("Download PDF", "Telechaje PDF", "Скачать PDF", "PDF 다운로드", "Tải PDF", "I-download ang PDF")
t("Drafts", "Bwouyon", "Черновики", "초안", "Bản nháp", "Mga Draft")
t("Dropdown Options", "Opsyon Dewoule", "Варианты выпадающего списка", "드롭다운 옵션", "Tùy chọn danh sách thả", "Mga Dropdown Option")
t("Dry Standard", "Estanda Sèk", "Стандарт сухости", "건조 표준", "Tiêu chuẩn khô", "Dry Standard")
t("Drying Equipment", "Ekipman Sechaj", "Оборудование для сушки", "건조 장비", "Thiết bị sấy khô", "Mga Drying Equipment")
t("Drying Goal", "Objektif Sechaj", "Цель сушки", "건조 목표", "Mục tiêu sấy khô", "Drying Goal")
t("Drying Progress", "Pwogresyon Sechaj", "Прогресс сушки", "건조 진행 상황", "Tiến trình sấy khô", "Drying Progress")
t("Due", "Dwe", "К оплате", "만기", "Đến hạn", "Due")
t("Due Date", "Dat Limit", "Срок оплаты", "마감일", "Ngày hết hạn", "Due Date")
t("Due This Week", "Dwe Semèn Sa a", "На этой неделе", "이번 주 마감", "Đến hạn tuần này", "Due Ngayong Linggo")
t("Duplicate", "Douplike", "Дубликат", "복제", "Trùng lặp", "Duplicate")
t("During", "Pandan", "Во время", "동안", "Trong", "Sa Panahon ng")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
