#!/usr/bin/env python3
"""5-language batch 12: 'No ...' empty state strings (part 2: No items through No revenue)"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("No items found", "Pa gen atik jwenn", "Элементы не найдены", "항목을 찾을 수 없음", "Không tìm thấy mục", "Walang nahanap na item")
t("No job budgets created yet.", "Pa gen bidjè travay kreye ankò.", "Бюджеты заказов ещё не созданы.", "아직 작업 예산이 생성되지 않았습니다.", "Chưa tạo ngân sách công việc.", "Wala pang nagawang job budget.")
t("No job postings found", "Pa gen piblikasyon travay jwenn", "Вакансии не найдены", "채용 공고를 찾을 수 없음", "Không tìm thấy tin tuyển dụng", "Walang nahanap na job posting")
t("No job revenue or costs found for this period", "Pa gen revni oswa koût travay jwenn pou peryòd sa a", "Нет доходов или затрат за этот период", "이 기간의 작업 수익 또는 비용 없음", "Không tìm thấy doanh thu hoặc chi phí công việc cho kỳ này", "Walang nahanap na job revenue o cost para sa period na ito")
t("No jobs scheduled for today", "Pa gen travay planifye pou jodi a", "Нет заказов на сегодня", "오늘 예정된 작업 없음", "Không có công việc lên lịch hôm nay", "Walang trabahong naka-schedule ngayon")
t("No jobs yet", "Pa gen travay ankò", "Заказов ещё нет", "아직 작업 없음", "Chưa có công việc", "Wala pang trabaho")
t("No jurisdictions found", "Pa gen jiridiksyon jwenn", "Юрисдикции не найдены", "관할구역을 찾을 수 없음", "Không tìm thấy khu vực pháp lý", "Walang nahanap na hurisdiksiyon")
t("No labor rates found", "Pa gen tarif travay jwenn", "Ставки труда не найдены", "인건비 단가를 찾을 수 없음", "Không tìm thấy đơn giá nhân công", "Walang nahanap na labor rate")
t("No lead details available", "Pa gen detay pwopriyetè disponib", "Нет данных о лиде", "리드 상세 정보 없음", "Không có chi tiết khách hàng tiềm năng", "Walang available na lead detail")
t("No leads found", "Pa gen pwopriyetè jwenn", "Лиды не найдены", "리드를 찾을 수 없음", "Không tìm thấy khách hàng tiềm năng", "Walang nahanap na lead")
t("No leads yet", "Pa gen pwopriyetè ankò", "Лидов ещё нет", "아직 리드 없음", "Chưa có khách hàng tiềm năng", "Wala pang lead")
t("No lease history", "Pa gen istwa kontra", "Нет истории аренды", "임대 이력 없음", "Không có lịch sử hợp đồng thuê", "Walang lease history")
t("No lease history for this unit", "Pa gen istwa kontra pou inite sa a", "Нет истории аренды для этого объекта", "이 유닛의 임대 이력 없음", "Không có lịch sử hợp đồng thuê cho đơn vị này", "Walang lease history para sa unit na ito")
t("No leases", "Pa gen kontra", "Нет аренд", "임대 없음", "Không có hợp đồng thuê", "Walang lease")
t("No leases found", "Pa gen kontra jwenn", "Аренды не найдены", "임대를 찾을 수 없음", "Không tìm thấy hợp đồng thuê", "Walang nahanap na lease")
t("No lien items", "Pa gen atik lyen", "Нет залоговых позиций", "유치권 항목 없음", "Không có mục giữ tài sản", "Walang lien item")
t("No lien record found for this job", "Pa gen dosye lyen jwenn pou travay sa a", "Нет залоговой записи для этого заказа", "이 작업의 유치권 기록 없음", "Không tìm thấy hồ sơ giữ tài sản cho công việc này", "Walang nahanap na lien record para sa trabaho na ito")
t("No lien records found", "Pa gen dosye lyen jwenn", "Залоговые записи не найдены", "유치권 기록을 찾을 수 없음", "Không tìm thấy hồ sơ giữ tài sản", "Walang nahanap na lien record")
t("No line items recorded", "Pa gen atik liy anrejistre", "Нет записанных позиций", "기록된 항목 없음", "Chưa ghi nhận mục hàng", "Walang nairecord na line item")
t("No locksmith records", "Pa gen dosye seritye", "Нет записей о слесарных работах", "열쇠 기록 없음", "Không có hồ sơ thợ khóa", "Walang locksmith record")
t("No maintenance items", "Pa gen atik antretyen", "Нет элементов обслуживания", "유지보수 항목 없음", "Không có mục bảo trì", "Walang maintenance item")
t("No maintenance records", "Pa gen dosye antretyen", "Нет записей обслуживания", "유지보수 기록 없음", "Không có hồ sơ bảo trì", "Walang maintenance record")
t("No maintenance requests found", "Pa gen demann antretyen jwenn", "Запросы обслуживания не найдены", "유지보수 요청을 찾을 수 없음", "Không tìm thấy yêu cầu bảo trì", "Walang nahanap na maintenance request")
t("No marketplace listings", "Pa gen lis mache", "Нет объявлений на маркетплейсе", "마켓플레이스 목록 없음", "Không có danh sách trên thị trường", "Walang marketplace listing")
t("No matching tasks for comparison.", "Pa gen travay koresponn pou konparezon.", "Нет задач для сравнения.", "비교할 일치하는 작업 없음.", "Không có nhiệm vụ phù hợp để so sánh.", "Walang tumutugmang task para sa comparison.")
t("No materials found", "Pa gen materyèl jwenn", "Материалы не найдены", "자재를 찾을 수 없음", "Không tìm thấy vật liệu", "Walang nahanap na materyales")
t("No materials logged", "Pa gen materyèl anrejistre", "Материалы не записаны", "기록된 자재 없음", "Chưa ghi nhận vật liệu", "Walang nairecord na materyales")
t("No materials tracked yet", "Pa gen materyèl swivi ankò", "Материалы ещё не отслеживаются", "아직 추적된 자재 없음", "Chưa theo dõi vật liệu", "Wala pang materyales na naka-track")
t("No meetings scheduled", "Pa gen reyinyon planifye", "Нет запланированных встреч", "예정된 회의 없음", "Chưa lên lịch cuộc họp", "Walang naka-schedule na meeting")
t("No messages", "Pa gen mesaj", "Нет сообщений", "메시지 없음", "Không có tin nhắn", "Walang mensahe")
t("No messages yet", "Pa gen mesaj ankò", "Сообщений ещё нет", "아직 메시지 없음", "Chưa có tin nhắn", "Wala pang mensahe")
t("No messages yet. Start the conversation.", "Pa gen mesaj ankò. Kòmanse konvèsasyon an.", "Сообщений нет. Начните разговор.", "아직 메시지 없음. 대화를 시작하세요.", "Chưa có tin nhắn. Bắt đầu cuộc trò chuyện.", "Wala pang mensahe. Simulan ang conversation.")
t("No moisture readings found", "Pa gen lekti imidite jwenn", "Показания влажности не найдены", "수분 판독값을 찾을 수 없음", "Không tìm thấy số đọc độ ẩm", "Walang nahanap na moisture reading")
t("No moisture readings recorded for this job", "Pa gen lekti imidite anrejistre pou travay sa a", "Нет показаний влажности для этого заказа", "이 작업의 수분 판독값 기록 없음", "Chưa ghi nhận số đọc độ ẩm cho công việc này", "Walang nairecord na moisture reading para sa trabaho na ito")
t("No mold remediation records", "Pa gen dosye remèd mwazi", "Нет записей об удалении плесени", "곰팡이 제거 기록 없음", "Không có hồ sơ xử lý nấm mốc", "Walang mold remediation record")
t("No monthly periods", "Pa gen peryòd chak mwa", "Нет месячных периодов", "월간 기간 없음", "Không có kỳ hàng tháng", "Walang buwanang period")
t("No notes recorded", "Pa gen nòt anrejistre", "Нет записанных заметок", "기록된 메모 없음", "Chưa ghi chú", "Walang nairecord na tala")
t("No notes yet", "Pa gen nòt ankò", "Нет заметок", "아직 메모 없음", "Chưa có ghi chú", "Wala pang tala")
t("No notifications yet", "Pa gen notifikasyon ankò", "Нет уведомлений", "아직 알림 없음", "Chưa có thông báo", "Wala pang notification")
t("No onboarding checklists found", "Pa gen lis tchèk onbòding jwenn", "Чек-листы адаптации не найдены", "온보딩 체크리스트를 찾을 수 없음", "Không tìm thấy danh sách kiểm tra nhập môn", "Walang nahanap na onboarding checklist")
t("No outreach history", "Pa gen istwa kontakte", "Нет истории обращений", "아웃리치 이력 없음", "Không có lịch sử tiếp cận", "Walang outreach history")
t("No outreach sent", "Pa gen kontakte voye", "Нет отправленных обращений", "전송된 아웃리치 없음", "Chưa gửi tiếp cận", "Walang naipadala na outreach")
t("No outstanding balances", "Pa gen balans anreta", "Нет задолженностей", "미결 잔액 없음", "Không có số dư chưa thanh toán", "Walang outstanding balance")
t("No pay stubs for this period", "Pa gen talon salè pou peryòd sa a", "Нет расчётных листков за этот период", "이 기간의 급여 명세서 없음", "Không có phiếu lương cho kỳ này", "Walang pay stub para sa period na ito")
t("No payments found", "Pa gen peman jwenn", "Платежи не найдены", "결제를 찾을 수 없음", "Không tìm thấy thanh toán", "Walang nahanap na bayad")
t("No payments recorded", "Pa gen peman anrejistre", "Нет записанных платежей", "기록된 결제 없음", "Chưa ghi nhận thanh toán", "Walang nairecord na bayad")
t("No payroll runs yet", "Pa gen egzekisyon salè ankò", "Нет расчётов зарплаты", "아직 급여 실행 없음", "Chưa chạy lương", "Wala pang payroll run")
t("No performance reviews found", "Pa gen evalyasyon pèfòmans jwenn", "Отзывы о работе не найдены", "성과 리뷰를 찾을 수 없음", "Không tìm thấy đánh giá hiệu suất", "Walang nahanap na performance review")
t("No permits for this job", "Pa gen pèmi pou travay sa a", "Нет разрешений для этого заказа", "이 작업의 허가 없음", "Không có giấy phép cho công việc này", "Walang permit para sa trabaho na ito")
t("No permits found", "Pa gen pèmi jwenn", "Разрешения не найдены", "허가를 찾을 수 없음", "Không tìm thấy giấy phép", "Walang nahanap na permit")
t("No pest control records", "Pa gen dosye kontwòl parazit", "Нет записей о борьбе с вредителями", "방역 기록 없음", "Không có hồ sơ kiểm soát sâu bệnh", "Walang pest control record")
t("No photos captured", "Pa gen foto kaptire", "Нет сделанных фотографий", "촬영된 사진 없음", "Chưa chụp ảnh", "Walang nakuhang litrato")
t("No photos for this room", "Pa gen foto pou pyès sa a", "Нет фотографий для этой комнаты", "이 방의 사진 없음", "Không có ảnh cho phòng này", "Walang litrato para sa room na ito")
t("No photos in this filter", "Pa gen foto nan filtè sa a", "Нет фотографий по этому фильтру", "이 필터에 사진 없음", "Không có ảnh trong bộ lọc này", "Walang litrato sa filter na ito")
t("No photos uploaded yet", "Pa gen foto telechaje ankò", "Фотографии ещё не загружены", "아직 업로드된 사진 없음", "Chưa tải ảnh lên", "Wala pang nai-upload na litrato")
t("No photos yet", "Pa gen foto ankò", "Нет фотографий", "아직 사진 없음", "Chưa có ảnh", "Wala pang litrato")
t("No plan data available", "Pa gen done plan disponib", "Нет данных о плане", "계획 데이터 없음", "Không có dữ liệu kế hoạch", "Walang available na plan data")
t("No policyholder info", "Pa gen enfò detantè polis", "Нет данных о страхователе", "보험 계약자 정보 없음", "Không có thông tin chủ hợp đồng", "Walang policyholder info")
t("No predictions match filter", "Pa gen prediksyon koresponn filtè", "Нет прогнозов по фильтру", "필터에 맞는 예측 없음", "Không có dự đoán khớp bộ lọc", "Walang prediction na tumutugma sa filter")
t("No price book items found", "Pa gen atik liv pri jwenn", "Позиции прайс-листа не найдены", "가격표 항목을 찾을 수 없음", "Không tìm thấy mục bảng giá", "Walang nahanap na price book item")
t("No pricing adjustments yet", "Pa gen ajisteman pri ankò", "Нет ценовых корректировок", "아직 가격 조정 없음", "Chưa có điều chỉnh giá", "Wala pang pricing adjustment")
t("No pricing data available", "Pa gen done pri disponib", "Нет данных о ценах", "가격 데이터 없음", "Không có dữ liệu giá", "Walang available na pricing data")
t("No pricing factors applied yet", "Pa gen faktè pri aplike ankò", "Ценовые факторы ещё не применены", "아직 적용된 가격 요인 없음", "Chưa áp dụng yếu tố giá", "Wala pang na-apply na pricing factor")
t("No pricing rules configured", "Pa gen règ pri konfigire", "Правила ценообразования не настроены", "설정된 가격 규칙 없음", "Chưa cấu hình quy tắc giá", "Walang na-configure na pricing rule")
t("No properties found", "Pa gen pwopriyete jwenn", "Объекты не найдены", "부동산을 찾을 수 없음", "Không tìm thấy bất động sản", "Walang nahanap na property")
t("No property address", "Pa gen adrès pwopriyete", "Нет адреса объекта", "부동산 주소 없음", "Không có địa chỉ bất động sản", "Walang property address")
t("No property income or expenses found for this period", "Pa gen revni oswa depans pwopriyete jwenn pou peryòd sa a", "Нет доходов или расходов по объекту за этот период", "이 기간의 부동산 수입 또는 지출 없음", "Không tìm thấy thu nhập hoặc chi phí bất động sản cho kỳ này", "Walang nahanap na property income o expense para sa period na ito")
t("No property scans yet", "Pa gen eskanè pwopriyete ankò", "Нет сканирований объекта", "아직 부동산 스캔 없음", "Chưa có quét bất động sản", "Wala pang property scan")
t("No psychrometric readings yet", "Pa gen lekti psikwometrik ankò", "Нет психрометрических показаний", "아직 건습구 판독값 없음", "Chưa có số đọc tâm ẩm", "Wala pang psychrometric reading")
t("No purchase orders found", "Pa gen kòmann acha jwenn", "Заказы на закупку не найдены", "구매 주문을 찾을 수 없음", "Không tìm thấy đơn đặt hàng", "Walang nahanap na purchase order")
t("No purchase orders yet", "Pa gen kòmann acha ankò", "Нет заказов на закупку", "아직 구매 주문 없음", "Chưa có đơn đặt hàng", "Wala pang purchase order")
t("No rating", "Pa gen evalyasyon", "Нет рейтинга", "평점 없음", "Chưa đánh giá", "Walang rating")
t("No readings yet", "Pa gen lekti ankò", "Нет показаний", "아직 판독값 없음", "Chưa có số đọc", "Wala pang reading")
t("No records generated yet.", "Pa gen dosye jenere ankò.", "Записи ещё не сгенерированы.", "아직 생성된 기록 없음.", "Chưa tạo hồ sơ.", "Wala pang na-generate na record.")
t("No recurring templates", "Pa gen modèl regilye", "Нет повторяющихся шаблонов", "반복 템플릿 없음", "Không có mẫu định kỳ", "Walang recurring template")
t("No removed equipment", "Pa gen ekipman retire", "Нет демонтированного оборудования", "제거된 장비 없음", "Không có thiết bị đã tháo", "Walang tinanggal na equipment")
t("No rent charges found", "Pa gen chaj lwaye jwenn", "Начисления аренды не найдены", "임대료 부과 내역을 찾을 수 없음", "Không tìm thấy phí thuê", "Walang nahanap na rent charge")
t("No reports generated yet", "Pa gen rapò jenere ankò", "Отчёты ещё не созданы", "아직 생성된 보고서 없음", "Chưa tạo báo cáo", "Wala pang na-generate na report")
t("No resources", "Pa gen resous", "Нет ресурсов", "리소스 없음", "Không có tài nguyên", "Walang resource")
t("No revenue data available", "Pa gen done revni disponib", "Нет данных о доходах", "수익 데이터 없음", "Không có dữ liệu doanh thu", "Walang available na revenue data")
t("No revenue data available yet. Start creating jobs and invoices to see insights.", "Pa gen done revni disponib ankò. Kòmanse kreye travay ak fakti pou wè apèsi.", "Нет данных о доходах. Создайте заказы и счета.", "아직 수익 데이터 없음. 작업과 청구서를 생성하여 인사이트를 확인하세요.", "Chưa có dữ liệu doanh thu. Bắt đầu tạo công việc và hóa đơn để xem phân tích.", "Wala pang available na revenue data. Mag-create ng mga trabaho at invoice para makita ang insight.")
t("No revenue data for this period", "Pa gen done revni pou peryòd sa a", "Нет данных о доходах за этот период", "이 기간의 수익 데이터 없음", "Không có dữ liệu doanh thu cho kỳ này", "Walang revenue data para sa period na ito")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
