#!/usr/bin/env python3
"""5-language batch 20: S values (second half: Send through System Templates) + lowercase"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("Send Email", "Voye Imèl", "Отправить письмо", "이메일 보내기", "Gửi email", "Magpadala ng Email")
t("Send Fax", "Voye Faks", "Отправить факс", "팩스 보내기", "Gửi fax", "Magpadala ng Fax")
t("Send Invoice", "Voye Fakti", "Отправить счёт", "청구서 보내기", "Gửi hóa đơn", "Magpadala ng Invoice")
t("Send Later", "Voye Pita", "Отправить позже", "나중에 보내기", "Gửi sau", "Ipadala Mamaya")
t("Send Now", "Voye Kounye a", "Отправить сейчас", "지금 보내기", "Gửi ngay", "Ipadala Ngayon")
t("Send SMS", "Voye SMS", "Отправить СМС", "문자 보내기", "Gửi SMS", "Magpadala ng SMS")
t("Send an invitation to join your team", "Voye yon envitasyon pou rejwenn ekip ou", "Отправьте приглашение в команду", "팀 참여 초대를 보내세요", "Gửi lời mời tham gia nhóm của bạn", "Magpadala ng imbitasyon para sumali sa team mo")
t("Send and receive faxes", "Voye ak resevwa faks", "Отправка и получение факсов", "팩스 송수신", "Gửi và nhận fax", "Magpadala at tumanggap ng fax")
t("Send for Approval", "Voye pou Apwobasyon", "Отправить на утверждение", "승인 요청", "Gửi để phê duyệt", "Ipadala para sa Pag-apruba")
t("Send for Signature", "Voye pou Siyati", "Отправить на подпись", "서명 요청", "Gửi để ký", "Ipadala para sa Lagda")
t("Send to Customer", "Voye bay Kliyan", "Отправить клиенту", "고객에게 보내기", "Gửi cho khách hàng", "Ipadala sa Customer")
t("Sender", "Ekspedityè", "Отправитель", "발신자", "Người gửi", "Nagpadala")
t("Sent Date", "Dat Voye", "Дата отправки", "발송 날짜", "Ngày gửi", "Petsa ng Pagpapadala")
t("Sent This Month", "Voye Mwa Sa a", "Отправлено в этом месяце", "이번 달 발송", "Đã gửi tháng này", "Naipadala Ngayong Buwan")
t("Serial Number", "Nimewo Seri", "Серийный номер", "일련번호", "Số sê-ri", "Serial Number")
t("Service Address", "Adrès Sèvis", "Адрес обслуживания", "서비스 주소", "Địa chỉ dịch vụ", "Address ng Serbisyo")
t("Service Agreements", "Akò Sèvis", "Договоры обслуживания", "서비스 계약", "Hợp đồng dịch vụ", "Mga Service Agreement")
t("Service Area", "Zòn Sèvis", "Зона обслуживания", "서비스 지역", "Khu vực dịch vụ", "Lugar ng Serbisyo")
t("Service Frequency", "Frekans Sèvis", "Частота обслуживания", "서비스 빈도", "Tần suất dịch vụ", "Dalas ng Serbisyo")
t("Service History", "Istwa Sèvis", "История обслуживания", "서비스 이력", "Lịch sử dịch vụ", "Kasaysayan ng Serbisyo")
t("Service Level Agreement deadlines auto-calculate from assignment time", "Dat limit Akò Nivo Sèvis kalkile otomatikman apati lè asiyman", "Сроки SLA рассчитываются автоматически от момента назначения", "서비스 수준 협약 마감일은 배정 시간부터 자동 계산됩니다", "Thời hạn SLA tự động tính từ thời điểm phân công", "Ang SLA deadlines ay auto-calculate mula sa assignment time")
t("Service Radius", "Reyon Sèvis", "Радиус обслуживания", "서비스 반경", "Bán kính dịch vụ", "Radius ng Serbisyo")
t("Service Types", "Tip Sèvis", "Типы услуг", "서비스 유형", "Loại dịch vụ", "Mga Uri ng Serbisyo")
t("Service Zip Codes", "Kòd Postal Sèvis", "Почтовые индексы обслуживания", "서비스 우편번호", "Mã bưu chính dịch vụ", "Mga Zip Code ng Serbisyo")
t("Service:", "Sèvis:", "Услуга:", "서비스:", "Dịch vụ:", "Serbisyo:")
t("Services Included", "Sèvis Enkli", "Включённые услуги", "포함 서비스", "Dịch vụ bao gồm", "Mga Kasama na Serbisyo")
t("Services This Month", "Sèvis Mwa Sa a", "Услуги в этом месяце", "이번 달 서비스", "Dịch vụ tháng này", "Mga Serbisyo Ngayong Buwan")
t("Set up automated workflows to save time.", "Konfigure pwosesis otomatize pou ekonomize tan.", "Настройте автоматические процессы для экономии времени.", "시간 절약을 위한 자동화 워크플로를 설정하세요.", "Thiết lập quy trình tự động để tiết kiệm thời gian.", "Mag-setup ng automated workflows para makatipid ng oras.")
t("Setup", "Konfigirasyon", "Настройка", "설정", "Thiết lập", "Setup")
t("Severity", "Gravite", "Серьёзность", "심각도", "Mức độ nghiêm trọng", "Kalubhaan")
t("Shape", "Fòm", "Форма", "형태", "Hình dạng", "Hugis")
t("Shared with Me", "Pataje ak Mwen", "Доступно мне", "나와 공유됨", "Được chia sẻ với tôi", "Ibinahagi sa Akin")
t("Shipping", "Ekspedisyon", "Доставка", "배송", "Vận chuyển", "Shipping")
t("Shortlisted", "Lis Kout", "В шорт-листе", "최종 후보", "Danh sách rút gọn", "Shortlisted")
t("Show low stock only", "Montre sèlman estòk ba", "Показать только с низким запасом", "재고 부족만 표시", "Chỉ hiện hàng tồn kho thấp", "Ipakita lang ang low stock")
t("Showing", "Montre", "Показано", "표시 중", "Đang hiển thị", "Ipinapakita")
t("Side-by-Side P&L Comparison", "Konparezon P&L Kote a Kote", "Сравнение P&L бок о бок", "손익 비교", "So sánh Lãi & Lỗ song song", "Side-by-Side P&L Comparison")
t("Sidebar", "Ba lateral", "Боковая панель", "사이드바", "Thanh bên", "Sidebar")
t("Sidebar control", "Kontwòl ba lateral", "Управление боковой панелью", "사이드바 제어", "Điều khiển thanh bên", "Kontrol ng Sidebar")
t("Sign Out All Devices", "Dekonekte Tout Aparèy", "Выйти со всех устройств", "모든 기기에서 로그아웃", "Đăng xuất tất cả thiết bị", "Mag-sign Out sa Lahat ng Device")
t("Sign Out Everywhere", "Dekonekte Toupatou", "Выйти отовсюду", "모든 곳에서 로그아웃", "Đăng xuất mọi nơi", "Mag-sign Out sa Lahat ng Lugar")
t("Sign above to approve this estimate", "Siyen anwo pou apwouve estimasyon sa a", "Подпишите выше для утверждения сметы", "이 견적을 승인하려면 위에 서명하세요", "Ký ở trên để phê duyệt dự toán này", "Pumirma sa itaas para i-approve ang estimate na ito")
t("Sign out of all devices and sessions", "Dekonekte nan tout aparèy ak sesyon", "Выйти со всех устройств и сеансов", "모든 기기 및 세션에서 로그아웃", "Đăng xuất khỏi tất cả thiết bị và phiên", "Mag-sign out sa lahat ng device at session")
t("Signature", "Siyati", "Подпись", "서명", "Chữ ký", "Lagda")
t("Signed", "Siyen", "Подписано", "서명됨", "Đã ký", "Nilagdaan")
t("Signer", "Siyatè", "Подписант", "서명자", "Người ký", "Pumirma")
t("Site Photo", "Foto Sit", "Фото объекта", "현장 사진", "Ảnh công trường", "Litrato ng Site")
t("Site Plan", "Plan Sit", "План участка", "배치도", "Mặt bằng", "Site Plan")
t("Site Surveys", "Sondaj Sit", "Обследования объекта", "현장 조사", "Khảo sát hiện trường", "Mga Site Survey")
t("Size", "Gwosè", "Размер", "크기", "Kích thước", "Laki")
t("Sketch Engine", "Motè Desen", "Графический движок", "스케치 엔진", "Công cụ phác thảo", "Sketch Engine")
t("Slack Days", "Jou Mou", "Дни запаса", "여유일", "Ngày dự phòng", "Slack Days")
t("Slow", "Lan", "Медленно", "느림", "Chậm", "Mabagal")
t("Smart Notifications", "Notifikasyon Entèlijan", "Умные уведомления", "스마트 알림", "Thông báo thông minh", "Mga Smart Notification")
t("Smart Pricing Rules", "Règ Pri Entèlijan", "Умные правила ценообразования", "스마트 가격 규칙", "Quy tắc định giá thông minh", "Mga Smart Pricing Rule")
t("Snippet", "Moso", "Фрагмент", "스니펫", "Đoạn mã", "Snippet")
t("Solar", "Solè", "Солнечная энергия", "태양광", "Năng lượng mặt trời", "Solar")
t("Soon", "Byento", "Скоро", "곧", "Sắp", "Malapit na")
t("Sort by", "Triye pa", "Сортировать по", "정렬 기준", "Sắp xếp theo", "Ayusin ayon sa")
t("Source", "Sous", "Источник", "출처", "Nguồn", "Pinagmulan")
t("Source Stopped", "Sous Kanpe", "Источник остановлен", "소스 중지됨", "Nguồn đã dừng", "Nahinto ang Source")
t("Sources", "Sous", "Источники", "출처", "Nguồn", "Mga Pinagmulan")
t("Specializations", "Espesyalizasyon", "Специализации", "전문 분야", "Chuyên môn", "Mga Espesyalisasyon")
t("Specifications", "Espesifikasyon", "Характеристики", "사양", "Thông số kỹ thuật", "Mga Specification")
t("Split", "Divize", "Разделить", "분할", "Chia", "Hatiin")
t("Spring Jobs", "Travay Prentan", "Весенние заказы", "봄 작업", "Công việc mùa xuân", "Mga Spring Job")
t("Sq Ft", "Pi Kare", "Кв. фут", "평방피트", "Sq Ft", "Sq Ft")
t("Square Footage", "Sipèfisi an Pi Kare", "Площадь (кв. фут.)", "평방피트", "Diện tích (sq ft)", "Square Footage")
t("Stage", "Etap", "Этап", "단계", "Giai đoạn", "Yugto")
t("Standard", "Estanda", "Стандартный", "표준", "Tiêu chuẩn", "Standard")
t("Star", "Zetwal", "Звезда", "별표", "Gắn sao", "Star")
t("Start", "Kòmanse", "Начать", "시작", "Bắt đầu", "Simula")
t("Start Drawing", "Kòmanse Desine", "Начать рисование", "그리기 시작", "Bắt đầu vẽ", "Magsimulang Gumuhit")
t("Start New Reconciliation", "Kòmanse Nouvo Rekonsilyasyon", "Начать новую сверку", "새 조정 시작", "Bắt đầu đối chiếu mới", "Magsimula ng Bagong Reconciliation")
t("Start a conversation with your team.", "Kòmanse yon konvèsasyon ak ekip ou.", "Начните беседу с командой.", "팀과 대화를 시작하세요.", "Bắt đầu cuộc trò chuyện với nhóm của bạn.", "Magsimula ng pag-uusap sa team mo.")
t("Start a property walkthrough to document conditions.", "Kòmanse yon vizit pwopriyete pou dokimante kondisyon.", "Начните обход объекта для документирования состояния.", "부동산 현장 조사를 시작하여 상태를 기록하세요.", "Bắt đầu khảo sát bất động sản để ghi nhận tình trạng.", "Magsimula ng property walkthrough para i-document ang conditions.")
t("Start blank", "Kòmanse vid", "Начать с нуля", "빈 상태로 시작", "Bắt đầu trống", "Magsimula na blangko")
t("Start logging moisture readings to track drying progress across restoration jobs.", "Kòmanse anrejistre lekti imidite pou swiv pwogrè sechaj sou travay restorasyon.", "Начните записывать показания влажности для отслеживания хода сушки.", "수분 판독을 기록하여 복원 작업의 건조 진행 상황을 추적하세요.", "Bắt đầu ghi nhận số đọc độ ẩm để theo dõi tiến trình sấy khô trên các công việc phục hồi.", "Simulang mag-log ng moisture readings para ma-track ang drying progress sa mga restoration job.")
t("State", "Eta", "Штат", "주", "Tiểu bang", "Estado")
t("State Lien Rules", "Règ Gravman Eta", "Правила залога штата", "주 유치권 규정", "Quy định cầm giữ theo tiểu bang", "Mga State Lien Rule")
t("Statement Balance", "Balans Relve", "Баланс выписки", "명세서 잔액", "Số dư sao kê", "Statement Balance")
t("Statement Date", "Dat Relve", "Дата выписки", "명세서 날짜", "Ngày sao kê", "Petsa ng Statement")
t("Statement Ending Balance", "Balans Final Relve", "Конечный баланс выписки", "명세서 마감 잔액", "Số dư cuối kỳ sao kê", "Ending Balance ng Statement")
t("Statutory Reference", "Referans Legal", "Ссылка на закон", "법적 참조", "Tham chiếu pháp luật", "Statutory Reference")
t("Step", "Etap", "Шаг", "단계", "Bước", "Hakbang")
t("Storage Location", "Kote Estokaj", "Место хранения", "보관 위치", "Vị trí lưu trữ", "Lokasyon ng Storage")
t("Storage Used", "Estokaj Itilize", "Использованное хранилище", "사용된 저장 공간", "Dung lượng đã dùng", "Ginamit na Storage")
t("Storm Chase", "Chas Tanpèt", "Погоня за штормом", "스톰 체이스", "Truy đuổi bão", "Storm Chase")
t("Storm Damage Assessment", "Evalyasyon Domaj Tanpèt", "Оценка ущерба от шторма", "폭풍 피해 평가", "Đánh giá thiệt hại do bão", "Storm Damage Assessment")
t("Storm Date", "Dat Tanpèt", "Дата шторма", "폭풍 날짜", "Ngày bão", "Petsa ng Bagyo")
t("Storm Events", "Evènman Tanpèt", "Штормовые события", "폭풍 이벤트", "Sự kiện bão", "Mga Storm Event")
t("Storm Pipeline", "Pipeline Tanpèt", "Воронка штормов", "스톰 파이프라인", "Kênh bão", "Storm Pipeline")
t("Storm Type", "Tip Tanpèt", "Тип шторма", "폭풍 유형", "Loại bão", "Uri ng Bagyo")
t("Street", "Ri", "Улица", "거리", "Đường", "Kalye")
t("Strengths", "Fòs", "Сильные стороны", "강점", "Điểm mạnh", "Mga Lakas")
t("Stripe Connected", "Stripe Konekte", "Stripe подключён", "Stripe 연결됨", "Đã kết nối Stripe", "Nakakonekta ang Stripe")
t("Structural", "Estriktirèl", "Конструктивный", "구조", "Kết cấu", "Structural")
t("Subcontractor", "Sou-kontraktè", "Субподрядчик", "하도급업체", "Nhà thầu phụ", "Subcontractor")
t("Subcontractors", "Sou-kontraktè", "Субподрядчики", "하도급업체", "Nhà thầu phụ", "Mga Subcontractor")
t("Subject", "Sijè", "Тема", "제목", "Chủ đề", "Paksa")
t("Submit Bid", "Soumèt Òf", "Подать заявку", "입찰 제출", "Nộp đấu thầu", "Mag-submit ng Bid")
t("Submittal", "Soumisyon", "Подача", "제출물", "Hồ sơ nộp", "Submittal")
t("Submitted", "Soumèt", "Подано", "제출됨", "Đã nộp", "Nai-submit")
t("Submitted:", "Soumèt:", "Подано:", "제출:", "Đã nộp:", "Nai-submit:")
t("Substantial", "Sibstansyèl", "Существенный", "상당한", "Đáng kể", "Malaki")
t("Subtitle", "Sou Tit", "Подзаголовок", "부제", "Phụ đề", "Subtitle")
t("Successfully created", "Kreye avèk siksè", "Успешно создано", "성공적으로 생성됨", "Đã tạo thành công", "Matagumpay na nagawa")
t("Successfully deleted", "Efase avèk siksè", "Успешно удалено", "성공적으로 삭제됨", "Đã xóa thành công", "Matagumpay na na-delete")
t("Successfully updated", "Mete ajou avèk siksè", "Успешно обновлено", "성공적으로 업데이트됨", "Đã cập nhật thành công", "Matagumpay na na-update")
t("Suggested Date", "Dat Sijere", "Предложенная дата", "제안 날짜", "Ngày đề xuất", "Iminungkahing Petsa")
t("Suggestion Outcomes", "Rezilta Sijesyon", "Результаты предложений", "제안 결과", "Kết quả đề xuất", "Mga Resulta ng Suhestiyon")
t("Supervisor", "Sipèvizè", "Руководитель", "감독관", "Giám sát", "Supervisor")
t("Supp. Rate", "Tarif Sip.", "Ставка доп.", "추가 단가", "Đơn giá bổ sung", "Supp. Rate")
t("Supplements", "Sipleman", "Дополнения", "추가 청구", "Bổ sung", "Mga Supplement")
t("Supplier", "Founisè", "Поставщик", "공급업체", "Nhà cung cấp", "Supplier")
t("Supplier pricing not configured", "Pri founisè pa konfigure", "Цены поставщика не настроены", "공급업체 가격 미설정", "Chưa cấu hình giá nhà cung cấp", "Hindi pa naka-configure ang supplier pricing")
t("Supplies", "Founitè", "Расходные материалы", "소모품", "Vật tư", "Mga Supply")
t("Suspend", "Sispann", "Приостановить", "중지", "Tạm ngưng", "I-suspend")
t("Sync", "Senkwonize", "Синхронизация", "동기화", "Đồng bộ", "Sync")
t("System", "Sistèm", "Система", "시스템", "Hệ thống", "Sistema")
t("System Form Templates", "Modèl Fòmilè Sistèm", "Системные шаблоны форм", "시스템 양식 템플릿", "Mẫu biểu mẫu hệ thống", "Mga System Form Template")
t("System Templates", "Modèl Sistèm", "Системные шаблоны", "시스템 템플릿", "Mẫu hệ thống", "Mga System Template")
# lowercase
t("selected", "chwazi", "выбрано", "선택됨", "đã chọn", "napili")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
