#!/usr/bin/env python3
"""5-language batch 18: R values (second half) + lowercase p/r"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("Related Job", "Travay Lye", "Связанный заказ", "관련 작업", "Công việc liên quan", "Kaugnay na Trabaho")
t("Relative", "Relatif", "Относительный", "상대적", "Tương đối", "Kamag-anak")
t("Release Amount", "Montan Liberasyon", "Сумма выпуска", "해제 금액", "Số tiền giải ngân", "Release Amount")
t("Release Conditions", "Kondisyon Liberasyon", "Условия выпуска", "해제 조건", "Điều kiện giải ngân", "Mga Release Condition")
t("Release Retention", "Libere Retansyon", "Освободить удержание", "보유 해제", "Giải trừ giữ lại", "I-release ang Retention")
t("Remediation", "Remèd", "Устранение", "개선", "Khắc phục", "Remediation")
t("Remediation Plan", "Plan Remèd", "План устранения", "개선 계획", "Kế hoạch khắc phục", "Remediation Plan")
t("Reminder", "Rapèl", "Напоминание", "알림", "Nhắc nhở", "Paalala")
t("Remove Area", "Retire Zòn", "Удалить зону", "구역 제거", "Xóa khu vực", "Alisin ang Area")
t("Remove Member", "Retire Manm", "Удалить участника", "멤버 제거", "Xóa thành viên", "Alisin ang Miyembro")
t("Remove from Team", "Retire nan Ekip", "Удалить из команды", "팀에서 제거", "Xóa khỏi nhóm", "Alisin sa Team")
t("Removed At", "Retire Nan", "Удалено в", "제거 일시", "Đã xóa lúc", "Tinanggal Noong")
t("Renewal", "Renouvèlman", "Продление", "갱신", "Gia hạn", "Renewal")
t("Renewal Date", "Dat Renouvèlman", "Дата продления", "갱신일", "Ngày gia hạn", "Petsa ng Renewal")
t("Renewal required", "Renouvèlman obligatwa", "Требуется продление", "갱신 필요", "Yêu cầu gia hạn", "Kailangan ng renewal")
t("Rent", "Lwaye", "Аренда", "임대료", "Tiền thuê", "Upa")
t("Rent Collected", "Lwaye Kolekte", "Собранная аренда", "수금된 임대료", "Tiền thuê đã thu", "Nakolektang Upa")
t("Rent Due (This Month)", "Lwaye Dwe (Mwa Sa a)", "Аренда к оплате (этот месяц)", "이번 달 임대료", "Tiền thuê đến hạn (tháng này)", "Upa na Due (Ngayong Buwan)")
t("Rent Roll", "Lis Lwaye", "Реестр аренды", "임대료 목록", "Sổ thuê", "Rent Roll")
t("Rent charges and payments will appear here", "Chaj lwaye ak peman ap parèt isit", "Начисления и платежи аренды появятся здесь", "임대료 부과 및 결제가 여기에 표시됩니다", "Phí thuê và thanh toán sẽ hiển thị ở đây", "Ang mga rent charge at bayad ay lalabas dito")
t("Rental Income", "Revni Lwaye", "Арендный доход", "임대 수입", "Thu nhập cho thuê", "Kita sa Pag-upa")
t("Rental Portfolio", "Pòtfèy Lwaye", "Арендный портфель", "임대 포트폴리오", "Danh mục cho thuê", "Rental Portfolio")
t("Rents received", "Lwaye resevwa", "Полученные арендные платежи", "수금된 임대료", "Tiền thuê đã nhận", "Mga natanggap na upa")
t("Reopen Period", "Relouvri Peryòd", "Повторно открыть период", "기간 재개방", "Mở lại kỳ", "Muling Buksan ang Period")
t("Repair", "Reparasyon", "Ремонт", "수리", "Sửa chữa", "Pag-aayos")
t("Repaired", "Repare", "Отремонтировано", "수리됨", "Đã sửa chữa", "Naayos")
t("Repairs", "Reparasyon", "Ремонты", "수리", "Sửa chữa", "Mga Pag-aayos")
t("Replaced", "Ranplase", "Заменено", "교체됨", "Đã thay thế", "Napalitan")
t("Replacement Planning", "Planifikasyon Ranplasman", "Планирование замены", "교체 계획", "Kế hoạch thay thế", "Replacement Planning")
t("Replacement Value", "Valè Ranplasman", "Стоимость замены", "교체 가치", "Giá trị thay thế", "Replacement Value")
t("Reply All", "Reponn Tout", "Ответить всем", "전체 답장", "Trả lời tất cả", "Sagutin Lahat")
t("Report", "Rapò", "Отчёт", "보고서", "Báo cáo", "Ulat")
t("Reporter", "Rapòtè", "Репортёр", "보고자", "Người báo cáo", "Reporter")
t("Request Review", "Demann Revizyon", "Запросить проверку", "리뷰 요청", "Yêu cầu đánh giá", "Humiling ng Review")
t("Requests Sent", "Demann Voye", "Запросы отправлены", "전송된 요청", "Yêu cầu đã gửi", "Mga Naipadala na Request")
t("Requests are managed from the main Maintenance section", "Demann jere nan seksyon Antretyen prensipal la", "Запросы управляются из раздела Обслуживание", "요청은 메인 유지보수 섹션에서 관리됩니다", "Yêu cầu được quản lý từ phần Bảo trì chính", "Ang mga request ay pinamamahalaan mula sa pangunahing Maintenance section")
t("Require approval for high-value actions before they go out", "Egzije apwobasyon pou aksyon gwo valè anvan yo soti", "Требовать одобрение для важных действий", "고가치 작업이 전송되기 전 승인 필요", "Yêu cầu phê duyệt cho các hành động có giá trị cao trước khi gửi đi", "Kailangan ng approval para sa mahahalagang aksyon bago ito maipadala")
t("Required", "Obligatwa", "Обязательно", "필수", "Bắt buộc", "Kinakailangan")
t("Required Deposit", "Depo Obligatwa", "Обязательный депозит", "필수 보증금", "Đặt cọc bắt buộc", "Kinakailangang Deposito")
t("Required Items", "Atik Obligatwa", "Обязательные позиции", "필수 항목", "Mục bắt buộc", "Mga Kinakailangang Item")
t("Requirements", "Egzijans", "Требования", "요구사항", "Yêu cầu", "Mga Kinakailangan")
t("Requirements Checklist", "Lis Tchèk Egzijans", "Чек-лист требований", "요구사항 체크리스트", "Danh sách kiểm tra yêu cầu", "Requirements Checklist")
t("Requires signature", "Egzije siyati", "Требуется подпись", "서명 필요", "Yêu cầu chữ ký", "Kailangan ng lagda")
t("Reset to defaults", "Remèt pa defo", "Сбросить по умолчанию", "기본값으로 초기화", "Đặt lại mặc định", "I-reset sa default")
t("Residential", "Rezidansyèl", "Жилой", "주거용", "Dân cư", "Residential")
t("Resolution", "Rezolisyon", "Решение", "해결", "Giải quyết", "Resolusyon")
t("Resolved", "Rezoud", "Решено", "해결됨", "Đã giải quyết", "Nalutas")
t("Resources", "Resous", "Ресурсы", "리소스", "Tài nguyên", "Mga Resource")
t("Response", "Repons", "Ответ", "응답", "Phản hồi", "Tugon")
t("Response Time", "Tan Repons", "Время ответа", "응답 시간", "Thời gian phản hồi", "Response Time")
t("Responsibilities", "Responsablite", "Обязанности", "책임", "Trách nhiệm", "Mga Responsibilidad")
t("Restocked", "Re-estoke", "Пополнено", "재입고됨", "Đã nhập lại kho", "Na-restock")
t("Restoration", "Restorasyon", "Реставрация", "복원", "Phục hồi", "Restoration")
t("Restore", "Restore", "Восстановить", "복원", "Phục hồi", "I-restore")
t("Restricted", "Restrenn", "Ограниченный", "제한됨", "Bị hạn chế", "Restricted")
t("Result", "Rezilta", "Результат", "결과", "Kết quả", "Resulta")
t("Resume", "Rezime", "Резюме", "이력서", "Sơ yếu lý lịch", "Resume")
t("Retainage", "Retansyon", "Удержание", "보유금", "Giữ lại", "Retainage")
t("Retained Earnings", "Benefis Retni", "Нераспределённая прибыль", "이익잉여금", "Lợi nhuận giữ lại", "Retained Earnings")
t("Retry", "Reseye", "Повторить", "재시도", "Thử lại", "Subukan Muli")
t("Return Notes", "Nòt Retounen", "Заметки о возврате", "반환 메모", "Ghi chú trả lại", "Mga Tala ng Pagbabalik")
t("Return Tool", "Retounen Zouti", "Вернуть инструмент", "도구 반환", "Trả lại dụng cụ", "Ibalik ang Tool")
t("Returned to vendor", "Retounen bay vandè", "Возвращено поставщику", "거래처에 반환됨", "Đã trả lại nhà cung cấp", "Ibinalik sa vendor")
t("Revenue Growth", "Kwasans Revni", "Рост доходов", "매출 성장", "Tăng trưởng doanh thu", "Paglago ng Kita")
t("Revenue Insights", "Apèsi Revni", "Аналитика доходов", "매출 인사이트", "Phân tích doanh thu", "Revenue Insights")
t("Revenue Intelligence", "Entèlijans Revni", "Аналитика доходов", "매출 인텔리전스", "Phân tích thông minh doanh thu", "Revenue Intelligence")
t("Revenue Overview", "Apèsi Revni", "Обзор доходов", "매출 개요", "Tổng quan doanh thu", "Revenue Overview")
t("Revenue This Month", "Revni Mwa Sa a", "Доход этого месяца", "이번 달 매출", "Doanh thu tháng này", "Kita Ngayong Buwan")
t("Revenue Trend", "Tandans Revni", "Динамика доходов", "매출 추이", "Xu hướng doanh thu", "Revenue Trend")
t("Revenue by Category", "Revni pa Kategori", "Доход по категориям", "카테고리별 매출", "Doanh thu theo danh mục", "Kita ayon sa Kategorya")
t("Revenue by Job Type", "Revni pa Tip Travay", "Доход по типам заказов", "작업 유형별 매출", "Doanh thu theo loại công việc", "Kita ayon sa Uri ng Trabaho")
t("Revenue by Month", "Revni pa Mwa", "Доход по месяцам", "월별 매출", "Doanh thu theo tháng", "Kita ayon sa Buwan")
t("Review All", "Revize Tout", "Просмотреть все", "전체 검토", "Xem xét tất cả", "I-review Lahat")
t("Review and approve employee time entries", "Revize epi apwouve antre tan anplwaye", "Проверка и утверждение табелей сотрудников", "직원 시간 기록 검토 및 승인", "Xem xét và phê duyệt mục thời gian của nhân viên", "I-review at aprubahan ang time entry ng mga empleyado")
t("Reviewer", "Revizè", "Рецензент", "검토자", "Người đánh giá", "Reviewer")
t("Reviews", "Revizyon", "Отзывы", "리뷰", "Đánh giá", "Mga Review")
t("Reviews Received", "Revizyon Resevwa", "Полученные отзывы", "받은 리뷰", "Đánh giá đã nhận", "Mga Natanggap na Review")
t("Revised Amount", "Montan Revize", "Исправленная сумма", "수정 금액", "Số tiền đã sửa", "Binagong Halaga")
t("Revision", "Revizyon", "Ревизия", "수정", "Phiên bản sửa đổi", "Rebisyon")
t("Revisions Required", "Revizyon Obligatwa", "Требуются исправления", "수정 필요", "Yêu cầu sửa đổi", "Kailangan ng Rebisyon")
t("Revoke", "Revoke", "Отозвать", "취소", "Thu hồi", "I-revoke")
t("Ridge", "Fèt", "Конёк", "용마루", "Nóc mái", "Ridge")
t("Ring Group", "Gwoup Sonri", "Группа вызова", "링 그룹", "Nhóm chuông", "Ring Group")
t("Ring Person", "Sonnen Moun", "Позвонить человеку", "개인 호출", "Gọi người", "Ring Person")
t("Robert Chen", "Robert Chen", "Robert Chen", "Robert Chen", "Robert Chen", "Robert Chen")
t("Role", "Wòl", "Роль", "역할", "Vai trò", "Tungkulin")
t("Role Permissions", "Pèmisyon Wòl", "Разрешения роли", "역할 권한", "Quyền vai trò", "Mga Pahintulot ng Tungkulin")
t("Roles & Permissions", "Wòl & Pèmisyon", "Роли и разрешения", "역할 및 권한", "Vai trò & Quyền", "Mga Tungkulin & Pahintulot")
t("Roof", "Twati", "Крыша", "지붕", "Mái nhà", "Bubong")
t("Roof Area", "Zòn Twati", "Площадь крыши", "지붕 면적", "Diện tích mái nhà", "Roof Area")
t("Roofing", "Twati", "Кровля", "지붕 공사", "Lợp mái", "Roofing")
t("Room", "Pyès", "Комната", "방", "Phòng", "Kwarto")
t("Room Checklist", "Lis Tchèk Pyès", "Чек-лист комнаты", "방 체크리스트", "Danh sách kiểm tra phòng", "Room Checklist")
t("Room Custom Fields", "Chan Pèsonalize Pyès", "Пользовательские поля комнаты", "방 사용자 정의 필드", "Trường tùy chỉnh phòng", "Mga Custom Field ng Kwarto")
t("Room List", "Lis Pyès", "Список комнат", "방 목록", "Danh sách phòng", "Listahan ng Kwarto")
t("Room Presets", "Presi Pyès", "Предустановки комнат", "방 프리셋", "Cài đặt sẵn phòng", "Mga Room Preset")
t("Room Type", "Tip Pyès", "Тип комнаты", "방 유형", "Loại phòng", "Uri ng Kwarto")
t("Rooms", "Pyès", "Комнаты", "방", "Phòng", "Mga Kwarto")
t("Rooms are added during the walkthrough on the mobile app", "Pyès ajoute pandan vizit sou aplikasyon mobil la", "Комнаты добавляются при обходе в мобильном приложении", "방은 모바일 앱에서 현장 조사 중 추가됩니다", "Phòng được thêm trong quá trình khảo sát trên ứng dụng di động", "Ang mga kwarto ay idinaragdag habang nasa walkthrough sa mobile app")
t("Routine", "Woutin", "Плановый", "정기", "Định kỳ", "Routine")
t("Rules", "Règ", "Правила", "규칙", "Quy tắc", "Mga Panuntunan")
t("Run Payroll", "Egzekite Salè", "Начислить зарплату", "급여 실행", "Chạy lương", "Mag-run ng Payroll")
t("Run a property scan with trade estimation first.", "Egzekite yon eskanè pwopriyete ak estimasyon metye anvan.", "Сначала запустите сканирование с оценкой.", "먼저 공종 견적이 포함된 부동산 스캔을 실행하세요.", "Chạy quét bất động sản với ước tính ngành trước.", "Mag-run muna ng property scan na may trade estimation.")
t("Run the engine to generate predictions from your equipment data", "Egzekite motè a pou jenere prediksyon nan done ekipman ou", "Запустите анализ для прогнозов по оборудованию", "장비 데이터에서 예측을 생성하려면 엔진을 실행하세요", "Chạy công cụ để tạo dự đoán từ dữ liệu thiết bị", "I-run ang engine para mag-generate ng prediction mula sa equipment data mo")
t("Runs", "Egzekisyon", "Запуски", "실행", "Lần chạy", "Mga Run")
# lowercase
t("per page", "pa paj", "на страницу", "페이지당", "mỗi trang", "bawat pahina")
t("results", "rezilta", "результатов", "결과", "kết quả", "mga resulta")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
