#!/usr/bin/env python3
"""5-language batch 19: S values (first half: SKU through Select...)"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("SKU", "SKU", "Артикул", "SKU", "SKU", "SKU")
t("SLA Violations", "Vyolasyon SLA", "Нарушения SLA", "SLA 위반", "Vi phạm SLA", "Mga Paglabag sa SLA")
t("SMS", "SMS", "СМС", "문자", "SMS", "SMS")
t("SMS Notifications", "Notifikasyon SMS", "СМС-уведомления", "문자 알림", "Thông báo SMS", "Mga SMS Notification")
t("SMS Templates", "Modèl SMS", "Шаблоны СМС", "문자 템플릿", "Mẫu SMS", "Mga SMS Template")
t("SMS conversations with customers", "Konvèsasyon SMS ak kliyan", "СМС-переписка с клиентами", "고객과의 문자 대화", "Cuộc trò chuyện SMS với khách hàng", "Mga SMS na pag-uusap sa mga customer")
t("SMS opt-in", "Enskri SMS", "Подписка на СМС", "문자 수신 동의", "Đăng ký nhận SMS", "SMS opt-in")
t("ST Hours", "Èdtan ST", "Часы ST", "ST 시간", "Giờ ST", "ST Hours")
t("Safety", "Sekirite", "Безопасность", "안전", "An toàn", "Kaligtasan")
t("Salary Range", "Ranje Salè", "Диапазон зарплаты", "급여 범위", "Khoảng lương", "Saklaw ng Sahod")
t("Sarah Martinez", "Sarah Martinez", "Сара Мартинес", "Sarah Martinez", "Sarah Martinez", "Sarah Martinez")
t("Satellite data is being processed. This usually takes a few seconds.", "Done satelit ap trete. Sa anjeneral pran kèk segond.", "Спутниковые данные обрабатываются. Обычно это занимает несколько секунд.", "위성 데이터를 처리 중입니다. 보통 몇 초 정도 걸립니다.", "Dữ liệu vệ tinh đang được xử lý. Thường mất vài giây.", "Pinoproseso ang satellite data. Karaniwang tumatagal ng ilang segundo.")
t("Satellite imagery, roof measurements, structural data", "Imaj satelit, mezi twa, done estriktirèl", "Спутниковые снимки, замеры крыши, данные конструкции", "위성 이미지, 지붕 측정, 구조 데이터", "Hình ảnh vệ tinh, đo đạc mái, dữ liệu kết cấu", "Satellite imagery, sukat ng bubong, structural data")
t("Satisfaction Score", "Pwen Satisfaksyon", "Оценка удовлетворённости", "만족도 점수", "Điểm hài lòng", "Satisfaction Score")
t("Save Adjustment", "Anrejistre Ajisteman", "Сохранить корректировку", "조정 저장", "Lưu điều chỉnh", "I-save ang Adjustment")
t("Save Entry", "Anrejistre Antre", "Сохранить запись", "항목 저장", "Lưu mục nhập", "I-save ang Entry")
t("Save Reading", "Anrejistre Lekti", "Сохранить показание", "판독 저장", "Lưu số đọc", "I-save ang Reading")
t("Save your current estimate as a reusable template", "Anrejistre estimasyon aktyèl ou kòm yon modèl reitilizab", "Сохраните текущую смету как шаблон", "현재 견적을 재사용 가능한 템플릿으로 저장하세요", "Lưu dự toán hiện tại làm mẫu có thể tái sử dụng", "I-save ang kasalukuyang estimate bilang reusable template")
t("Saved successfully", "Anrejistre avèk siksè", "Успешно сохранено", "성공적으로 저장됨", "Đã lưu thành công", "Matagumpay na na-save")
t("Scan Date", "Dat Eskanè", "Дата сканирования", "스캔 날짜", "Ngày quét", "Petsa ng Scan")
t("Scan Options", "Opsyon Eskanè", "Параметры сканирования", "스캔 옵션", "Tùy chọn quét", "Mga Option ng Scan")
t("Scan Property", "Eskanè Pwopriyete", "Сканировать объект", "부동산 스캔", "Quét bất động sản", "I-scan ang Property")
t("Scan Type", "Tip Eskanè", "Тип сканирования", "스캔 유형", "Loại quét", "Uri ng Scan")
t("Scan any address for instant roof, wall, and trade measurements", "Eskanè nenpòt adrès pou mezi twa, mi, ak mezi metye enstantane", "Сканируйте любой адрес для мгновенных замеров крыши, стен и специализированных измерений", "주소를 스캔하여 즉시 지붕, 벽, 공종별 측정값을 받으세요", "Quét bất kỳ địa chỉ nào để đo tức thì mái, tường và các phép đo chuyên ngành", "I-scan ang kahit anong address para sa instant na sukat ng bubong, dingding, at trade measurements")
t("Scan failed. The address may not have satellite coverage.", "Eskanè pa reyisi. Adrès la ka pa gen kouvèti satelit.", "Сканирование не удалось. Адрес может быть вне зоны спутникового покрытия.", "스캔 실패. 해당 주소에 위성 커버리지가 없을 수 있습니다.", "Quét thất bại. Địa chỉ có thể không có dữ liệu vệ tinh.", "Nabigo ang scan. Maaaring walang satellite coverage ang address.")
t("Scan this QR code with your authenticator app", "Eskanè kòd QR sa a ak aplikasyon otantikatè ou", "Отсканируйте QR-код в приложении-аутентификаторе", "인증 앱으로 이 QR 코드를 스캔하세요", "Quét mã QR này bằng ứng dụng xác thực của bạn", "I-scan ang QR code na ito gamit ang authenticator app mo")
t("Scanning in progress...", "Eskanè an kou...", "Сканирование выполняется...", "스캔 진행 중...", "Đang quét...", "Nagsa-scan...")
t("Scanning...", "Eskanè...", "Сканирование...", "스캔 중...", "Đang quét...", "Nagsa-scan...")
t("Schedule E", "Barèm E", "Приложение E", "Schedule E", "Biểu mẫu E", "Schedule E")
t("Schedule E Category", "Kategori Barèm E", "Категория Приложения E", "Schedule E 카테고리", "Danh mục Biểu mẫu E", "Kategorya ng Schedule E")
t("Schedule Inspection", "Planifye Enspeksyon", "Запланировать инспекцию", "검사 예약", "Lên lịch kiểm tra", "Mag-schedule ng Inspection")
t("Schedule Maintenance", "Planifye Antretyen", "Запланировать обслуживание", "유지보수 예약", "Lên lịch bảo trì", "Mag-schedule ng Maintenance")
t("Schedule Meeting", "Planifye Reyinyon", "Запланировать встречу", "미팅 예약", "Lên lịch họp", "Mag-schedule ng Meeting")
t("Schedule video calls with customers and team members.", "Planifye apèl videyo ak kliyan ak manm ekip.", "Планируйте видеозвонки с клиентами и командой.", "고객 및 팀원과 화상 통화를 예약하세요.", "Lên lịch cuộc gọi video với khách hàng và thành viên nhóm.", "Mag-schedule ng video calls sa mga customer at team members.")
t("Schedule your first property inspection.", "Planifye premye enspeksyon pwopriyete ou.", "Запланируйте первую инспекцию объекта.", "첫 번째 부동산 검사를 예약하세요.", "Lên lịch kiểm tra bất động sản đầu tiên.", "Mag-schedule ng unang property inspection mo.")
t("Scheduled Date", "Dat Planifye", "Запланированная дата", "예정 날짜", "Ngày dự kiến", "Naka-schedule na Petsa")
t("Scheduled Jobs", "Travay Planifye", "Запланированные заказы", "예정된 작업", "Công việc đã lên lịch", "Mga Naka-schedule na Trabaho")
t("Scope", "Anvègi", "Объём работ", "범위", "Phạm vi", "Saklaw")
t("Scope of Work", "Anvègi Travay", "Объём работ", "작업 범위", "Phạm vi công việc", "Saklaw ng Trabaho")
t("Score", "Pwen", "Оценка", "점수", "Điểm", "Score")
t("Score Alerts", "Alèt Pwen", "Оповещения оценок", "점수 알림", "Cảnh báo điểm", "Mga Score Alert")
t("Scorecards", "Kat Pwen", "Оценочные карты", "성과표", "Bảng điểm", "Mga Scorecard")
t("Screening", "Depistaj", "Скрининг", "심사", "Sàng lọc", "Screening")
t("Scrubbers", "Netwayè Lè", "Скрубберы", "스크러버", "Máy lọc khí", "Mga Scrubber")
t("Search OSHA standards...", "Chèche estanda OSHA...", "Поиск стандартов OSHA...", "OSHA 기준 검색...", "Tìm kiếm tiêu chuẩn OSHA...", "Maghanap ng OSHA standards...")
t("Search applicants...", "Chèche aplikan...", "Поиск кандидатов...", "지원자 검색...", "Tìm kiếm ứng viên...", "Maghanap ng applicants...")
t("Search bids...", "Chèche òf...", "Поиск заявок...", "입찰 검색...", "Tìm kiếm đấu thầu...", "Maghanap ng bids...")
t("Search claims...", "Chèche reklamasyon...", "Поиск заявок...", "청구 검색...", "Tìm kiếm yêu cầu bồi thường...", "Maghanap ng claims...")
t("Search customers...", "Chèche kliyan...", "Поиск клиентов...", "고객 검색...", "Tìm kiếm khách hàng...", "Maghanap ng customers...")
t("Search documents...", "Chèche dokiman...", "Поиск документов...", "문서 검색...", "Tìm kiếm tài liệu...", "Maghanap ng documents...")
t("Search employees...", "Chèche anplwaye...", "Поиск сотрудников...", "직원 검색...", "Tìm kiếm nhân viên...", "Maghanap ng employees...")
t("Search equipment...", "Chèche ekipman...", "Поиск оборудования...", "장비 검색...", "Tìm kiếm thiết bị...", "Maghanap ng equipment...")
t("Search estimates...", "Chèche estimasyon...", "Поиск смет...", "견적 검색...", "Tìm kiếm dự toán...", "Maghanap ng estimates...")
t("Search inspections...", "Chèche enspeksyon...", "Поиск инспекций...", "검사 검색...", "Tìm kiếm kiểm tra...", "Maghanap ng inspections...")
t("Search inventory...", "Chèche envantè...", "Поиск по складу...", "재고 검색...", "Tìm kiếm kho hàng...", "Maghanap ng inventory...")
t("Search invoices...", "Chèche fakti...", "Поиск счетов...", "청구서 검색...", "Tìm kiếm hóa đơn...", "Maghanap ng invoices...")
t("Search leads...", "Chèche pwopriyetè...", "Поиск лидов...", "리드 검색...", "Tìm kiếm khách hàng tiềm năng...", "Maghanap ng leads...")
t("Search marketplace...", "Chèche mache...", "Поиск на маркетплейсе...", "마켓플레이스 검색...", "Tìm kiếm trên sàn...", "Maghanap sa marketplace...")
t("Search or jump to...", "Chèche oswa ale nan...", "Поиск или перейти к...", "검색 또는 이동...", "Tìm kiếm hoặc chuyển đến...", "Maghanap o pumunta sa...")
t("Search permits...", "Chèche pèmi...", "Поиск разрешений...", "허가 검색...", "Tìm kiếm giấy phép...", "Maghanap ng permits...")
t("Search schedules...", "Chèche orè...", "Поиск расписаний...", "일정 검색...", "Tìm kiếm lịch trình...", "Maghanap ng schedules...")
t("Search subcontractors...", "Chèche sou-kontraktè...", "Поиск субподрядчиков...", "하도급업체 검색...", "Tìm kiếm nhà thầu phụ...", "Maghanap ng subcontractors...")
t("Search team members...", "Chèche manm ekip...", "Поиск сотрудников...", "팀원 검색...", "Tìm kiếm thành viên nhóm...", "Maghanap ng team members...")
t("Search vehicles...", "Chèche machin...", "Поиск транспорта...", "차량 검색...", "Tìm kiếm phương tiện...", "Maghanap ng vehicles...")
t("Search vendors...", "Chèche vandè...", "Поиск поставщиков...", "거래처 검색...", "Tìm kiếm nhà cung cấp...", "Maghanap ng vendors...")
t("Seasonal", "Sezonye", "Сезонный", "시즌", "Theo mùa", "Seasonal")
t("Secondary", "Segondè", "Вторичный", "보조", "Phụ", "Pangalawa")
t("Secondary Contact", "Kontak Segondè", "Дополнительный контакт", "보조 연락처", "Liên hệ phụ", "Pangalawang Contact")
t("Section", "Seksyon", "Раздел", "섹션", "Phần", "Seksyon")
t("Security", "Sekirite", "Безопасность", "보안", "Bảo mật", "Seguridad")
t("Security Deposit", "Depo Sekirite", "Залог", "보증금", "Tiền đặt cọc", "Security Deposit")
t("Security Settings", "Paramèt Sekirite", "Настройки безопасности", "보안 설정", "Cài đặt bảo mật", "Mga Setting ng Seguridad")
t("Select All", "Chwazi Tout", "Выбрать все", "모두 선택", "Chọn tất cả", "Piliin Lahat")
t("Select Bid Format", "Chwazi Fòma Òf", "Выбрать формат заявки", "입찰 형식 선택", "Chọn định dạng đấu thầu", "Pumili ng Bid Format")
t("Select Date", "Chwazi Dat", "Выбрать дату", "날짜 선택", "Chọn ngày", "Pumili ng Petsa")
t("Select Job", "Chwazi Travay", "Выбрать заказ", "작업 선택", "Chọn công việc", "Pumili ng Trabaho")
t("Select a claim...", "Chwazi yon reklamasyon...", "Выберите заявку...", "청구를 선택하세요...", "Chọn yêu cầu bồi thường...", "Pumili ng claim...")
t("Select a conversation", "Chwazi yon konvèsasyon", "Выберите беседу", "대화를 선택하세요", "Chọn cuộc trò chuyện", "Pumili ng pag-uusap")
t("Select a conversation to start chatting", "Chwazi yon konvèsasyon pou kòmanse pale", "Выберите беседу, чтобы начать общение", "대화를 선택하여 채팅을 시작하세요", "Chọn cuộc trò chuyện để bắt đầu nhắn tin", "Pumili ng pag-uusap para magsimulang mag-chat")
t("Select a conversation to view", "Chwazi yon konvèsasyon pou wè", "Выберите беседу для просмотра", "볼 대화를 선택하세요", "Chọn cuộc trò chuyện để xem", "Pumili ng pag-uusap para tingnan")
t("Select a day", "Chwazi yon jou", "Выберите день", "날짜를 선택하세요", "Chọn một ngày", "Pumili ng araw")
t("Select a message to view", "Chwazi yon mesaj pou wè", "Выберите сообщение для просмотра", "볼 메시지를 선택하세요", "Chọn tin nhắn để xem", "Pumili ng mensahe para tingnan")
t("Select account...", "Chwazi kont...", "Выберите счёт...", "계정 선택...", "Chọn tài khoản...", "Pumili ng account...")
t("Select action...", "Chwazi aksyon...", "Выберите действие...", "동작 선택...", "Chọn hành động...", "Pumili ng aksyon...")
t("Select an action to view details", "Chwazi yon aksyon pou wè detay", "Выберите действие для просмотра", "동작을 선택하여 상세 정보를 확인하세요", "Chọn hành động để xem chi tiết", "Pumili ng aksyon para tingnan ang detalye")
t("Select an assessment to view details", "Chwazi yon evalyasyon pou wè detay", "Выберите оценку для просмотра", "평가를 선택하여 상세 정보를 확인하세요", "Chọn đánh giá để xem chi tiết", "Pumili ng assessment para tingnan ang detalye")
t("Select customer", "Chwazi kliyan", "Выберите клиента", "고객 선택", "Chọn khách hàng", "Pumili ng customer")
t("Select customer...", "Chwazi kliyan...", "Выберите клиента...", "고객 선택...", "Chọn khách hàng...", "Pumili ng customer...")
t("Select employee...", "Chwazi anplwaye...", "Выберите сотрудника...", "직원 선택...", "Chọn nhân viên...", "Pumili ng employee...")
t("Select job...", "Chwazi travay...", "Выберите заказ...", "작업 선택...", "Chọn công việc...", "Pumili ng trabaho...")
t("Select program...", "Chwazi pwogram...", "Выберите программу...", "프로그램 선택...", "Chọn chương trình...", "Pumili ng program...")
t("Select reason...", "Chwazi rezon...", "Выберите причину...", "사유 선택...", "Chọn lý do...", "Pumili ng dahilan...")
t("Select team member", "Chwazi manm ekip", "Выберите сотрудника", "팀원 선택", "Chọn thành viên nhóm", "Pumili ng team member")
t("Select trade", "Chwazi metye", "Выберите специальность", "공종 선택", "Chọn ngành nghề", "Pumili ng trade")
t("Select trade to import materials", "Chwazi metye pou enpòte materyèl", "Выберите специальность для импорта материалов", "자재를 가져올 공종을 선택하세요", "Chọn ngành nghề để nhập vật liệu", "Pumili ng trade para mag-import ng materials")
t("Select trigger...", "Chwazi deklanchè...", "Выберите триггер...", "트리거 선택...", "Chọn kích hoạt...", "Pumili ng trigger...")
t("Select type...", "Chwazi tip...", "Выберите тип...", "유형 선택...", "Chọn loại...", "Pumili ng uri...")
t("Select vendor...", "Chwazi vandè...", "Выберите поставщика...", "거래처 선택...", "Chọn nhà cung cấp...", "Pumili ng vendor...")
t("Select...", "Chwazi...", "Выберите...", "선택...", "Chọn...", "Pumili...")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
