#!/usr/bin/env python3
"""5-language batch 8: K-L values"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

# K values
t("Kanban", "Kanban", "Канбан", "칸반", "Kanban", "Kanban")
t("Key", "Kle", "Ключ", "키", "Khóa", "Susi")
t("Keyboard Shortcuts", "Rakousi Klavye", "Горячие клавиши", "키보드 단축키", "Phím tắt", "Mga Keyboard Shortcut")

# L values
t("LAB:", "LAB:", "LAB:", "LAB:", "LAB:", "LAB:")
t("Label", "Etikèt", "Метка", "라벨", "Nhãn", "Label")
t("Labor", "Travay", "Труд", "인건비", "Nhân công", "Paggawa")
t("Labor Cost", "Koût Travay", "Стоимость труда", "인건비", "Chi phí nhân công", "Gastos sa Paggawa")
t("Labor Coverage", "Kouvèti Travay", "Покрытие труда", "인건비 보장", "Bảo hiểm nhân công", "Saklaw ng Paggawa")
t("Labor Duration", "Dire Travay", "Продолжительность работ", "작업 기간", "Thời gian nhân công", "Tagal ng Paggawa")
t("Labor Hours", "Èdtan Travay", "Часы работы", "작업 시간", "Giờ nhân công", "Oras ng Paggawa")
t("Labor Rate", "Tarif Travay", "Ставка труда", "인건비 단가", "Đơn giá nhân công", "Rate ng Paggawa")
t("Labor Rate Summary", "Rezime Tarif Travay", "Сводка ставок труда", "인건비 단가 요약", "Tóm tắt đơn giá nhân công", "Buod ng Rate ng Paggawa")
t("Labor Rates", "Tarif Travay", "Ставки труда", "인건비 단가", "Đơn giá nhân công", "Mga Rate ng Paggawa")
t("Labor Warranty", "Garanti Travay", "Гарантия на работу", "인건비 보증", "Bảo hành nhân công", "Garantiya sa Paggawa")
t("Landscaping", "Amanjman Peyizaj", "Ландшафтный дизайн", "조경", "Cảnh quan", "Landscaping")
t("Language", "Lang", "Язык", "언어", "Ngôn ngữ", "Wika")
t("Last", "Dènye", "Последний", "마지막", "Cuối cùng", "Huli")
t("Last Active", "Dènye Aktif", "Последняя активность", "마지막 활동", "Hoạt động gần nhất", "Huling Aktibo")
t("Last Contact", "Dènye Kontak", "Последний контакт", "마지막 연락", "Liên hệ gần nhất", "Huling Kontak")
t("Last GPS", "Dènye GPS", "Последний GPS", "마지막 GPS", "GPS gần nhất", "Huling GPS")
t("Last Job", "Dènye Travay", "Последний заказ", "마지막 작업", "Công việc gần nhất", "Huling Trabaho")
t("Last Modified", "Dènye Modifye", "Последнее изменение", "마지막 수정", "Sửa đổi gần nhất", "Huling Binago")
t("Last Month", "Mwa Pase", "Прошлый месяц", "지난달", "Tháng trước", "Nakaraang Buwan")
t("Last Name", "Siyati", "Фамилия", "성", "Họ", "Apelyido")
t("Last Reading", "Dènye Lekti", "Последнее показание", "마지막 판독값", "Số đọc gần nhất", "Huling Reading")
t("Last Run", "Dènye Egzekisyon", "Последний запуск", "마지막 실행", "Lần chạy gần nhất", "Huling Pagpapatakbo")
t("Last Service", "Dènye Sèvis", "Последнее обслуживание", "마지막 서비스", "Dịch vụ gần nhất", "Huling Serbisyo")
t("Last Updated", "Dènye Mete Ajou", "Последнее обновление", "마지막 업데이트", "Cập nhật gần nhất", "Huling Na-update")
t("Last Week", "Semèn Pase", "На прошлой неделе", "지난주", "Tuần trước", "Nakaraang Linggo")
t("Last Year", "Ane Pase", "В прошлом году", "작년", "Năm ngoái", "Nakaraang Taon")
t("Late Fee", "Frè Reta", "Штраф за просрочку", "연체 수수료", "Phí trễ hạn", "Late Fee")
t("Late Finish", "Fini Reta", "Позднее завершение", "지연 완료", "Hoàn thành trễ", "Late Finish")
t("Late fee", "Frè reta", "Штраф за просрочку", "연체 수수료", "Phí trễ hạn", "Late fee")
t("Latest Conditions", "Dènye Kondisyon", "Последние условия", "최신 상태", "Điều kiện mới nhất", "Pinakabagong Kondisyon")
t("Layout", "Dispozisyon", "Макет", "레이아웃", "Bố cục", "Layout")
t("Lead", "Pwopriyetè", "Лид", "리드", "Khách hàng tiềm năng", "Lead")
t("Lead Details", "Detay Pwopriyetè", "Детали лида", "리드 상세", "Chi tiết khách hàng tiềm năng", "Detalye ng Lead")
t("Lead Distribution", "Distribisyon Pwopriyetè", "Распределение лидов", "리드 배분", "Phân phối khách hàng tiềm năng", "Distribusyon ng Lead")
t("Lead Idle", "Pwopriyetè Inaktif", "Неактивный лид", "비활성 리드", "Khách hàng tiềm năng không hoạt động", "Lead na Idle")
t("Lead Paint Suspect", "Sispèk Penti Plom", "Подозрение на свинцовую краску", "납 페인트 의심", "Nghi ngờ sơn chì", "May Suspetsa ng Lead Paint")
t("Lead Routing", "Direksyon Pwopriyetè", "Маршрутизация лидов", "리드 라우팅", "Định tuyến khách hàng tiềm năng", "Lead Routing")
t("Lead Score", "Pwen Pwopriyetè", "Оценка лида", "리드 점수", "Điểm khách hàng tiềm năng", "Lead Score")
t("Lead Source", "Sous Pwopriyetè", "Источник лида", "리드 소스", "Nguồn khách hàng tiềm năng", "Pinagmulan ng Lead")
t("Lead Tech", "Teknisyen Prensipal", "Ведущий техник", "담당 기술자", "Kỹ thuật viên chính", "Lead Tech")
t("Lease Details", "Detay Kontra", "Детали аренды", "임대 상세", "Chi tiết hợp đồng thuê", "Detalye ng Lease")
t("Lease End", "Fen Kontra", "Окончание аренды", "임대 종료", "Kết thúc hợp đồng thuê", "Katapusan ng Lease")
t("Lease History", "Istwa Kontra", "История аренды", "임대 이력", "Lịch sử hợp đồng thuê", "Kasaysayan ng Lease")
t("Lease Start", "Kòmansman Kontra", "Начало аренды", "임대 시작", "Bắt đầu hợp đồng thuê", "Simula ng Lease")
t("Lease Type", "Tip Kontra", "Тип аренды", "임대 유형", "Loại hợp đồng thuê", "Uri ng Lease")
t("Lease not found", "Kontra pa jwenn", "Аренда не найдена", "임대를 찾을 수 없음", "Không tìm thấy hợp đồng thuê", "Hindi nahanap ang lease")
t("Leases", "Kontra", "Аренды", "임대", "Hợp đồng thuê", "Mga Lease")
t("Leases Expiring (30d)", "Kontra Ap Ekspire (30j)", "Аренды с истекающим сроком (30д)", "만료 예정 임대 (30일)", "Hợp đồng thuê sắp hết hạn (30 ngày)", "Mga Lease na Mag-e-expire (30 araw)")
t("Ledger", "Rejis", "Книга учёта", "원장", "Sổ cái", "Ledger")
t("Legal/professional fees", "Frè legal/pwofesyonèl", "Юр./проф. услуги", "법률/전문 비용", "Phí pháp lý/chuyên môn", "Legal/professional fees")
t("Legend", "Lejand", "Легенда", "범례", "Chú giải", "Legend")
t("Lender", "Pretè", "Кредитор", "대출기관", "Bên cho vay", "Nagpapautang")
t("Less", "Mwens", "Меньше", "이하", "Ít hơn", "Mas Kaunti")
t("Liabilities", "Obligasyon", "Обязательства", "부채", "Nợ phải trả", "Mga Pananagutan")
t("License", "Lisans", "Лицензия", "면허", "Giấy phép", "Lisensya")
t("License #", "Lisans #", "Лицензия #", "면허 #", "Giấy phép #", "Lisensya #")
t("License Expiry", "Ekspirasyon Lisans", "Истечение лицензии", "면허 만료", "Hết hạn giấy phép", "Pag-expire ng Lisensya")
t("License Number", "Nimewo Lisans", "Номер лицензии", "면허 번호", "Số giấy phép", "Numero ng Lisensya")
t("License Plate", "Plak Machin", "Номерной знак", "번호판", "Biển số xe", "Plaka")
t("License Renewal", "Renouvèlman Lisans", "Продление лицензии", "면허 갱신", "Gia hạn giấy phép", "Pag-renew ng Lisensya")
t("License State", "Eta Lisans", "Штат лицензии", "면허 발급 주", "Bang cấp giấy phép", "Estado ng Lisensya")
t("Lien", "Lyen", "Залоговое право", "유치권", "Quyền giữ tài sản", "Lien")
t("Lien Filing", "Depo Lyen", "Подача залогового иска", "유치권 신청", "Nộp đơn giữ tài sản", "Pag-file ng Lien")
t("Lien Lifecycle", "Sik Lavi Lyen", "Жизненный цикл залога", "유치권 수명주기", "Vòng đời quyền giữ tài sản", "Lifecycle ng Lien")
t("Lien Protection", "Pwoteksyon Lyen", "Защита залоговых прав", "유치권 보호", "Bảo vệ quyền giữ tài sản", "Lien Protection")
t("Lien Releases", "Liberasyon Lyen", "Снятие залога", "유치권 해제", "Giải trừ quyền giữ tài sản", "Mga Lien Release")
t("Lien Tracker", "Swivi Lyen", "Отслеживание залогов", "유치권 추적", "Theo dõi quyền giữ tài sản", "Lien Tracker")
t("Lien tracking starts when jobs have outstanding payments", "Swivi lyen kòmanse lè travay gen peman anreta", "Отслеживание залогов начинается при наличии неоплаченных заказов", "미지급 작업이 있을 때 유치권 추적이 시작됩니다", "Theo dõi quyền giữ tài sản bắt đầu khi công việc có khoản thanh toán chưa trả", "Nagsisimula ang lien tracking kapag may mga trabahong may hindi pa nababayaran")
t("Lifetime Revenue", "Revni Atoutjamè", "Доход за всё время", "총 수익", "Doanh thu trọn đời", "Lifetime Revenue")
t("Lifetime Value", "Valè Atoutjamè", "Пожизненная ценность", "총 가치", "Giá trị trọn đời", "Lifetime Value")
t("Light Mode", "Mòd Klè", "Светлая тема", "라이트 모드", "Chế độ sáng", "Light Mode")
t("Line Items", "Atik Liy", "Позиции", "항목", "Mục hàng", "Mga Line Item")
t("Link", "Lyen", "Ссылка", "링크", "Liên kết", "Link")
t("Link Team Member", "Lye Manm Ekip", "Привязать члена команды", "팀원 연결", "Liên kết thành viên nhóm", "I-link ang Team Member")
t("List", "Lis", "Список", "목록", "Danh sách", "Listahan")
t("Load More", "Chaje Plis", "Загрузить ещё", "더 불러오기", "Tải thêm", "Mag-load pa")
t("Load-Bearing", "Pòt Chaj", "Несущий", "하중 지지", "Chịu tải", "Load-Bearing")
t("Loading Schedule C data...", "Ap chaje done Orè C...", "Загрузка данных Schedule C...", "Schedule C 데이터 로딩 중...", "Đang tải dữ liệu Schedule C...", "Naglo-load ng Schedule C data...")
t("Loading billings...", "Ap chaje faktirasyon...", "Загрузка счетов...", "청구 데이터 로딩 중...", "Đang tải hóa đơn...", "Naglo-load ng mga billing...")
t("Loading branch financial data...", "Ap chaje done finansye branch...", "Загрузка финансов филиала...", "지점 재무 데이터 로딩 중...", "Đang tải dữ liệu tài chính chi nhánh...", "Naglo-load ng branch financial data...")
t("Loading canvas...", "Ap chaje kanva...", "Загрузка холста...", "캔버스 로딩 중...", "Đang tải canvas...", "Naglo-load ng canvas...")
t("Loading configuration...", "Ap chaje konfigirasyon...", "Загрузка настроек...", "설정 로딩 중...", "Đang tải cấu hình...", "Naglo-load ng configuration...")
t("Loading custom fields...", "Ap chaje chan pèsonalize...", "Загрузка пользовательских полей...", "사용자 정의 필드 로딩 중...", "Đang tải trường tùy chỉnh...", "Naglo-load ng custom fields...")
t("Loading financial data...", "Ap chaje done finansye...", "Загрузка финансовых данных...", "재무 데이터 로딩 중...", "Đang tải dữ liệu tài chính...", "Naglo-load ng financial data...")
t("Loading floor plans...", "Ap chaje plan etaj...", "Загрузка планов этажей...", "평면도 로딩 중...", "Đang tải sơ đồ tầng...", "Naglo-load ng floor plans...")
t("Loading inspections...", "Ap chaje enspeksyon...", "Загрузка инспекций...", "검사 로딩 중...", "Đang tải kiểm tra...", "Naglo-load ng mga inspeksyon...")
t("Loading job context...", "Ap chaje kontèks travay...", "Загрузка контекста заказа...", "작업 컨텍스트 로딩 중...", "Đang tải bối cảnh công việc...", "Naglo-load ng job context...")
t("Loading material data...", "Ap chaje done materyèl...", "Загрузка данных о материалах...", "자재 데이터 로딩 중...", "Đang tải dữ liệu vật liệu...", "Naglo-load ng material data...")
t("Loading retention records...", "Ap chaje dosye retansyon...", "Загрузка записей удержания...", "보유 기록 로딩 중...", "Đang tải hồ sơ giữ lại...", "Naglo-load ng retention records...")
t("Loading scans...", "Ap chaje eskanè...", "Загрузка сканов...", "스캔 로딩 중...", "Đang tải bản quét...", "Naglo-load ng mga scan...")
t("Loading scorecards...", "Ap chaje fich pwen...", "Загрузка карточек показателей...", "스코어카드 로딩 중...", "Đang tải bảng điểm...", "Naglo-load ng mga scorecard...")
t("Loading session info...", "Ap chaje enfò sesyon...", "Загрузка информации о сессии...", "세션 정보 로딩 중...", "Đang tải thông tin phiên...", "Naglo-load ng session info...")
t("Loading templates...", "Ap chaje modèl...", "Загрузка шаблонов...", "템플릿 로딩 중...", "Đang tải mẫu...", "Naglo-load ng mga template...")
t("Loans / Equity", "Prè / Ekite", "Кредиты / Капитал", "대출 / 자본", "Vay / Vốn chủ sở hữu", "Mga Loan / Equity")
t("Location:", "Kote:", "Местоположение:", "위치:", "Vị trí:", "Lokasyon:")
t("Locations", "Kote", "Местоположения", "위치", "Vị trí", "Mga Lokasyon")
t("Lock", "Vewouye", "Замок", "잠금", "Khóa", "Lock")
t("Locksmith Services", "Sèvis Seritye", "Слесарные услуги", "열쇠 서비스", "Dịch vụ thợ khóa", "Mga Serbisyo ng Locksmith")
t("Log", "Jounal", "Журнал", "로그", "Nhật ký", "Log")
t("Log Fuel", "Anrejistre Gaz", "Записать заправку", "연료 기록", "Ghi nhiên liệu", "Mag-log ng Fuel")
t("Logout", "Dekonekte", "Выход", "로그아웃", "Đăng xuất", "Mag-logout")
t("Loom-style video messages tied to jobs", "Mesaj videyo estil Loom lye ak travay", "Видеосообщения в стиле Loom привязанные к заказам", "작업에 연결된 Loom 스타일 비디오 메시지", "Tin nhắn video kiểu Loom gắn với công việc", "Loom-style na video message na nakalink sa mga trabaho")
t("Loss", "Pèt", "Убыток", "손실", "Tổn thất", "Pagkalugi")
t("Loss Description", "Deskripsyon Pèt", "Описание убытка", "손실 설명", "Mô tả tổn thất", "Paglalarawan ng Pagkalugi")
t("Loss Details", "Detay Pèt", "Детали убытка", "손실 상세", "Chi tiết tổn thất", "Detalye ng Pagkalugi")
t("Loss Type", "Tip Pèt", "Тип убытка", "손실 유형", "Loại tổn thất", "Uri ng Pagkalugi")
t("Loss Types Covered", "Tip Pèt Kouvri", "Покрываемые типы убытков", "보장 손실 유형", "Các loại tổn thất được bảo hiểm", "Mga Uri ng Pagkalugi na Covered")
t("Lost", "Pèdi", "Потеряно", "분실", "Mất", "Nawala")
t("Lost Bids", "Òf Pèdi", "Потерянные заявки", "유실 입찰", "Đấu thầu thất bại", "Mga Natalo na Bid")
t("Lost Reason", "Rezon Pèt", "Причина потери", "분실 사유", "Lý do mất", "Dahilan ng Pagkatalo")
t("Lot Size", "Gwosè Teren", "Размер участка", "대지 면적", "Diện tích đất", "Lot Size")
t("Low", "Ba", "Низкий", "낮음", "Thấp", "Mababa")
t("Low Stock", "Estòk Ba", "Мало на складе", "재고 부족", "Tồn kho thấp", "Mababang Stock")
t("Lowest Reading", "Lekti Pi Ba", "Наименьшее показание", "최저 판독값", "Số đọc thấp nhất", "Pinakamababang Reading")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
