#!/usr/bin/env python3
"""5-language batch 10: N values (first half: N/A through No GPS)"""
import json, subprocess, os

LOCALES = ['ht', 'ru', 'ko', 'vi', 'tl']
dicts = {}
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    if os.path.exists(f):
        with open(f, "r", encoding="utf-8") as fh: dicts[loc] = json.load(fh)
    else: dicts[loc] = {}

def t(en, ht_v, ru_v, ko_v, vi_v, tl_v):
    dicts['ht'][en]=ht_v; dicts['ru'][en]=ru_v; dicts['ko'][en]=ko_v; dicts['vi'][en]=vi_v; dicts['tl'][en]=tl_v

t("N/A", "N/A", "Н/Д", "해당없음", "Không áp dụng", "N/A")
t("Name *", "Non *", "Имя *", "이름 *", "Tên *", "Pangalan *")
t("Navigate to any books section", "Navige nan nenpòt seksyon liv", "Перейти в любой раздел бухгалтерии", "모든 회계 섹션으로 이동", "Điều hướng đến bất kỳ phần sổ sách nào", "Mag-navigate sa kahit anong books section")
t("Need Response", "Bezwen Repons", "Требуется ответ", "응답 필요", "Cần phản hồi", "Kailangan ng Tugon")
t("Needing Service", "Bezwen Sèvis", "Нуждается в обслуживании", "서비스 필요", "Cần dịch vụ", "Nangangailangan ng Serbisyo")
t("Needs Review", "Bezwen Revizyon", "Требует проверки", "검토 필요", "Cần xem xét", "Kailangan i-review")
t("Net Change in Cash", "Chanjman Nèt nan Lajan", "Чистое изменение денежных средств", "순현금 변동", "Thay đổi ròng tiền mặt", "Net Change sa Cash")
t("Net Income", "Revni Nèt", "Чистый доход", "순이익", "Thu nhập ròng", "Net Income")
t("Net Margin", "Maj Nèt", "Чистая маржа", "순마진", "Biên lợi nhuận ròng", "Net Margin")
t("Net Operating", "Fonksyonnman Nèt", "Чистая операционная", "순영업", "Hoạt động ròng", "Net Operating")
t("Net Pay", "Salè Nèt", "Чистая зарплата", "순급여", "Lương thực nhận", "Net Pay")
t("Net Payable", "Peye Nèt", "Чистая кредиторская", "순지급액", "Phải trả ròng", "Net Payable")
t("Net Profit", "Pwofi Nèt", "Чистая прибыль", "순이익", "Lợi nhuận ròng", "Net Profit")
t("Net Rental", "Lwaye Nèt", "Чистая аренда", "순임대", "Thuê ròng", "Net Rental")
t("Net Rental Income", "Revni Lwaye Nèt", "Чистый арендный доход", "순임대 수입", "Thu nhập cho thuê ròng", "Net Rental Income")
t("Net Terms", "Tèm Nèt", "Условия оплаты", "결제 조건", "Điều khoản thanh toán", "Net Terms")
t("Net to Customer", "Nèt pou Kliyan", "Итого клиенту", "고객 순수령액", "Ròng cho khách hàng", "Net sa Customer")
t("Network error. Check your connection.", "Erè rezo. Verifye koneksyon ou.", "Ошибка сети. Проверьте подключение.", "네트워크 오류. 연결을 확인하세요.", "Lỗi mạng. Kiểm tra kết nối.", "Network error. Suriin ang connection mo.")
t("Neutral", "Nèt", "Нейтральный", "중립", "Trung tính", "Neutral")
t("New Agreement", "Nouvo Akò", "Новое соглашение", "새 계약", "Thỏa thuận mới", "Bagong Kasunduan")
t("New Applicants", "Nouvo Aplikan", "Новые кандидаты", "새 지원자", "Ứng viên mới", "Mga Bagong Aplikante")
t("New Area Scan", "Nouvo Eskanè Zòn", "Новое сканирование зоны", "새 구역 스캔", "Quét khu vực mới", "Bagong Area Scan")
t("New Automation", "Nouvo Otomatizasyon", "Новая автоматизация", "새 자동화", "Tự động hóa mới", "Bagong Automation")
t("New Bid", "Nouvo Òf", "Новая заявка", "새 입찰", "Đấu thầu mới", "Bagong Bid")
t("New Call", "Nouvo Apèl", "Новый звонок", "새 통화", "Cuộc gọi mới", "Bagong Tawag")
t("New Change Order", "Nouvo Òd Chanjman", "Новое изменение заказа", "새 변경 주문", "Lệnh thay đổi mới", "Bagong Change Order")
t("New Channel", "Nouvo Kanal", "Новый канал", "새 채널", "Kênh mới", "Bagong Channel")
t("New Claim", "Nouvo Reklamasyon", "Новая заявка", "새 청구", "Yêu cầu bồi thường mới", "Bagong Claim")
t("New Customer", "Nouvo Kliyan", "Новый клиент", "새 고객", "Khách hàng mới", "Bagong Customer")
t("New Document", "Nouvo Dokiman", "Новый документ", "새 문서", "Tài liệu mới", "Bagong Dokumento")
t("New Employee", "Nouvo Anplwaye", "Новый сотрудник", "새 직원", "Nhân viên mới", "Bagong Empleyado")
t("New Event", "Nouvo Evènman", "Новое событие", "새 이벤트", "Sự kiện mới", "Bagong Event")
t("New Expense", "Nouvo Depans", "Новый расход", "새 지출", "Chi phí mới", "Bagong Gastos")
t("New Floor Plan", "Nouvo Plan Etaj", "Новый план этажа", "새 평면도", "Sơ đồ tầng mới", "Bagong Floor Plan")
t("New Inspection", "Nouvo Enspeksyon", "Новая инспекция", "새 검사", "Kiểm tra mới", "Bagong Inspeksyon")
t("New Invoice", "Nouvo Fakti", "Новый счёт", "새 청구서", "Hóa đơn mới", "Bagong Invoice")
t("New Job", "Nouvo Travay", "Новый заказ", "새 작업", "Công việc mới", "Bagong Trabaho")
t("New Job Posting", "Nouvo Piblikasyon Travay", "Новая вакансия", "새 채용 공고", "Tin tuyển dụng mới", "Bagong Job Posting")
t("New Lead", "Nouvo Pwopriyetè", "Новый лид", "새 리드", "Khách hàng tiềm năng mới", "Bagong Lead")
t("New Leads", "Nouvo Pwopriyetè", "Новые лиды", "새 리드", "Khách hàng tiềm năng mới", "Mga Bagong Lead")
t("New Message", "Nouvo Mesaj", "Новое сообщение", "새 메시지", "Tin nhắn mới", "Bagong Mensahe")
t("New PO", "Nouvo BC", "Новый заказ на закупку", "새 발주서", "Đơn đặt hàng mới", "Bagong PO")
t("New Password", "Nouvo Modpas", "Новый пароль", "새 비밀번호", "Mật khẩu mới", "Bagong Password")
t("New Pay Period", "Nouvo Peryòd Salè", "Новый период оплаты", "새 급여 기간", "Kỳ trả lương mới", "Bagong Pay Period")
t("New Permit", "Nouvo Pèmi", "Новое разрешение", "새 허가", "Giấy phép mới", "Bagong Permit")
t("New Permit Application", "Nouvo Aplikasyon Pèmi", "Новая заявка на разрешение", "새 허가 신청", "Đơn xin giấy phép mới", "Bagong Permit Application")
t("New Progress Billing Application", "Nouvo Aplikasyon Faktirasyon Pwogrè", "Новая заявка на прогресс-биллинг", "새 진행 청구 신청", "Đơn thanh toán tiến độ mới", "Bagong Progress Billing Application")
t("New Property", "Nouvo Pwopriyete", "Новый объект", "새 부동산", "Bất động sản mới", "Bagong Property")
t("New Property Inspection", "Nouvo Enspeksyon Pwopriyete", "Новая инспекция объекта", "새 부동산 검사", "Kiểm tra bất động sản mới", "Bagong Property Inspection")
t("New Purchase Order", "Nouvo Kòmann Acha", "Новый заказ на закупку", "새 구매 주문", "Đơn đặt mua mới", "Bagong Purchase Order")
t("New Retention Record", "Nouvo Dosye Retansyon", "Новая запись удержания", "새 보유 기록", "Hồ sơ giữ lại mới", "Bagong Retention Record")
t("New Scan", "Nouvo Eskanè", "Новое сканирование", "새 스캔", "Quét mới", "Bagong Scan")
t("New Schedule", "Nouvo Orè", "Новое расписание", "새 일정", "Lịch trình mới", "Bagong Schedule")
t("New Scorecard", "Nouvo Fich Pwen", "Новая карточка", "새 스코어카드", "Bảng điểm mới", "Bagong Scorecard")
t("New Service Agreement", "Nouvo Akò Sèvis", "Новое соглашение об обслуживании", "새 서비스 계약", "Thỏa thuận dịch vụ mới", "Bagong Service Agreement")
t("New Sketch", "Nouvo Eskis", "Новый эскиз", "새 스케치", "Bản phác thảo mới", "Bagong Sketch")
t("New Supplement", "Nouvo Sipleman", "Новое дополнение", "새 추가분", "Bổ sung mới", "Bagong Supplement")
t("New Survey", "Nouvo Sondaj", "Новый обзор", "새 조사", "Khảo sát mới", "Bagong Survey")
t("New TPA Assignment", "Nouvo Asiyasyon TPA", "Новое назначение ТПА", "새 TPA 배정", "Phân công TPA mới", "Bagong TPA Assignment")
t("New Task", "Nouvo Travay", "Новая задача", "새 작업", "Nhiệm vụ mới", "Bagong Task")
t("New Template", "Nouvo Modèl", "Новый шаблон", "새 템플릿", "Mẫu mới", "Bagong Template")
t("New This Week", "Nouvo Semèn Sa a", "Новое за неделю", "이번 주 신규", "Mới trong tuần này", "Bago Ngayong Linggo")
t("New Transaction", "Nouvo Tranzaksyon", "Новая транзакция", "새 거래", "Giao dịch mới", "Bagong Transaksyon")
t("New Unit Turn", "Nouvo Tounen Inite", "Новая смена арендатора", "새 유닛 턴오버", "Luân chuyển đơn vị mới", "Bagong Unit Turn")
t("New Walkthrough", "Nouvo Vizit", "Новый обход", "새 현장 조사", "Khảo sát mới", "Bagong Walkthrough")
t("New Warranty", "Nouvo Garanti", "Новая гарантия", "새 보증", "Bảo hành mới", "Bagong Garantiya")
t("Next Billing", "Pwochen Faktirasyon", "Следующий счёт", "다음 청구", "Thanh toán tiếp theo", "Susunod na Billing")
t("Next Calibration", "Pwochen Kalibrasyon", "Следующая калибровка", "다음 교정", "Hiệu chuẩn tiếp theo", "Susunod na Calibration")
t("Next Due", "Pwochen Dat", "Следующий срок", "다음 기한", "Đến hạn tiếp theo", "Susunod na Due")
t("Next Follow-up", "Pwochen Swivi", "Следующее напоминание", "다음 후속 조치", "Theo dõi tiếp theo", "Susunod na Follow-up")
t("Next Pay Date", "Pwochen Dat Salè", "Следующая зарплата", "다음 급여일", "Ngày trả lương tiếp theo", "Susunod na Pay Date")
t("Next Scheduled", "Pwochen Planifye", "Следующее запланированное", "다음 예정", "Lịch trình tiếp theo", "Susunod na Naka-schedule")
t("Next Service", "Pwochen Sèvis", "Следующее обслуживание", "다음 서비스", "Dịch vụ tiếp theo", "Susunod na Serbisyo")
t("Nextdoor", "Nextdoor", "Nextdoor", "Nextdoor", "Nextdoor", "Nextdoor")
t("No API keys. Generate one to enable integrations.", "Pa gen kle API. Jenere youn pou aktive entegrasyon.", "Нет API-ключей. Сгенерируйте для интеграций.", "API 키가 없습니다. 통합을 활성화하려면 생성하세요.", "Không có khóa API. Tạo một khóa để kích hoạt tích hợp.", "Walang API key. Gumawa ng isa para ma-enable ang integration.")
t("No Assignments", "Pa gen Asiyasyon", "Нет назначений", "배정 없음", "Không có phân công", "Walang Assignment")
t("No Branches Configured", "Pa gen Branch Konfigire", "Нет настроенных филиалов", "설정된 지점 없음", "Chưa cấu hình chi nhánh", "Walang Na-configure na Branch")
t("No CE credits recorded yet", "Pa gen kredi CE anrejistre ankò", "Нет записей о CE-кредитах", "CE 학점 기록 없음", "Chưa ghi nhận tín chỉ CE nào", "Wala pang nairecord na CE credit")
t("No COC Yet", "Pa gen COC Ankò", "Нет COC пока", "COC 없음", "Chưa có COC", "Wala pang COC")
t("No Contents Inventory", "Pa gen Envantè Kontni", "Нет инвентаря содержимого", "내용물 목록 없음", "Không có kiểm kê nội dung", "Walang Contents Inventory")
t("No Discount", "Pa gen Rabè", "Без скидки", "할인 없음", "Không giảm giá", "Walang Discount")
t("No GPS data", "Pa gen done GPS", "Нет данных GPS", "GPS 데이터 없음", "Không có dữ liệu GPS", "Walang GPS data")

# Save and apply
for loc in LOCALES:
    f = f"_{loc}_dict.json"
    with open(f, "w", encoding="utf-8") as fh:
        json.dump(dicts[loc], fh, ensure_ascii=False, indent=2)
    print(f"{loc} dict: {len(dicts[loc])} entries")
    subprocess.run(["python", "_all_langs_apply.py", loc, f])
