"""Translate round 7 keys to Spanish."""
import json, os

TRANS_DIR = os.path.join('src', 'lib', 'translations')

with open(os.path.join(TRANS_DIR, 'es.json'), encoding='utf-8') as f:
    es = json.load(f)

common_es = {
    "own": "Propio",
    "airMovers": "Movedores de aire",
    "dehu": "Deshu",
    "scrubbers": "Purificadores",
    "volume": "Volumen",
    "floor": "Piso",
    "walls": "Paredes",
    "ceiling": "Techo",
    "notRecorded": "No registrado",
    "selectAll": "Seleccionar todo",
    "clearAll": "Limpiar todo",
    "preview": "Vista previa",
    "template": "Plantilla",
    "templates": "Plantillas",
    "frequency": "Frecuencia",
    "weekly": "Semanal",
    "monthly": "Mensual",
    "quarterly": "Trimestral",
    "annually": "Anual",
    "daily": "Diario",
    "custom": "Personalizado",
    "percentage": "Porcentaje",
    "amount": "Monto",
    "count": "Conteo",
    "average": "Promedio",
    "minimum": "Minimo",
    "maximum": "Maximo",
    "firstAndLast": "Primero y ultimo",
    "sendNow": "Enviar ahora",
    "sendLater": "Enviar despues",
    "schedule": "Programar",
    "addNote": "Agregar nota",
    "addPhoto": "Agregar foto",
    "addDocument": "Agregar documento",
    "addAttachment": "Agregar adjunto",
    "viewDetails": "Ver detalles",
    "viewAll": "Ver todo",
    "showMore": "Mostrar mas",
    "showLess": "Mostrar menos",
    "loadMore": "Cargar mas",
    "noResults": "Sin resultados",
    "noData": "Sin datos",
    "unknown": "Desconocido",
    "none": "Ninguno",
    "all": "Todo",
    "yes": "Si",
    "no": "No",
    "open": "Abierto",
    "closed": "Cerrado",
    "archived": "Archivado",
    "inProgress": "En progreso",
    "onHold": "En espera",
    "cancelled": "Cancelado",
    "rejected": "Rechazado",
    "expired": "Vencido",
    "renewed": "Renovado",
    "verified": "Verificado",
    "unverified": "No verificado",
    "critical": "Critico",
    "warning": "Advertencia",
    "info": "Info",
    "success": "Exito",
    "error": "Error",
    "priority": "Prioridad",
    "assignee": "Asignado",
    "dueDate": "Fecha de vencimiento",
    "createdDate": "Fecha de creacion",
    "lastUpdated": "Ultima actualizacion",
    "nextDue": "Proximo vencimiento",
    "attachments": "Adjuntos",
    "comments": "Comentarios",
    "history": "Historial",
    "timeline": "Linea de tiempo",
    "overview": "Vista general",
    "summary": "Resumen",
    "analytics": "Analiticas",
    "dashboard": "Panel",
    "settings": "Configuracion",
    "profile": "Perfil",
    "notifications": "Notificaciones",
    "preferences": "Preferencias",
    "help": "Ayuda",
    "logout": "Cerrar sesion",
    "previous": "Anterior",
    "next": "Siguiente",
    "back": "Atras",
    "forward": "Adelante",
    "refresh": "Actualizar",
    "retry": "Reintentar",
    "confirm": "Confirmar",
    "submit": "Enviar",
    "apply": "Aplicar",
    "reset": "Restablecer",
    "clear": "Limpiar",
    "upload": "Subir",
    "download": "Descargar",
    "import": "Importar",
    "export": "Exportar",
    "print": "Imprimir",
    "copy": "Copiar",
    "paste": "Pegar",
    "duplicate": "Duplicar",
    "move": "Mover",
    "rename": "Renombrar",
    "archive": "Archivar",
    "restore": "Restaurar",
    "enable": "Habilitar",
    "disable": "Deshabilitar",
    "activate": "Activar",
    "deactivate": "Desactivar",
    "suspend": "Suspender",
    "resume": "Reanudar",
    "approve": "Aprobar",
    "reject": "Rechazar",
    "send": "Enviar",
    "receive": "Recibir",
    "accept": "Aceptar",
    "decline": "Declinar",
    "assign": "Asignar",
    "unassign": "Desasignar",
    "link": "Enlazar",
    "unlink": "Desenlazar",
    "merge": "Fusionar",
    "split": "Dividir",
    "lock": "Bloquear",
    "unlock": "Desbloquear",
    "pin": "Fijar",
    "unpin": "Desfijar",
    "star": "Marcar",
    "unstar": "Desmarcar",
    "flag": "Senalar",
    "unflag": "Quitar senalamiento",
    "follow": "Seguir",
    "unfollow": "Dejar de seguir",
    "share": "Compartir",
    "mute": "Silenciar",
    "unmute": "Desilenciar",
    "block": "Bloquear",
    "unblock": "Desbloquear",
    "report": "Reportar",
}

page_es = {
    "settings": {
        "configureNotifications": "Configura que notificaciones deseas recibir",
        "configureWorkflowAutomation": "Configura automatizacion de flujos para recorridos",
        "enableDisableHere": "Habilita/deshabilita canales de notificacion aqui",
        "savedSuccessfully": "Guardado exitosamente",
        "stripeConnected": "Stripe conectado",
        "notConnected": "No conectado",
        "displayName": "Nombre a mostrar",
        "aboutYourCompany": "Acerca de tu empresa",
        "storageUsed": "Almacenamiento usado",
        "auditLogEntries": "Registros de auditoria",
        "dataExport": "Exportacion de datos",
    },
    "estimates": {
        "mat": "MAT:",
        "lab": "M.O.:",
        "equ": "EQU:",
        "title": "Titulo:",
        "customer": "Cliente:",
        "address": "Direccion:",
        "cityStateZip": "Ciudad/Estado/CP:",
        "claimNumber": "Reclamo #:",
        "policyNumber": "Poliza #:",
        "carrierLabel": "Aseguradora:",
        "adjusterLabel": "Ajustador:",
        "deductibleLabel": "Deducible:",
        "claimLabel": "Reclamo:",
        "policyLabel": "Poliza:",
    },
    "marketplace": {
        "locationLabel": "Ubicacion:",
        "tradeLabel": "Oficio:",
        "serviceLabel": "Servicio:",
        "urgencyLabel": "Urgencia:",
        "budgetLabel": "Presupuesto:",
        "descriptionLabel": "Descripcion:",
        "amountLabel": "Monto:",
        "typeLabel": "Tipo:",
        "timelineLabel": "Plazo:",
        "warrantyLabel": "Garantia:",
        "submittedLabel": "Enviado:",
    },
    "email": {
        "composeEmail": "Redactar correo",
        "inbox": "Bandeja de entrada",
        "drafts": "Borradores",
        "allMail": "Todo el correo",
        "noEmailsFound": "No se encontraron correos",
        "manageEmailCommunications": "Administra comunicaciones por correo con clientes",
        "from": "De",
        "snippet": "Fragmento",
        "reply": "Responder",
        "replyAll": "Responder a todos",
        "forward": "Reenviar",
        "markRead": "Marcar como leido",
        "markUnread": "Marcar como no leido",
        "moveToTrash": "Mover a papelera",
        "noConversationSelected": "Sin conversacion seleccionada",
        "selectConversation": "Selecciona una conversacion para ver",
    },
    "scheduling": {
        "criticalPath": "Ruta critica",
        "ganttChart": "Diagrama de Gantt",
        "addDependency": "Agregar dependencia",
        "addMilestone": "Agregar hito",
        "delayDays": "Dias de retraso",
        "slackDays": "Dias de holgura",
        "earlyStart": "Inicio temprano",
        "lateFinish": "Fin tardio",
        "noTasksScheduled": "Sin tareas programadas",
    },
    "books": {
        "accountNumber": "Cuenta #",
        "financialOverview": "Vista general financiera",
        "quickAccess": "Acceso rapido",
        "recentTransactions": "Transacciones recientes",
        "monthlyTrend": "Tendencia mensual",
        "navigateToSection": "Navegar a cualquier seccion de libros",
        "cashBalance": "Saldo en efectivo",
        "outstandingInvoices": "Facturas pendientes",
        "unpaidBills": "Cuentas sin pagar",
        "profitThisMonth": "Utilidad este mes",
    },
    "recon": {
        "scanDate": "Fecha de escaneo",
        "sources": "Fuentes",
        "measurements": "Mediciones",
        "scanType": "Tipo de escaneo",
        "scanOptions": "Opciones de escaneo",
        "addAddress": "Agregar direccion",
    },
    "walkthroughs": {
        "walkthroughDetails": "Detalles del recorrido",
        "scopeOfWork": "Alcance del trabajo",
        "measurementData": "Datos de medicion",
        "generateBid": "Generar oferta",
        "roomList": "Lista de habitaciones",
        "damageAssessment": "Evaluacion de danos",
        "noWalkthroughsFound": "No se encontraron recorridos",
    },
    "invoices": {
        "invoiceNotFound": "Factura no encontrada",
        "paymentHistory": "Historial de pagos",
        "sendInvoice": "Enviar factura",
        "createInvoice": "Crear factura",
        "invoiceTotal": "Total de factura",
        "balanceDue": "Saldo pendiente",
        "amountPaid": "Monto pagado",
        "paymentTerms": "Terminos de pago",
    },
    "bids": {
        "bidOverview": "Vista general de oferta",
        "optimizePrice": "Optimizar precio",
        "bidNotFound": "Oferta no encontrada",
        "winProbability": "Probabilidad de ganar",
        "competitorAnalysis": "Analisis de competencia",
        "priceOptimization": "Optimizacion de precio",
    },
    "changeOrders": {
        "changeOrderTracker": "Rastreador de ordenes de cambio",
        "newChangeOrder": "Nueva orden de cambio",
        "changeOrderAmount": "Monto de orden de cambio",
        "approvalRequired": "Aprobacion requerida",
        "originalAmount": "Monto original",
        "revisedAmount": "Monto revisado",
    },
    "documents": {
        "documentLibrary": "Biblioteca de documentos",
        "allDocuments": "Todos los documentos",
        "sharedWithMe": "Compartidos conmigo",
        "noDocumentsFound": "No se encontraron documentos",
        "fileType": "Tipo de archivo",
        "fileSize": "Tamano de archivo",
        "lastModified": "Ultima modificacion",
    },
    "lienProtection": {
        "lienTracker": "Rastreador de gravamenes",
        "noticesSent": "Avisos enviados",
        "lienReleases": "Liberaciones de gravamen",
        "deadlineApproaching": "Plazo acercandose",
        "noLienItems": "Sin elementos de gravamen",
    },
    "serviceAgreements": {
        "agreementTracker": "Rastreador de acuerdos",
        "newAgreement": "Nuevo acuerdo",
        "renewalDate": "Fecha de renovacion",
        "serviceFrequency": "Frecuencia de servicio",
        "noAgreementsFound": "No se encontraron acuerdos",
    },
    "propertyManagement": {
        "leaseDetails": "Detalles del contrato",
        "tenantInfo": "Info del inquilino",
        "unitDetails": "Detalles de la unidad",
        "rentRoll": "Registro de rentas",
        "moveInDate": "Fecha de mudanza",
        "moveOutDate": "Fecha de salida",
        "securityDeposit": "Deposito de seguridad",
        "monthlyRent": "Renta mensual",
        "leaseStart": "Inicio del contrato",
        "leaseEnd": "Fin del contrato",
        "noLeases": "Sin contratos",
        "noTenants": "Sin inquilinos",
        "noUnits": "Sin unidades",
    },
}

common = es.setdefault("common", {})
for k, v in common_es.items():
    common[k] = v

for ns, keys in page_es.items():
    if ns not in es:
        es[ns] = {}
    for k, v in keys.items():
        es[ns][k] = v

with open(os.path.join(TRANS_DIR, 'es.json'), 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)
    f.write('\n')

total = len(common_es) + sum(len(keys) for keys in page_es.values())
print(f"Set {total} Spanish translations")
